/***********************************************************************
 * FILE: AcceptedNotificationAuditPlanningRecovery.js
 * BUILD: 2026-09-17_ACCEPTED_NOTIFICATION_AP_RECOVERY_R5_TARGET4_LOCATE
 * Read-only targeted diagnosis + guarded queue-only recovery.
 ***********************************************************************/
var ANAPR_BUILD='2026-09-17_ACCEPTED_NOTIFICATION_AP_RECOVERY_R5_TARGET4_LOCATE';
var ANAPR_TARGET4=['AUD_FernandezMoreno-Mate_HQ_1777531729292_30','AUD_Imaginaplant,S.L._HQ_1777531729367_46','AUD_I.P.C.Alfa3Almerimar_HQ_1777531729359_44','AUD_PlantalProduccionesS_HQ_1777531729439_61'];
function ANAPR_clean_(v){return String(v==null?'':v).trim();}
function ANAPR_norm_(v){return ANAPR_clean_(v).replace(/[–—−]/g,'-').replace(/\u00A0/g,' ').replace(/[\u200B-\u200D\uFEFF]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function ANAPR_header_(h,n){var m={};for(var i=0;i<(h||[]).length;i++){var k=ANAPR_norm_(h[i]);if(k&&m[k]===undefined)m[k]=i;}for(var j=0;j<(n||[]).length;j++){var w=ANAPR_norm_(n[j]);if(Object.prototype.hasOwnProperty.call(m,w))return m[w];}return-1;}
function ANAPR_iso_(v){if(v instanceof Date&&!isNaN(v.getTime()))return v.toISOString();return ANAPR_clean_(v);}
function ANAPR_loadAll_(ss){var sh=ss.getSheetByName('Audit planning');if(!sh)throw new Error("Missing sheet 'Audit planning'");var lr=sh.getLastRow(),lc=sh.getLastColumn(),v=lr&&lc?sh.getRange(1,1,lr,lc).getValues():[],h=v[0]||[],c={id:ANAPR_header_(h,['Audit ID','Audit_ID','AuditId']),status:ANAPR_header_(h,['Status']),decision:ANAPR_header_(h,['Last auditor decision']),stamp:ANAPR_header_(h,['Last auditor decision timestamp']),assigned:ANAPR_header_(h,['Assigned to','Assigned To','Assigned auditor','Assigned Auditor','Assigned']),planned:ANAPR_header_(h,['Date - Planned','Date – Planned','Date planned','Date Planned']),approved:ANAPR_header_(h,['Date - Approved','Date – Approved','Date approved','Date Approved'])};if(c.id<0)throw new Error('Audit ID column missing');var out=[];for(var r=1;r<v.length;r++){var row=v[r]||[],id=ANAPR_clean_(row[c.id]);if(!id)continue;out.push({auditId:id,rowNumber:r+1,status:c.status>=0?ANAPR_clean_(row[c.status]):'',assigned:c.assigned>=0?ANAPR_clean_(row[c.assigned]):'',planned:c.planned>=0?ANAPR_iso_(row[c.planned]):'',approved:c.approved>=0?ANAPR_iso_(row[c.approved]):'',decision:c.decision>=0?ANAPR_clean_(row[c.decision]):'',stamp:c.stamp>=0?ANAPR_iso_(row[c.stamp]):''});}return out;}
function RUN_ACCEPTED_NOTIFICATION_AP_TARGET4_LOCATE(){var st=Date.now(),out={ok:true,build:ANAPR_BUILD,targetCount:4,found:0,items:[],errors:[]};try{var ss=SpreadsheetApp.getActiveSpreadsheet()||SpreadsheetApp.getActive(),q=ss.getSheetByName('Notification Queue'),queue=AcceptedNotificationReconciler_LoadQueue_(q),a=ANAPR_loadAll_(ss),m={};for(var i=0;i<a.length;i++)m[a[i].auditId]=a[i];for(var j=0;j<ANAPR_TARGET4.length;j++){var id=ANAPR_TARGET4[j],x=m[id];if(!x){out.items.push({auditId:id,found:false});continue;}out.found++;out.items.push({auditId:id,found:true,rowNumber:x.rowNumber,status:x.status,assigned:x.assigned,planned:x.planned,approved:x.approved,lastAuditorDecision:x.decision,lastAuditorDecisionTimestamp:x.stamp,queueState:AcceptedNotificationReconciler_GetRequiredEventState_(queue,id)});}}catch(e){out.ok=false;out.errors.push({message:ANAPR_clean_(e&&e.message||e)});}out.durationMs=Date.now()-st;Logger.log(JSON.stringify(out,null,2));return out;}
function RUN_ACCEPTED_NOTIFICATION_AP_TARGET4_DRYRUN(){return ANAPR_target4_(true);}
function RUN_ACCEPTED_NOTIFICATION_AP_TARGET4(){return ANAPR_target4_(false);}
function ANAPR_target4_(dry){var st=Date.now(),out={ok:true,build:ANAPR_BUILD,dryRun:dry,targetCount:4,foundAccepted:0,candidates:0,repaired:0,unresolved:0,items:[],errors:[]};try{var ss=SpreadsheetApp.getActiveSpreadsheet()||SpreadsheetApp.getActive(),q=ss.getSheetByName('Notification Queue'),queue=AcceptedNotificationReconciler_LoadQueue_(q),a=ANAPR_loadAll_(ss),m={};for(var i=0;i<a.length;i++)m[a[i].auditId]=a[i];for(var j=0;j<ANAPR_TARGET4.length;j++){var id=ANAPR_TARGET4[j],x=m[id];if(!x||ANAPR_norm_(x.status)!=='accepted'){out.unresolved++;out.items.push({auditId:id,action:'BLOCKED',reason:!x?'NOT_FOUND':'STATUS_'+(x.status||'EMPTY')});continue;}out.foundAccepted++;var before=AcceptedNotificationReconciler_GetRequiredEventState_(queue,id);if(before.complete){out.items.push({auditId:id,action:'SKIP_ALREADY_COMPLETE'});continue;}out.candidates++;if(dry){out.items.push({auditId:id,action:'DRYRUN_REPAIR_NEEDED',status:x.status,assigned:x.assigned,planned:x.planned,state:before});continue;}try{var ctx=AcceptedNotificationReconciler_LoadAuditContext_(id),payload={actorRole:'AUDITOR',action:'ACCEPT',source:'AcceptedNotificationAuditPlanningRecovery_TARGET4',explicitRecovery:true},result={success:true,auditId:id,beforeStatus:'APPROVED',beforeStatusDisplay:'Approved',afterStatus:'ACCEPTED',afterStatusDisplay:'Accepted',newStatus:'Accepted'};StatusNotificationBridge_Dispatch_('ACCEPT','AUDITOR',ctx,payload,result);queue=AcceptedNotificationReconciler_LoadQueue_(q);var after=AcceptedNotificationReconciler_GetRequiredEventState_(queue,id);if(after.complete)out.repaired++;else out.unresolved++;out.items.push({auditId:id,action:after.complete?'REPAIRED':'UNRESOLVED',state:after});}catch(er){out.unresolved++;out.errors.push({auditId:id,message:ANAPR_clean_(er&&er.message||er)});}}}catch(e){out.ok=false;out.errors.push({message:ANAPR_clean_(e&&e.message||e)});}if(out.errors.length||out.unresolved)out.ok=false;out.durationMs=Date.now()-st;Logger.log(JSON.stringify(out,null,2));return out;}
function RUN_ACCEPTED_NOTIFICATION_AP_RECOVERY_REGRESSION(){var out={ok:true,build:ANAPR_BUILD,meta:{readOnlyLocate:true,queueOnlyRepair:true,lifecycleWrites:false,planningWrites:false,availabilityWrites:false,target4:4}};Logger.log(JSON.stringify(out,null,2));return out;}
