/***********************************************************************
 * FILE: AMS01_PlanningWorkspaceRealPeriodPerfTests.js
 * BUILD: 2026-09-10_AMS01_2_WORKSPACE_REAL_PERIOD_PERF_R2_POST_PROFILES
 *
 * PURPOSE
 * - Measure actual Planning Workspace default period: current month +3 months.
 * - Compare cold/warm full context and warm context without Availability.
 * - Surface current service builds and dominant DEV stages after AMS-01.2.
 * - Read-only diagnostics only.
 ***********************************************************************/
var AMS01_WORKSPACE_REAL_PERIOD_PERF_BUILD='2026-09-10_AMS01_2_WORKSPACE_REAL_PERIOD_PERF_R2_POST_PROFILES';
function AMS01_WRP_isoMonthStart_(date,tz){return Utilities.formatDate(date,tz,'yyyy-MM-01');}
function AMS01_WRP_monthEndPlus_(date,monthsAhead,tz){var y=Number(Utilities.formatDate(date,tz,'yyyy')),m=Number(Utilities.formatDate(date,tz,'M'))-1,d=new Date(y,m+monthsAhead+1,0,12,0,0,0);return Utilities.formatDate(d,tz,'yyyy-MM-dd');}
function AMS01_WRP_runContext_(label,from,to,includeAvailability){var started=Date.now(),result=PlanningContextReadModel_get({from:from,to:to,includeAvailability:includeAvailability!==false});return{label:label,wallServerMs:Date.now()-started,includeAvailability:includeAvailability!==false,contextBuild:result?result.build||'':'',demandBuild:result&&result.demand?result.demand.build||'':'',profilesBuild:result&&result.profiles?result.profiles.build||'':'',availabilityBuild:result&&result.availability?result.availability.build||'':'',demandRows:result&&result.demand&&result.demand.rows?result.demand.rows.length:0,companyProfiles:result&&result.profiles&&result.profiles.companies?result.profiles.companies.length:0,auditorProfiles:result&&result.profiles&&result.profiles.auditors?result.profiles.auditors.length:0,availabilityRows:result&&result.availability&&result.availability.rows?result.availability.rows.length:0,devPerformance:result?result.devPerformance||null:null,demandPerformance:result&&result.demand?result.demand.devPerformance||null:null,profilesPerformance:result&&result.profiles?result.profiles.devPerformance||null:null,availabilityPerformance:result&&result.availability?result.availability.devPerformance||null:null};}
function RUN_AMS01_2_PLANNING_WORKSPACE_REAL_PERIOD_PERF(){if(typeof PlanningContextReadModel_get!=='function')throw new Error('PlanningContextReadModel_get unavailable');var ss=SpreadsheetApp.getActive(),tz=ss.getSpreadsheetTimeZone()||Session.getScriptTimeZone(),now=new Date(),from=AMS01_WRP_isoMonthStart_(now,tz),to=AMS01_WRP_monthEndPlus_(now,3,tz);var coldFull=AMS01_WRP_runContext_('COLD_FULL_CONTEXT',from,to,true),warmFull=AMS01_WRP_runContext_('WARM_FULL_CONTEXT',from,to,true),warmNoAvailability=AMS01_WRP_runContext_('WARM_NO_AVAILABILITY',from,to,false);var out={ok:true,build:AMS01_WORKSPACE_REAL_PERIOD_PERF_BUILD,period:{from:from,to:to,timezone:tz},runs:{coldFull:coldFull,warmFull:warmFull,warmNoAvailability:warmNoAvailability},derived:{warmAvailabilityContributionMs:Math.max(0,warmFull.wallServerMs-warmNoAvailability.wallServerMs),coldToWarmGainMs:Math.max(0,coldFull.wallServerMs-warmFull.wallServerMs),coldToWarmGainPct:coldFull.wallServerMs>0?Math.round(((coldFull.wallServerMs-warmFull.wallServerMs)*1000/coldFull.wallServerMs))/10:0},readOnly:true};Logger.log(JSON.stringify(out,null,2));return out;}
