/***********************************************************************
 * FILE: AMS01_Roadmap24CloseoutTests.js
 * BUILD: 2026-09-17_AMS01_ROADMAP_2_4_CLOSEOUT_R2_FULL_SERVER_GATE
 * Consolidated non-destructive DEV close-out gate.
 ***********************************************************************/
var AMS01_ROADMAP24_CLOSEOUT_BUILD='2026-09-17_AMS01_ROADMAP_2_4_CLOSEOUT_R2_FULL_SERVER_GATE';
function AMS01_R24C_clean_(v){return String(v==null?'':v).trim();}
function AMS01_R24C_num_(v){var n=Number(v);return isFinite(n)?n:null;}
function AMS01_R24C_call_(name,fn){var t0=Date.now(),rec={name:name,ok:false,wallMs:0,result:null,error:''};try{var r=fn();rec.wallMs=Date.now()-t0;rec.result=r||null;rec.ok=!!(r&&(r.ok===true||r.success===true));if(!rec.ok&&r&&r.failed===0)rec.ok=true;}catch(e){rec.wallMs=Date.now()-t0;rec.error=AMS01_R24C_clean_(e&&e.message||e);}return rec;}
function AMS01_R24C_require_(name){if(typeof this[name]!=='function')throw new Error('AMS01 Roadmap 2.4 closeout: missing '+name);}
function AMS01_R24C_reg_(rec){var r=rec&&rec.result||{};return{ok:!!rec&&rec.ok===true,total:AMS01_R24C_num_(r.total),passed:AMS01_R24C_num_(r.passed),failed:AMS01_R24C_num_(r.failed),build:AMS01_R24C_clean_(r.build)};}
function AMS01_R24C_workspace_(rec){var r=rec&&rec.result||{},x=r.runs||{},c=x.coldFull||{},w=x.warmFull||{},n=x.warmNoAvailability||{};return{ok:!!rec&&rec.ok===true,period:r.period||null,coldFullMs:AMS01_R24C_num_(c.wallServerMs),warmFullMs:AMS01_R24C_num_(w.wallServerMs),warmNoAvailabilityMs:AMS01_R24C_num_(n.wallServerMs),coldToWarmGainMs:r.derived?AMS01_R24C_num_(r.derived.coldToWarmGainMs):null,warmAvailabilityContributionMs:r.derived?AMS01_R24C_num_(r.derived.warmAvailabilityContributionMs):null};}
function AMS01_R24C_coldRevision_(rec){var r=rec&&rec.result||{},m=r.bulkMeta||{},c=r.checks||{};return{ok:!!rec&&rec.ok===true,serverMs:AMS01_R24C_num_(r.coldServerMs),requested:Array.isArray(r.auditIds)?r.auditIds.length:null,indexReads:AMS01_R24C_num_(m.indexPhysicalSheetReads),rowPayloadReads:AMS01_R24C_num_(m.rowPayloadPhysicalSheetReads),totalPhysicalReads:AMS01_R24C_num_(m.physicalSheetReadsTotal),rangeRows:AMS01_R24C_num_(m.rangeRows),zeroCacheHits:c.zeroCacheHits===true,allTokens:c.allTokens===true};}
function AMS01_R24C_shell_(rec){var r=rec&&rec.result||{},s=r.summary||{};return{ok:!!rec&&rec.ok===true,fileReadTotalMs:AMS01_R24C_num_(s.fileReadTotalMs),templateAvgMs:AMS01_R24C_num_(s.templateAvgMs),rendererAvgMs:AMS01_R24C_num_(s.rendererAvgMs),rendererChars:AMS01_R24C_num_(s.rendererChars)};}
function AMS01_R24C_demand_(rec){var r=rec&&rec.result||{},d=r.defaultHotPath||{},n=r.explicitNoCompanyProjection||{},c=r.withCompanyProjection||{};return{ok:!!rec&&rec.ok===true,period:r.period||null,defaultHotPathMs:AMS01_R24C_num_(d.wallServerMs),explicitNoCompanyProjectionMs:AMS01_R24C_num_(n.wallServerMs),withCompanyProjectionMs:AMS01_R24C_num_(c.wallServerMs),companyProjectionDeltaMs:AMS01_R24C_num_(r.companyProjectionDeltaMs),defaultSkipsCompanyProjection:d.companyProjectionUsed===false};}
function RUN_AMS01_ROADMAP_2_4_CLOSEOUT(){
  if(typeof EnvironmentGuard_getRuntimeEnv==='function'){var env=AMS01_R24C_clean_(EnvironmentGuard_getRuntimeEnv()).toUpperCase();if(env&&env!=='DEV')throw new Error('AMS01 Roadmap 2.4 closeout is DEV-only; runtime='+env);}
  var required=['RUN_PLANNING_WORKSPACE_SHELL_PERFORMANCE_DIAGNOSTIC','RUN_AMS01_2_PLANNING_DEMAND_PERF','RUN_AMS01_2_PLANNING_WORKSPACE_REAL_PERIOD_PERF','RUN_PLANNING_BATCH_REVISION_HYDRATION_COLD_PERF','RUN_PLANNING_BATCH_REVISION_HYDRATION_REGRESSION','RUN_PLANNING_WORKSPACE_RPC_REGRESSION','RUN_PLANNING_BATCH_COMMIT_REGRESSION','RUN_PLANNING_BATCH_COMMIT_INTEGRATION_REGRESSION','RUN_PLANNING_CANONICAL_COMMIT_ORCHESTRATION_REGRESSION'];for(var q=0;q<required.length;q++)AMS01_R24C_require_(required[q]);
  var started=Date.now(),p=[];
  p.push(AMS01_R24C_call_('shellPerformance',function(){return RUN_PLANNING_WORKSPACE_SHELL_PERFORMANCE_DIAGNOSTIC();}));
  p.push(AMS01_R24C_call_('planningDemandPerformance',function(){return RUN_AMS01_2_PLANNING_DEMAND_PERF();}));
  p.push(AMS01_R24C_call_('workspaceRealPeriod',function(){return RUN_AMS01_2_PLANNING_WORKSPACE_REAL_PERIOD_PERF();}));
  p.push(AMS01_R24C_call_('batchRevisionCold',function(){return RUN_PLANNING_BATCH_REVISION_HYDRATION_COLD_PERF();}));
  p.push(AMS01_R24C_call_('batchRevisionRegression',function(){return RUN_PLANNING_BATCH_REVISION_HYDRATION_REGRESSION();}));
  p.push(AMS01_R24C_call_('workspaceRpcRegression',function(){return RUN_PLANNING_WORKSPACE_RPC_REGRESSION();}));
  p.push(AMS01_R24C_call_('batchCommitRegression',function(){return RUN_PLANNING_BATCH_COMMIT_REGRESSION();}));
  p.push(AMS01_R24C_call_('batchCommitIntegration',function(){return RUN_PLANNING_BATCH_COMMIT_INTEGRATION_REGRESSION();}));
  p.push(AMS01_R24C_call_('canonicalCommitOrchestration',function(){return RUN_PLANNING_CANONICAL_COMMIT_ORCHESTRATION_REGRESSION();}));
  var b={};for(var i=0;i<p.length;i++)b[p[i].name]=p[i];var allGreen=p.every(function(x){return x.ok===true;});
  var out={ok:allGreen,build:AMS01_ROADMAP24_CLOSEOUT_BUILD,generatedAt:new Date().toISOString(),durationMs:Date.now()-started,probes:p.map(function(x){return{name:x.name,ok:x.ok,wallMs:x.wallMs,error:x.error};}),serverAcceptance:{shell:AMS01_R24C_shell_(b.shellPerformance),planningDemand:AMS01_R24C_demand_(b.planningDemandPerformance),workspaceRealPeriod:AMS01_R24C_workspace_(b.workspaceRealPeriod),coldBulkRevision:AMS01_R24C_coldRevision_(b.batchRevisionCold),batchRevision:AMS01_R24C_reg_(b.batchRevisionRegression),workspaceRpc:AMS01_R24C_reg_(b.workspaceRpcRegression),batchCommit:AMS01_R24C_reg_(b.batchCommitRegression),batchCommitIntegration:AMS01_R24C_reg_(b.batchCommitIntegration),canonicalCommit:AMS01_R24C_reg_(b.canonicalCommitOrchestration)},architecture:{readModelFirst:true,coarseGrainedWorkspaceRpc:true,batchRevisionHydration:true,physicalNPlusOneRevisionReads:false,perItemCanonicalCommitRevalidation:true,notificationDispatchOutsidePlanningLock:true,reservationReleaseInsideCanonicalLock:true,speculativeRpcRequiredForVisibleCommand:false,canonicalOwnersPreserved:true,secondSsotIntroduced:false},clientAcceptance:{measuredByThisRunner:false,reason:'Browser/GAS proxy/paint walltime cannot be measured truthfully from server-side Apps Script.',requiredDimensions:['login/route -> first usable planning screen','Calendar Shell Interactive','Planning Decision-Ready','Availability perceived latency','month/range navigation browser walltime','Validate browser walltime','Commit browser walltime','RPC queue depth/concurrent request count','visible-vs-speculative contention'],serverCloseoutDoesNotClaimBrowserDoD:true},meta:{nonDestructive:true,devOnly:true,businessWrites:false,notificationQueueWrites:false,canonicalOwnersChanged:false,newSsot:false,roadmap:'2.4',workstream:'AMS-01 Performance & Hot Paths'}};Logger.log(JSON.stringify(out,null,2));return out;
}
