/***********************************************************************
 * FILE: AMS01_AvailabilityPeriodBoundedReadTests.js
 * BUILD: 2026-09-11_AMS01_2_AVAILABILITY_SINGLE_WINDOW_TEST_R3
 *
 * Non-destructive semantic + performance regression for Availability R4.
 ***********************************************************************/
var AMS01_APRM_BOUNDED_TEST_BUILD='2026-09-11_AMS01_2_AVAILABILITY_SINGLE_WINDOW_TEST_R3';
function AMS01_APRM_TEST_period_(){var ss=SpreadsheetApp.getActive(),tz=ss.getSpreadsheetTimeZone()||Session.getScriptTimeZone(),now=new Date(),from=Utilities.formatDate(now,tz,'yyyy-MM-01'),y=Number(Utilities.formatDate(now,tz,'yyyy')),m=Number(Utilities.formatDate(now,tz,'M'))-1,end=new Date(y,m+4,0,12,0,0,0);return{from:from,to:Utilities.formatDate(end,tz,'yyyy-MM-dd'),timezone:tz};}
function AMS01_APRM_TEST_fullBaseline_(input){input=input||{};var ss=SpreadsheetApp.getActive(),tz=ss.getSpreadsheetTimeZone()||Session.getScriptTimeZone(),period=APRM_period_(input,tz),auditorSet=APRM_auditorSet_(input),sh=APRM_sheet_();if(!sh)throw new Error("Missing sheet 'Auditor Availability'");var lastRow=sh.getLastRow(),lastCol=sh.getLastColumn(),headers=sh.getRange(1,1,1,lastCol).getValues()[0]||[],cDate=APRM_findCol_(headers,['Date']),cAud=APRM_findCol_(headers,['Auditor_Email','Auditor Email','Email','E-mail','Auditor_Name','Auditor Name']),cAvail=APRM_findCol_(headers,['Available']),cS1=APRM_findCol_(headers,['First_Audit_Start_Time','First Audit Start Time']),cE1=APRM_findCol_(headers,['First_Audit_End_Time','First Audit End Time']),cID1=APRM_findCol_(headers,['Audit_ID_1','Audit ID 1','AuditId1']),cSt1=APRM_findCol_(headers,['Status_1','Status 1','Status','Source']),cS2=APRM_findCol_(headers,['Second_Audit_Start_Time','Second Audit Start Time']),cE2=APRM_findCol_(headers,['Second_Audit_End_Time','Second Audit End Time']),cID2=APRM_findCol_(headers,['Audit_ID_2','Audit ID 2','AuditId2']),cSt2=APRM_findCol_(headers,['Status_2','Status 2']),cUpd=APRM_findCol_(headers,['Last_Updated','Last Updated','Timestamp']),required=[cDate,cAud,cAvail,cS1,cE1,cID1,cSt1,cS2,cE2,cID2,cSt2,cUpd].filter(function(x){return x>=0;}),maxCol=required.length?Math.max.apply(null,required)+1:lastCol,values=lastRow>=2?sh.getRange(2,1,lastRow-1,maxCol).getValues():[],rows=[];for(var r=0;r<values.length;r++){var row=values[r]||[],date=APRM_isoDate_(row[cDate],tz);if(!date||date<period.from||date>period.to)continue;var auditorEmail=APRM_norm_(row[cAud]);if(!auditorEmail||(auditorSet&&!auditorSet[auditorEmail]))continue;var rec={date:date,auditorEmail:auditorEmail,available:APRM_clean_(row[cAvail]),slots:[],lastUpdated:cUpd>=0?APRM_clean_(row[cUpd]):'',sourceRow:r+2},s1=APRM_slot_(row,cS1,cE1,cID1,cSt1,tz,1),s2=APRM_slot_(row,cS2,cE2,cID2,cSt2,tz,2);if(s1)rec.slots.push(s1);if(s2)rec.slots.push(s2);rows.push(rec);}rows.sort(function(a,b){if(a.auditorEmail!==b.auditorEmail)return a.auditorEmail.localeCompare(b.auditorEmail);if(a.date!==b.date)return a.date.localeCompare(b.date);return a.sourceRow-b.sourceRow;});return rows;}
function AMS01_APRM_TEST_signature_(row){return JSON.stringify({date:row.date,auditorEmail:row.auditorEmail,available:row.available,slots:row.slots,lastUpdated:row.lastUpdated,sourceRow:row.sourceRow});}
function RUN_AMS01_2_AVAILABILITY_BOUNDED_READ_REGRESSION(){var p=AMS01_APRM_TEST_period_(),baselineStart=Date.now(),baseline=AMS01_APRM_TEST_fullBaseline_({from:p.from,to:p.to}),baselineMs=Date.now()-baselineStart,coldStart=Date.now(),cold=AvailabilityPeriodReadModel_get({from:p.from,to:p.to}),coldMs=Date.now()-coldStart,warmStart=Date.now(),warm=AvailabilityPeriodReadModel_get({from:p.from,to:p.to}),warmMs=Date.now()-warmStart,actual=warm&&warm.rows?warm.rows:[],mismatches=[],max=Math.max(baseline.length,actual.length);for(var i=0;i<max;i++){var b=baseline[i]||null,a=actual[i]||null;if(!b||!a||AMS01_APRM_TEST_signature_(b)!==AMS01_APRM_TEST_signature_(a)){mismatches.push({index:i,baseline:b,actual:a});if(mismatches.length>=10)break;}}var workspaceStart=Date.now(),workspace=typeof PlanningContextReadModel_get==='function'?PlanningContextReadModel_get({from:p.from,to:p.to}):null,workspaceMs=Date.now()-workspaceStart,meta=warm?warm.meta||{}:{};var out={ok:mismatches.length===0,build:AMS01_APRM_BOUNDED_TEST_BUILD,serviceBuild:AVAILABILITY_PERIOD_READ_MODEL_BUILD,period:p,baselineRows:baseline.length,actualRows:actual.length,mismatches:mismatches,baselineFullReadMs:baselineMs,coldSingleWindowMs:coldMs,warmSingleWindowMs:warmMs,coldPerformance:cold?cold.devPerformance||null:null,warmPerformance:warm?warm.devPerformance||null:null,meta:meta,singleWindow:{strategy:meta.readStrategy||'',sourceRows:meta.sourceRows||0,periodMatchedRows:meta.periodMatchedRows||0,segmentsRead:meta.segmentsRead||0,scannedRows:meta.scannedRows||0,windowFallback:!!meta.windowFallback},workspace:{wallServerMs:workspaceMs,devPerformance:workspace?workspace.devPerformance||null:null,availabilityPerformance:workspace&&workspace.availability?workspace.availability.devPerformance||null:null,demandPerformance:workspace&&workspace.demand?workspace.demand.devPerformance||null:null,profilesPerformance:workspace&&workspace.profiles?workspace.profiles.devPerformance||null:null},readOnly:true};Logger.log(JSON.stringify(out,null,2));return out;}
