// BUILD: AuditPlanningRowIndexCache_d21_AMS01_DETERMINISTIC_COLD_DIAGNOSTIC_20260917
var MP_AP_INDEX_BUILD='AuditPlanningRowIndexCache_d21_AMS01_DETERMINISTIC_COLD_DIAGNOSTIC_20260917';
var MP_AP_INDEX_NS='mp_audit_planning_index',MP_AP_INDEX_KEY='ap_row_index_v1',MP_AP_INDEX_TTL_SEC=1500,MP_AP_INDEX_EXEC_KEY='AP_ROW_INDEX_V1',MP_AP_ROW_EXEC_PREFIX='AP_ROW_PAYLOAD::';
var MP_AP_ROW_NS='MP_AP_ROW_V1',MP_AP_ROW_TTL_SEC=1500,MP_AP_ROW_GEN_KEY='MP_AP_ROW_GEN_V1';
function __mp_apIndexNativeKey_(){return'MP_PERSIST::'+MP_AP_INDEX_NS+'::'+MP_AP_INDEX_KEY;}
function __mp_apRowGen_(){try{var v=CacheService.getScriptCache().get(MP_AP_ROW_GEN_KEY);if(v)return String(v);CacheService.getScriptCache().put(MP_AP_ROW_GEN_KEY,'1',21600);return'1';}catch(e){return'0';}}
function __mp_apRowGenBump_(){try{var cur=parseInt(CacheService.getScriptCache().get(MP_AP_ROW_GEN_KEY)||'1',10),nxt=String(isFinite(cur)?cur+1:1);CacheService.getScriptCache().put(MP_AP_ROW_GEN_KEY,nxt,21600);return nxt;}catch(e){return null;}}
function __mp_apRowCacheKey_(id){return MP_AP_ROW_NS+'::G'+__mp_apRowGen_()+'::'+String(id||'').trim();}
function __mp_apRowCacheGet_(id){try{var raw=CacheService.getScriptCache().get(__mp_apRowCacheKey_(id));if(!raw)return null;var p=JSON.parse(raw);return p&&p.row&&p.hdr?p:null;}catch(e){return null;}}
function __mp_apRowCachePut_(id,hdr,row,rowNumber,lastCol){try{var json=JSON.stringify({hdr:hdr,row:row,rowNumber:rowNumber,lastCol:lastCol});if(json.length<=95000){CacheService.getScriptCache().put(__mp_apRowCacheKey_(id),json,MP_AP_ROW_TTL_SEC);return true;}}catch(e){}return false;}
function __mp_apExecRowKey_(id){return MP_AP_ROW_EXEC_PREFIX+String(id||'').trim();}
function __mp_apExecRowGet_(id){try{if(typeof __MP_EXEC_CACHE!=='object'||!__MP_EXEC_CACHE)return null;var p=__MP_EXEC_CACHE[__mp_apExecRowKey_(id)];return p&&p.row&&p.hdr&&p.rowNumber?p:null;}catch(e){return null;}}
function __mp_apExecRowPut_(id,hdr,row,rowNumber,lastCol){try{if(typeof __MP_EXEC_CACHE!=='object'||!__MP_EXEC_CACHE)return false;__MP_EXEC_CACHE[__mp_apExecRowKey_(id)]={hdr:(hdr||[]).slice(),row:(row||[]).slice(),rowNumber:Number(rowNumber||0),lastCol:Number(lastCol||(hdr||[]).length||0)};return true;}catch(e){return false;}}
function __mp_apExecRowsClear_(){try{if(typeof __MP_EXEC_CACHE!=='object'||!__MP_EXEC_CACHE)return;Object.keys(__MP_EXEC_CACHE).forEach(function(k){if(String(k).indexOf(MP_AP_ROW_EXEC_PREFIX)===0)delete __MP_EXEC_CACHE[k];});}catch(e){}}
function __mp_findAuditIdCol_(hdr){for(var i=0;i<(hdr||[]).length;i++){var h=String(hdr[i]||'').trim().toLowerCase();if(h==='audit id'||h==='audit_id'||h==='auditid')return i;}return-1;}
function __mp_readAuditPlanningIndexPersist_(){try{if(typeof __mp_auditCacheGet_==='function'){var v=__mp_auditCacheGet_(MP_AP_INDEX_NS,MP_AP_INDEX_KEY);if(v&&v.hdr&&v.index)return v;}}catch(e0){}try{var raw=CacheService.getScriptCache().get(__mp_apIndexNativeKey_());if(raw){var p=JSON.parse(raw);if(p&&p.hdr&&p.index)return p;}}catch(e1){}return null;}
function __mp_writeAuditPlanningIndexPersist_(payload,ttlSec){var ttl=ttlSec||MP_AP_INDEX_TTL_SEC,okA=false,okN=false;try{if(typeof __mp_auditCachePut_==='function')okA=!!__mp_auditCachePut_(MP_AP_INDEX_NS,MP_AP_INDEX_KEY,payload,ttl);}catch(e0){}try{var json=JSON.stringify(payload||{});if(json.length<90000){CacheService.getScriptCache().put(__mp_apIndexNativeKey_(),json,ttl);okN=true;}}catch(e1){}return okA||okN;}
function __mp_apInstallPack_(p){if(typeof __MP_EXEC_CACHE==='object'&&__MP_EXEC_CACHE)__MP_EXEC_CACHE[MP_AP_INDEX_EXEC_KEY]={hdr:p.hdr||[],index:p.index||{},count:p.count||0,lastRow:p.lastRow||0,lastCol:p.lastCol||0,_indexPhysicalSheetReads:Number(p._indexPhysicalSheetReads||0),_coldIndexBuild:p._coldIndexBuild===true,_indexBuildMode:p._indexBuildMode||'CACHE'};}
function __mp_apBuildIndex_(sh,persist){var t0=Date.now(),lastRow=sh.getLastRow(),lastCol=sh.getLastColumn();if(lastRow<1||lastCol<1)return null;var hdr=sh.getRange(1,1,1,lastCol).getValues()[0]||[],col=__mp_findAuditIdCol_(hdr);if(col<0)return null;var reads=1,ids=[];if(lastRow>1){ids=sh.getRange(2,col+1,lastRow-1,1).getValues();reads++;}var index={},count=0;for(var r=0;r<ids.length;r++){var id=String(ids[r][0]||'').trim();if(id){index[id]=r+2;count++;}}var base={hdr:hdr,index:index,count:count,lastRow:lastRow,lastCol:lastCol};if(persist!==false)__mp_writeAuditPlanningIndexPersist_(base,MP_AP_INDEX_TTL_SEC);var p={hdr:hdr,index:index,count:count,lastRow:lastRow,lastCol:lastCol,_indexPhysicalSheetReads:reads,_coldIndexBuild:true,_indexBuildMode:'NARROW_HEADER_PLUS_AUDIT_ID_COLUMN'};if(persist!==false)__mp_apInstallPack_(p);Logger.log('[AP_INDEX_DIAG] tier=COLD_INDEX_NARROW count='+count+' reads='+reads+' persist='+(persist!==false)+' ms='+(Date.now()-t0));return p;}
function __mp_apGetPack_(sh){if(typeof __MP_EXEC_CACHE==='object'&&__MP_EXEC_CACHE&&__MP_EXEC_CACHE[MP_AP_INDEX_EXEC_KEY]){var e=__MP_EXEC_CACHE[MP_AP_INDEX_EXEC_KEY];e._indexPhysicalSheetReads=0;e._coldIndexBuild=false;e._indexBuildMode='EXEC_CACHE';return e;}var p=__mp_readAuditPlanningIndexPersist_();if(p&&p.index&&p.lastCol>0){p._indexPhysicalSheetReads=0;p._coldIndexBuild=false;p._indexBuildMode='SCRIPT_CACHE';__mp_apInstallPack_(p);return p;}return __mp_apBuildIndex_(sh,true);}
function __mp_apMeta_(pack,rowReads,cacheHits,rangeRows,requested,missing){var ir=Number(pack&&pack._indexPhysicalSheetReads||0),rr=Number(rowReads||0);return{physicalSheetReads:rr,rowPayloadPhysicalSheetReads:rr,indexPhysicalSheetReads:ir,physicalSheetReadsTotal:ir+rr,coldIndexBuild:!!(pack&&pack._coldIndexBuild),indexBuildMode:pack&&pack._indexBuildMode||'NOT_NEEDED',cacheHits:Number(cacheHits||0),rangeRows:Number(rangeRows||0),requested:Number(requested||0),missing:Number(missing||0)};}
function __mp_getAuditPlanningRows_(ss,auditIds,options){options=options||{};var bypass=options.bypassCache===true,forceIndex=options.forceRebuildIndex===true,t0=Date.now(),ids=[],seen={};(auditIds||[]).forEach(function(v){var id=String(v||'').trim();if(id&&!seen[id]){seen[id]=1;ids.push(id);}});if(!ids.length)return{items:{},hdr:[],meta:__mp_apMeta_(null,0,0,0,0,0)};var sh=ss.getSheetByName('Audit planning');if(!sh)return null;var items={},missing=[],cacheHits=0;ids.forEach(function(id){var p=bypass?null:(__mp_apExecRowGet_(id)||__mp_apRowCacheGet_(id));if(p&&p.row){items[id]={sh:sh,hdr:p.hdr||[],row:(p.row||[]).slice(),rowNumber:p.rowNumber||0,indexFromCache:true};__mp_apExecRowPut_(id,p.hdr||[],p.row,p.rowNumber,p.lastCol);cacheHits++;}else missing.push(id);});if(!missing.length){Logger.log('[AP_INDEX_DIAG] tier=BULK_CACHE hits='+cacheHits+' ms='+(Date.now()-t0));return{items:items,hdr:items[ids[0]].hdr,meta:__mp_apMeta_(null,0,cacheHits,0,ids.length,0)};}var pack=forceIndex?__mp_apBuildIndex_(sh,false):__mp_apGetPack_(sh);if(!pack)return null;var rows=[];for(var i=0;i<missing.length;i++){var rn=pack.index[missing[i]];if(!rn)return null;rows.push(rn);}var min=Math.min.apply(null,rows),max=Math.max.apply(null,rows),span=max-min+1,data=sh.getRange(min,1,span,pack.lastCol).getValues(),idCol=__mp_findAuditIdCol_(pack.hdr);for(var r=0;r<data.length;r++){var key=String(data[r][idCol]||'').trim();if(seen[key]){var rowNum=min+r;items[key]={sh:sh,hdr:pack.hdr,row:data[r],rowNumber:rowNum,indexFromCache:false};if(!bypass){__mp_apExecRowPut_(key,pack.hdr,data[r],rowNum,pack.lastCol);__mp_apRowCachePut_(key,pack.hdr,data[r],rowNum,pack.lastCol);}}}for(var j=0;j<ids.length;j++)if(!items[ids[j]])return null;Logger.log('[AP_INDEX_DIAG] tier=BULK_RANGE ids='+ids.length+' missing='+missing.length+' span='+span+' totalReads='+(Number(pack._indexPhysicalSheetReads||0)+1)+' diagnosticBypass='+bypass+' ms='+(Date.now()-t0));return{items:items,hdr:pack.hdr,meta:__mp_apMeta_(pack,1,cacheHits,span,ids.length,missing.length)};}
function __mp_getAuditPlanningRow_(ss,auditId){var key=String(auditId||'').trim();if(!key)return null;var b=__mp_getAuditPlanningRows_(ss,[key]);return b&&b.items?b.items[key]||null:null;}
function __mp_getAuditPlanningRowsColdDiagnostic_(ss,auditIds){return __mp_getAuditPlanningRows_(ss,auditIds,{bypassCache:true,forceRebuildIndex:true});}
function __mp_invalidateAuditPlanningPack_(){try{__mp_apRowGenBump_();}catch(e0){}try{if(typeof _mp_pwGenBump_==='function')_mp_pwGenBump_();}catch(e1){}try{CacheService.getScriptCache().remove(__mp_apIndexNativeKey_());}catch(e2){}try{if(typeof AUDIT_CACHE!=='undefined'&&AUDIT_CACHE&&typeof AUDIT_CACHE.remove==='function'){try{AUDIT_CACHE.remove(MP_AP_INDEX_NS,MP_AP_INDEX_KEY);}catch(e3){AUDIT_CACHE.remove(MP_AP_INDEX_NS+'::'+MP_AP_INDEX_KEY);}}}catch(e4){}try{if(typeof __MP_EXEC_CACHE==='object'&&__MP_EXEC_CACHE){delete __MP_EXEC_CACHE[MP_AP_INDEX_EXEC_KEY];__mp_apExecRowsClear_();}}catch(e5){}Logger.log('['+MP_AP_INDEX_BUILD+'] structurally invalidated');}
function __mp_warmAuditPlanningRowIndex_(ss){var t0=Date.now();try{if(!ss)ss=SpreadsheetApp.getActive();var sh=ss.getSheetByName('Audit planning');if(!sh)return{ok:false,error:'sheet not found',ms:Date.now()-t0};var p=__mp_apBuildIndex_(sh,true);return{ok:!!p,count:p&&p.count||0,rowsWarmed:0,indexPhysicalSheetReads:p&&p._indexPhysicalSheetReads||0,ms:Date.now()-t0,mode:'NARROW_INDEX_ONLY'};}catch(e){return{ok:false,error:String(e&&e.message||e),ms:Date.now()-t0};}}
