var MODEL_C_SCOPE_OWNER_TEST_BUILD='2026-09-20_AMS_01_6_MODEL_C_PHASE_2B_SCOPE_OWNER_TESTS_R3';
function RUN_MODEL_C_PHASE2B_SCOPE_OWNER_REGRESSION(){var tests=[ModelCScopeOwnerTest_retain_,ModelCScopeOwnerTest_create_,ModelCScopeOwnerTest_deactivate_,ModelCScopeOwnerTest_abc_,ModelCScopeOwnerTest_grasp_,ModelCScopeOwnerTest_graspRequiresGap_,ModelCScopeOwnerTest_expiryRequired_,ModelCScopeOwnerTest_currentAuditObligation_,ModelCScopeOwnerTest_decimalCommaHours_],results=[],passed=0;for(var i=0;i<tests.length;i++){try{tests[i]();results.push({name:tests[i].name,ok:true});passed++;}catch(e){results.push({name:tests[i].name,ok:false,error:String(e.message||e)});}}var out={ok:passed===tests.length,build:MODEL_C_SCOPE_OWNER_TEST_BUILD,ownerBuild:MODEL_C_SCOPE_OWNER_BUILD,passed:passed,total:tests.length,writesPerformed:false,results:results};Logger.log(JSON.stringify(out,null,2));if(!out.ok)throw new Error('Scope owner regression failed');return out;}
function ModelCScopeOwnerTest_fixture_(selected){return ModelCScopeOwner_planTransition_({companyUid:'C1',auditId:'A1',selectedScopes:selected},[{Company_Scope_ID:'CS1',Company_UID:'C1',ScopeCode:'MPS-GAP',Active:'YES'}],[{Obligation_ID:'O1',Company_Scope_ID:'CS1',Company_UID:'C1',Obligation_State:'OPEN',Source_Audit_ID:'A1'}],[{Audit_ID:'A1',Obligation_ID:'O1',Link_State:'ACTIVE'}]);}
function ModelCScopeOwnerTest_retain_(){var p=ModelCScopeOwnerTest_fixture_([{scope:'MPS-GAP',enabled:true,customHours:8,baseExpiry:'2027-01-01'}]);ModelCScopeOwnerTest_assert_(p.counts.retain===1&&p.counts.deactivate===0,'retain');}
function ModelCScopeOwnerTest_create_(){var p=ModelCScopeOwnerTest_fixture_([{scope:'MPS-GAP',enabled:true},{scope:'MPS-SQ',enabled:true,baseExpiry:'2027-01-01'}]);ModelCScopeOwnerTest_assert_(p.counts.create===1,'create');}
function ModelCScopeOwnerTest_deactivate_(){var p=ModelCScopeOwnerTest_fixture_([]);ModelCScopeOwnerTest_assert_(p.counts.deactivate===1&&p.deactivate[0].activeLink,'deactivate');}
function ModelCScopeOwnerTest_abc_(){var n=ModelCScopeOwner_normalizeSelected_([{scope:'MPS-ABC',enabled:true,baseExpiry:'2026-12-31'}]);ModelCScopeOwnerTest_assert_(n['MPS-ABC'].baseExpiry===''&&n['MPS-ABC'].lifecycleType==='EXTERNAL_ANNUAL','ABC expiry');}
function ModelCScopeOwnerTest_grasp_(){var n=ModelCScopeOwner_normalizeSelected_([{scope:'MPS-GAP',enabled:true,baseExpiry:'2027-06-01'},{scope:'GRASP',enabled:true,baseExpiry:'2099-01-01'}]);ModelCScopeOwnerTest_assert_(n.GRASP.baseExpiry==='2027-06-01','GRASP inheritance');}
function ModelCScopeOwnerTest_graspRequiresGap_(){var failed=false;try{ModelCScopeOwner_validateSelection_(ModelCScopeOwner_normalizeSelected_([{scope:'GRASP',enabled:true,baseExpiry:'2027-06-01'}]));}catch(e){failed=true;}ModelCScopeOwnerTest_assert_(failed,'GRASP without GAP accepted');}
function ModelCScopeOwnerTest_expiryRequired_(){var failed=false;try{ModelCScopeOwner_validateSelection_(ModelCScopeOwner_normalizeSelected_([{scope:'MPS-GAP',enabled:true}]));}catch(e){failed=true;}ModelCScopeOwnerTest_assert_(failed,'certificate expiry missing');}
function ModelCScopeOwnerTest_currentAuditObligation_(){var obligations=[{Obligation_ID:'O1',Company_Scope_ID:'CS1',Company_UID:'C1',Obligation_State:'OPEN',Source_Audit_ID:'A1'},{Obligation_ID:'O2',Company_Scope_ID:'CS1',Company_UID:'C1',Obligation_State:'OPEN',Source_Audit_ID:'A2'}];var links=[{Audit_ID:'A1',Obligation_ID:'O1',Link_State:'ACTIVE'},{Audit_ID:'A2',Obligation_ID:'O2',Link_State:'ACTIVE'}];var p=ModelCScopeOwner_planTransition_({companyUid:'C1',auditId:'A1',selectedScopes:[{scope:'MPS-GAP',enabled:true,customHours:8,baseExpiry:'2027-01-01'}]},[{Company_Scope_ID:'CS1',Company_UID:'C1',ScopeCode:'MPS-GAP',Active:'YES'}],obligations,links);ModelCScopeOwnerTest_assert_(p.success&&p.retain.length===1&&p.retain[0].obligation&&p.retain[0].obligation.Obligation_ID==='O1','wrong audit obligation selected');}
function ModelCScopeOwnerTest_decimalCommaHours_(){ModelCScopeOwnerTest_assert_(ModelCScopeOwner_hours_('8,5')===8.5,'decimal comma hours');}
function ModelCScopeOwnerTest_assert_(v,m){if(!v)throw new Error(m);}
