/***********************************************************************
 * AvailabilityPeriodReadModel.js
 * BUILD: 2026-09-10_AMS01_2_AVAILABILITY_PERIOD_READ_MODEL_R3_SEGMENTED_PERIOD_READ
 *
 * Read-only compact period projection of canonical Auditor Availability.
 * Canonical owner remains AvailabilityService / Auditor Availability.
 * No writes, no new truth, no persistent cache.
 ***********************************************************************/
var AVAILABILITY_PERIOD_READ_MODEL_BUILD='2026-09-10_AMS01_2_AVAILABILITY_PERIOD_READ_MODEL_R3_SEGMENTED_PERIOD_READ';
function APRM_clean_(v){return String(v==null?'':v).replace(/\u00A0/g,' ').trim();}
function APRM_norm_(v){return APRM_clean_(v).toLowerCase();}
function APRM_headerKey_(v){return APRM_norm_(v).replace(/\s+/g,'_');}
function APRM_findCol_(headers,candidates){var map={};for(var i=0;i<(headers||[]).length;i++){var key=APRM_headerKey_(headers[i]);if(key&&map[key]===undefined)map[key]=i;}for(var j=0;j<(candidates||[]).length;j++){var k=APRM_headerKey_(candidates[j]);if(map[k]!==undefined)return map[k];}return-1;}
function APRM_isoDate_(v,tz){if(!v)return'';if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v.getTime()))return Utilities.formatDate(v,tz||Session.getScriptTimeZone(),'yyyy-MM-dd');var s=APRM_clean_(v);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:'';}
function APRM_time_(v,tz){if(v==null||v==='')return'';if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v.getTime()))return Utilities.formatDate(v,tz||Session.getScriptTimeZone(),'HH:mm');var s=APRM_clean_(v),m=s.match(/^(\d{1,2}):(\d{2})$/);return m?('0'+Number(m[1])).slice(-2)+':'+m[2]:s;}
function APRM_period_(input,tz){input=input||{};var from=APRM_isoDate_(input.from||input.start||input.periodFrom,tz),to=APRM_isoDate_(input.to||input.end||input.periodTo,tz);if(!from||!to)throw new Error('AvailabilityPeriodReadModel: valid from/to required');if(to<from)throw new Error('AvailabilityPeriodReadModel: to cannot be before from');return{from:from,to:to};}
function APRM_auditorSet_(input){var raw=input&&(input.auditors||input.auditorEmails||input.auditorEmail||input.auditor);if(!raw)return null;var arr=Array.isArray(raw)?raw:[raw],set={};for(var i=0;i<arr.length;i++){var k=APRM_norm_(arr[i]);if(k)set[k]=true;}return Object.keys(set).length?set:null;}
function APRM_sheet_(){var ss=SpreadsheetApp.getActive();return ss.getSheetByName('Auditor Availability')||ss.getSheetByName('Auditor availability');}
function APRM_slot_(row,startCol,endCol,auditIdCol,statusCol,tz,slot){if(startCol<0&&endCol<0&&auditIdCol<0&&statusCol<0)return null;var start=startCol>=0?APRM_time_(row[startCol],tz):'',end=endCol>=0?APRM_time_(row[endCol],tz):'',auditId=auditIdCol>=0?APRM_clean_(row[auditIdCol]):'',status=statusCol>=0?APRM_clean_(row[statusCol]):'';if(!start&&!end&&!auditId&&!status)return null;return{slot:slot,start:start,end:end,auditId:auditId,status:status};}
function APRM_periodSegments_(dateValues,period,tz){var segments=[],current=null,matchedRows=0,validDates=0;for(var i=0;i<(dateValues||[]).length;i++){var d=APRM_isoDate_(dateValues[i]&&dateValues[i][0],tz);if(d)validDates++;var matched=!!d&&d>=period.from&&d<=period.to;if(matched){matchedRows++;if(!current)current={startOffset:i,rowCount:1};else current.rowCount++;}else if(current){segments.push(current);current=null;}}if(current)segments.push(current);return{segments:segments,matchedRows:matchedRows,validDates:validDates};}
function APRM_readStrategy_(sourceRows,pack){var segments=(pack&&pack.segments)||[],matched=pack?pack.matchedRows||0:0,density=sourceRows?matched/sourceRows:0,use=matched===0||(segments.length>0&&segments.length<=8&&density<=0.70);return{mode:use?'SEGMENTED':'FULL',segments:use?segments:[{startOffset:0,rowCount:sourceRows}],matchedRows:matched,density:density,detectedSegments:segments.length};}
function AvailabilityPeriodReadModel_get(input){
 input=input||{};var perf=typeof DPL_start_==='function'?DPL_start_('AvailabilityPeriodReadModel_get',{from:input.from||input.start||input.periodFrom||'',to:input.to||input.end||input.periodTo||'',auditorCount:Array.isArray(input.auditors||input.auditorEmails)?(input.auditors||input.auditorEmails).length:((input.auditorEmail||input.auditor)?1:0)}):null;
 var ss=SpreadsheetApp.getActive(),tz=ss.getSpreadsheetTimeZone()||Session.getScriptTimeZone(),period=APRM_period_(input,tz),auditorSet=APRM_auditorSet_(input),sh=APRM_sheet_();if(!sh)throw new Error("AvailabilityPeriodReadModel: missing sheet 'Auditor Availability'");
 var lastRow=sh.getLastRow(),lastCol=sh.getLastColumn();if(lastCol<1){var e={success:true,build:AVAILABILITY_PERIOD_READ_MODEL_BUILD,period:period,days:{},rows:[],meta:{sourceRows:0,returnedRows:0,writes:false}};if(typeof DPL_end_==='function')e.devPerformance=DPL_end_(perf,{returnedRows:0});return e;}
 var headers=sh.getRange(1,1,1,lastCol).getValues()[0]||[],cDate=APRM_findCol_(headers,['Date']),cAud=APRM_findCol_(headers,['Auditor_Email','Auditor Email','Email','E-mail','Auditor_Name','Auditor Name']),cAvail=APRM_findCol_(headers,['Available']),cS1=APRM_findCol_(headers,['First_Audit_Start_Time','First Audit Start Time']),cE1=APRM_findCol_(headers,['First_Audit_End_Time','First Audit End Time']),cID1=APRM_findCol_(headers,['Audit_ID_1','Audit ID 1','AuditId1']),cSt1=APRM_findCol_(headers,['Status_1','Status 1','Status','Source']),cS2=APRM_findCol_(headers,['Second_Audit_Start_Time','Second Audit Start Time']),cE2=APRM_findCol_(headers,['Second_Audit_End_Time','Second Audit End Time']),cID2=APRM_findCol_(headers,['Audit_ID_2','Audit ID 2','AuditId2']),cSt2=APRM_findCol_(headers,['Status_2','Status 2']),cUpd=APRM_findCol_(headers,['Last_Updated','Last Updated','Timestamp']);if(cDate<0||cAud<0||cAvail<0)throw new Error('AvailabilityPeriodReadModel: required columns missing');
 var required=[cDate,cAud,cAvail,cS1,cE1,cID1,cSt1,cS2,cE2,cID2,cSt2,cUpd].filter(function(x){return x>=0;}),maxCol=required.length?Math.max.apply(null,required)+1:lastCol,sourceRows=Math.max(0,lastRow-1),dateValues=sourceRows?sh.getRange(2,cDate+1,sourceRows,1).getValues():[],pack=APRM_periodSegments_(dateValues,period,tz),strategy=APRM_readStrategy_(sourceRows,pack);
 if(typeof DPL_mark_==='function')DPL_mark_(perf,'dateIndexRead',{rows:dateValues.length,matchedRows:pack.matchedRows,segmentCount:pack.segments.length,strategy:strategy.mode,density:Math.round(strategy.density*1000)/1000});
 var rawRows=[],scannedRows=0;for(var s=0;s<strategy.segments.length;s++){var seg=strategy.segments[s];if(!seg||seg.rowCount<=0)continue;var startRow=seg.startOffset+2,values=sh.getRange(startRow,1,seg.rowCount,maxCol).getValues();scannedRows+=values.length;for(var v=0;v<values.length;v++)rawRows.push({sourceRow:startRow+v,row:values[v]||[]});}
 if(typeof DPL_mark_==='function')DPL_mark_(perf,'bodyRead',{strategy:strategy.mode,segmentsRead:strategy.segments.length,rows:scannedRows,cols:maxCol,sourceRows:sourceRows});
 var rows=[],days={};for(var r=0;r<rawRows.length;r++){var raw=rawRows[r],row=raw.row||[],date=APRM_isoDate_(row[cDate],tz);if(!date||date<period.from||date>period.to)continue;var auditorEmail=APRM_norm_(row[cAud]);if(!auditorEmail||(auditorSet&&!auditorSet[auditorEmail]))continue;var rec={date:date,auditorEmail:auditorEmail,available:APRM_clean_(row[cAvail]),slots:[],lastUpdated:cUpd>=0?APRM_clean_(row[cUpd]):'',sourceRow:raw.sourceRow},s1=APRM_slot_(row,cS1,cE1,cID1,cSt1,tz,1),s2=APRM_slot_(row,cS2,cE2,cID2,cSt2,tz,2);if(s1)rec.slots.push(s1);if(s2)rec.slots.push(s2);rows.push(rec);if(!days[auditorEmail])days[auditorEmail]={};if(!days[auditorEmail][date])days[auditorEmail][date]=[];days[auditorEmail][date].push(rec);}
 if(typeof DPL_mark_==='function')DPL_mark_(perf,'filterProject',{returnedRows:rows.length,auditors:Object.keys(days).length});rows.sort(function(a,b){if(a.auditorEmail!==b.auditorEmail)return a.auditorEmail.localeCompare(b.auditorEmail);if(a.date!==b.date)return a.date.localeCompare(b.date);return a.sourceRow-b.sourceRow;});
 var result={success:true,build:AVAILABILITY_PERIOD_READ_MODEL_BUILD,period:period,rows:rows,days:days,meta:{sourceRows:sourceRows,scannedRows:scannedRows,returnedRows:rows.length,auditors:Object.keys(days).length,columnsRead:maxCol,dateIndexRows:dateValues.length,periodMatchedRows:pack.matchedRows,detectedSegments:pack.segments.length,segmentsRead:strategy.segments.length,readStrategy:strategy.mode,readDensity:strategy.density,canonicalOwner:'AvailabilityService / Auditor Availability',writes:false}};if(typeof DPL_end_==='function')result.devPerformance=DPL_end_(perf,{sourceRows:sourceRows,scannedRows:scannedRows,returnedRows:rows.length,auditors:Object.keys(days).length,readStrategy:strategy.mode,segmentsRead:strategy.segments.length});return result;
}
