/** FILE: BatchPlanningTransactionSnapshot.gs
 * BUILD: 2026-09-18_BATCH_PLANNING_TRANSACTION_SNAPSHOT_R1
 * Read-only snapshot/restore primitives for future atomic Batch commit.
 * Restore is intentionally private and not wired to public confirmation.
 */
var BATCH_PLANNING_TX_SNAPSHOT_BUILD='2026-09-18_BATCH_PLANNING_TRANSACTION_SNAPSHOT_R1';
function BatchPlanningTx_snapshot_(requests){requests=requests||[];var ss=SpreadsheetApp.getActive(),ap=ss.getSheetByName('Audit planning'),av=ss.getSheetByName('Auditor Availability')||ss.getSheetByName('Auditor availability');if(!ap||!av)throw new Error('Canonical planning sheets missing');var ids={},dates={},auditors={};requests.forEach(function(q){ids[String(q.auditId||'').trim()]=true;auditors[String(q.auditorEmail||q.auditorName||'').trim().toLowerCase()]=true;(q.blocks||[]).forEach(function(b){dates[String(b.date||'').trim()]=true;});});var apVals=ap.getDataRange().getValues(),apHdr=apVals[0]||[],ai=apHdr.indexOf('Audit ID'),apRows=[];if(ai<0)throw new Error("Missing 'Audit ID' column");for(var r=1;r<apVals.length;r++){var id=String(apVals[r][ai]||'').trim();if(ids[id])apRows.push({rowNumber:r+1,values:apVals[r].slice()});}var avVals=av.getDataRange().getValues(),avHdr=avVals[0]||[],dateI=BatchPlanningTx_findHeader_(avHdr,['Date']),audI=BatchPlanningTx_findHeader_(avHdr,['Auditor_Email','Auditor Email','Email','E-mail','Auditor_Name','Auditor Name']),avRows=[];for(var x=1;x<avVals.length;x++){var d=BatchPlanningTx_iso_(avVals[x][dateI],ss),a=String(avVals[x][audI]||'').trim().toLowerCase();if(dates[d]&&auditors[a])avRows.push({rowNumber:x+1,values:avVals[x].slice()});}return{build:BATCH_PLANNING_TX_SNAPSHOT_BUILD,auditPlanning:{sheetName:ap.getName(),lastRow:ap.getLastRow(),lastColumn:ap.getLastColumn(),rows:apRows},availability:{sheetName:av.getName(),lastRow:av.getLastRow(),lastColumn:av.getLastColumn(),headers:avHdr.slice(),rows:avRows},auditIds:Object.keys(ids),dates:Object.keys(dates),auditors:Object.keys(auditors),writesPerformed:false};}
function BatchPlanningTx_findHeader_(h,n){var z=h.map(function(v){return String(v||'').trim().toLowerCase().replace(/[_\s]+/g,' ');});for(var i=0;i<n.length;i++){var k=String(n[i]).trim().toLowerCase().replace(/[_\s]+/g,' '),p=z.indexOf(k);if(p>=0)return p;}throw new Error('Required Availability header missing: '+n.join('/'));}
function BatchPlanningTx_iso_(v,ss){if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v.getTime()))return Utilities.formatDate(v,ss.getSpreadsheetTimeZone(),'yyyy-MM-dd');return String(v||'').trim();}
function BatchPlanningTx_restore_DISABLED_(snapshot){throw new Error('BATCH_TX_RESTORE_NOT_ENABLED');}
