/** FILE: BatchPlanningManagerApi.gs
 * BUILD: 2026-09-18_BATCH_PLANNING_MANAGER_API_R1_READ_ONLY
 * Manager-facing read-only Batch Planning boundary. No planning/status/availability writes.
 */
var BATCH_PLANNING_MANAGER_API_BUILD='2026-09-19_BATCH_PLANNING_MANAGER_API_R8_CONCEPT_RESERVATION_PAYLOAD';
function getBatchPlanningAuditorOptionsV5(){var ss=SpreadsheetApp.getActiveSpreadsheet(),dir=m5t_getAuditorDirectory_(ss),out=(dir&&Array.isArray(dir.list)?dir.list:[]).map(function(a){return{email:String(a.email||'').trim().toLowerCase(),name:String(a.name||a.email||'').trim()};}).filter(function(a){return !!a.email;});out.sort(function(a,b){return String(a.name||a.email).localeCompare(String(b.name||b.email));});return{ok:true,auditors:out,writesPerformed:false};}
function getBatchPlanningConceptV5(input){input=input||{};var auditor=String(input.auditorEmail||'').trim().toLowerCase(),from=String(input.periodFrom||'').trim(),to=String(input.periodTo||'').trim();if(!auditor)return{ok:false,error:'AUDITOR_REQUIRED',writesPerformed:false};if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)return{ok:false,error:'PERIOD_INVALID',writesPerformed:false};var request={auditorEmail:auditor,periodFrom:from,periodTo:to,noApiCall:input.noApiCall===true,forceFreshRoutes:input.forceFreshRoutes===true};if(Array.isArray(input.auditIds)&&input.auditIds.length)request.auditIds=input.auditIds.map(function(id){return String(id||'').trim();}).filter(Boolean);if(input.inboundPoint!=null)request.inboundPoint=input.inboundPoint;if(input.outboundPoint!=null)request.outboundPoint=input.outboundPoint;var result=BatchPlanningIntegratedConcept_Generate(request);if(!result||!result.ok)return result||{ok:false,error:'BATCH_PLANNING_CONCEPT_FAILED',writesPerformed:false};return{ok:true,build:BATCH_PLANNING_MANAGER_API_BUILD,advisoryOnly:true,auditor:result.auditor,period:result.period,boundaries:result.boundaries,candidateCount:Number(result.candidateCount||0),routedCandidateCount:Number(result.routedCandidateCount||0),days:Array.isArray(result.days)?result.days:[],routeLegs:Array.isArray(result.routeLegs)?result.routeLegs:[],outboundLeg:result.outboundLeg||null,rejected:Array.isArray(result.rejected)?result.rejected:[],unresolved:Array.isArray(result.unresolved)?result.unresolved:[],pendingPlannerAllocation:Array.isArray(result.pendingPlannerAllocation)?result.pendingPlannerAllocation:[],pendingPlannerAllocationCount:Number(result.pendingPlannerAllocationCount||0),stopIssues:Array.isArray(result.stopIssues)?result.stopIssues:[],fixedAnchorsImmutable:result.fixedAnchorsImmutable===true,dynamicRouteBoundaries:result.dynamicRouteBoundaries===true,hoursToBePlannedLeading:result.hoursToBePlannedLeading===true,travelTimeLeading:result.travelTimeLeading===true,distanceInformational:result.distanceInformational===true,routeBatching:result.routeBatching===true,routeOrderPreservedByScheduler:result.routeOrderPreservedByScheduler===true,routeStateStale:false,plannerDragDropLeading:true,explicitConfirmationRequired:true,conceptReservations:BatchPlanningManagerApi_reservations_(result),writesPerformed:false};}
function BatchPlanningManagerApi_reservations_(result){var out=[],auditor=result&&result.auditor||{},email=String(auditor.email||auditor.auditorEmail||'').trim().toLowerCase(),name=String(auditor.name||auditor.auditorName||email).trim();(result&&result.days||[]).forEach(function(day){(day.conceptAudits||[]).forEach(function(a){var hours=Number(a.hours||0)||0;out.push({auditId:String(a.auditId||'').trim(),company:String(a.company||'').trim(),auditorEmail:email,auditorName:name,blocks:[{date:String(day.date||'').slice(0,10),start:String(a.startTime||''),end:String(a.endTime||''),hours:hours}],planningWindowFrom:String(a.planningWindowFrom||''),planningWindowTo:String(a.planningWindowTo||''),softWarnings:Array.isArray(a.softWarnings)?a.softWarnings:[],routeIndex:Number(a.routeIndex||0),routeFromPrevious:a.routeFromPrevious||null,readOnlyGenerated:true});});});return out;}

function revalidateBatchPlanningEditedConceptV5(input){return revalidateBatchPlanningEditedRouteV5(input||{});}
