/** FILE: BatchPlanningEndToEndLiveTests.gs
 * BUILD: 2026-09-17_BATCH_PLANNING_END_TO_END_LIVE_R1
 * RUN: RUN_BATCH_PLANNING_END_TO_END_LIVE
 * Live read-only validation: candidates -> boundaries -> company stops -> Google Routes -> concept -> day scheduler.
 */
function RUN_BATCH_PLANNING_END_TO_END_LIVE(){
 var results=[];function t(n,ok,detail){results.push({name:n,ok:!!ok,detail:ok?'':String(detail||'')});}
 var directory=AuditorsIndex_GetDirectory(false),list=directory&&directory.list?directory.list:[],auditor=list.length?String(list[0].email||'').trim().toLowerCase():'',from=new Date(),to=new Date(from.getTime());to.setDate(to.getDate()+45);var input={auditorEmail:auditor,periodFrom:BatchPlanningCandidateEngine_iso_(from),periodTo:BatchPlanningCandidateEngine_iso_(to),noApiCall:false,forceFreshRoutes:false};
 t('auditorAvailable',!!auditor,'No auditor');
 var candidates=auditor?BatchPlanningCandidateEngine_Collect(input):null;t('candidateRead',!!(candidates&&candidates.ok),candidates&&candidates.error);t('candidateShape',!!(candidates&&Array.isArray(candidates.candidates)), 'Candidates unavailable');
 var boundaries=auditor?BatchPlanningAnchorRouteModel_Resolve(input):null;t('boundaryRead',!!(boundaries&&boundaries.ok),boundaries&&boundaries.error);t('boundaryReadOnly',!!(boundaries&&boundaries.writesPerformed===false),'Boundary write contract');t('unboundedBoundaryContract',!!(boundaries&&boundaries.nearestAnchorHorizonDays===null),'Nearest boundary horizon not unbounded');
 var integrated=auditor?BatchPlanningIntegratedConcept_Generate(input):null;t('integratedRead',!!(integrated&&integrated.ok),integrated&&integrated.error);t('integratedReadOnly',!!(integrated&&integrated.writesPerformed===false),'Integrated writes');t('safeInjection',!!(integrated&&integrated.safeCandidateInjection===true),'Safe injection missing');t('fixedAnchorsImmutable',!!(integrated&&integrated.fixedAnchorsImmutable===true),'Fixed anchors mutable');t('plannerAttentionVisible',!!(integrated&&Array.isArray(integrated.pendingPlannerAllocation)),'Planner attention missing');
 var routed=integrated&&Number(integrated.routedCandidateCount||0),legs=integrated&&integrated.routeLegs||[];t('routeProviderLive',routed>0&&legs.length>0,'No routed candidates/legs');t('routeMetricsLive',legs.length>0&&legs.every(function(x){return Number(x.durationSeconds)>0&&Number(x.distanceMeters)>0;}),'Missing route metrics');t('dayScheduleBuilt',!!(integrated&&Array.isArray(integrated.days)&&integrated.days.length),'No day schedule');t('auditHoursLeading',!!(integrated&&integrated.hoursToBePlannedLeading===true),'Audit hours contract');t('travelTimeLeading',!!(integrated&&integrated.travelTimeLeading===true),'Travel time contract');
 var passed=results.filter(function(x){return x.ok;}).length,out={ok:passed===results.length,build:'2026-09-17_BATCH_PLANNING_END_TO_END_LIVE_R1',total:results.length,passed:passed,failed:results.length-passed,results:results,meta:{auditorEmail:auditor,periodFrom:input.periodFrom,periodTo:input.periodTo,candidateCount:candidates&&candidates.candidateCount||0,routedCandidateCount:routed||0,routeLegCount:legs.length,pendingPlannerAllocation:integrated&&integrated.pendingPlannerAllocationCount||0,unresolved:integrated&&integrated.unresolved?integrated.unresolved.length:null,planningWritesPerformed:false,statusWritesPerformed:false,availabilityWritesPerformed:false,externalRoutesEnabled:true}};Logger.log(JSON.stringify(out,null,2));return out;
}
