/** FILE: BatchPlanningTransactionSnapshot.gs
 * BUILD: 2026-09-18_BATCH_PLANNING_TRANSACTION_R3_ROBUST_ROLLBACK
 * Transaction snapshot + exact Availability restoration for future Batch commit.
 */
var BATCH_PLANNING_TX_SNAPSHOT_BUILD='2026-09-18_BATCH_PLANNING_TRANSACTION_R3_ROBUST_ROLLBACK';
function BatchPlanningTx_scope_(requests){var ids={},dates={},auditors={};(requests||[]).forEach(function(q){var id=String(q.auditId||'').trim(),a=String(q.auditorEmail||q.auditorName||'').trim().toLowerCase();if(id)ids[id]=true;if(a)auditors[a]=true;(q.blocks||[]).forEach(function(b){var d=String(b.date||'').trim();if(d)dates[d]=true;});});return{ids:ids,dates:dates,auditors:auditors};}
function BatchPlanningTx_snapshot_(requests){var ss=SpreadsheetApp.getActive(),ap=ss.getSheetByName('Audit planning'),av=ss.getSheetByName('Auditor Availability')||ss.getSheetByName('Auditor availability');if(!ap||!av)throw new Error('Canonical planning sheets missing');var scope=BatchPlanningTx_scope_(requests),apVals=ap.getDataRange().getValues(),apHdr=apVals[0]||[],ai=apHdr.indexOf('Audit ID'),apRows=[];if(ai<0)throw new Error("Missing 'Audit ID' column");for(var r=1;r<apVals.length;r++){var id=String(apVals[r][ai]||'').trim();if(scope.ids[id])apRows.push({auditId:id,rowNumber:r+1,values:apVals[r].slice()});}var avVals=av.getDataRange().getValues(),avHdr=avVals[0]||[],dateI=BatchPlanningTx_findHeader_(avHdr,['Date']),audI=BatchPlanningTx_findHeader_(avHdr,['Auditor_Email','Auditor Email','Email','E-mail','Auditor_Name','Auditor Name']),avRows=[];for(var x=1;x<avVals.length;x++){var d=BatchPlanningTx_iso_(avVals[x][dateI],ss),a=String(avVals[x][audI]||'').trim().toLowerCase();if(scope.dates[d]&&scope.auditors[a])avRows.push({date:d,auditor:a,rowNumber:x+1,values:avVals[x].slice()});}return{build:BATCH_PLANNING_TX_SNAPSHOT_BUILD,auditPlanning:{sheetName:ap.getName(),lastRow:ap.getLastRow(),lastColumn:ap.getLastColumn(),headers:apHdr.slice(),rows:apRows},availability:{sheetName:av.getName(),lastRow:av.getLastRow(),lastColumn:av.getLastColumn(),headers:avHdr.slice(),rows:avRows},auditIds:Object.keys(scope.ids),dates:Object.keys(scope.dates),auditors:Object.keys(scope.auditors),writesPerformed:false};}
function BatchPlanningTx_findHeader_(h,n){var z=h.map(function(v){return String(v||'').trim().toLowerCase().replace(/[_\s]+/g,' ');});for(var i=0;i<n.length;i++){var k=String(n[i]).trim().toLowerCase().replace(/[_\s]+/g,' '),p=z.indexOf(k);if(p>=0)return p;}throw new Error('Required Availability header missing: '+n.join('/'));}
function BatchPlanningTx_iso_(v,ss){if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v.getTime()))return Utilities.formatDate(v,ss.getSpreadsheetTimeZone(),'yyyy-MM-dd');return String(v||'').trim();}
function BatchPlanningTx_restore_(snapshot){snapshot=snapshot||{};var ss=SpreadsheetApp.getActive(),ap=ss.getSheetByName(snapshot.auditPlanning&&snapshot.auditPlanning.sheetName||'Audit planning'),av=ss.getSheetByName(snapshot.availability&&snapshot.availability.sheetName||'Auditor Availability');if(!ap||!av)throw new Error('Canonical planning sheets missing during rollback');var apRows=(snapshot.auditPlanning&&snapshot.auditPlanning.rows)||[],apHdr=ap.getRange(1,1,1,ap.getLastColumn()).getValues()[0],ai=apHdr.indexOf('Audit ID'),apVals=ap.getDataRange().getValues(),rowById={};for(var r=1;r<apVals.length;r++)rowById[String(apVals[r][ai]||'').trim()]=r+1;for(var i=0;i<apRows.length;i++){var ar=apRows[i],rn=rowById[ar.auditId]||ar.rowNumber;ap.getRange(rn,1,1,ar.values.length).setValues([ar.values]);}
var avHdr=av.getRange(1,1,1,av.getLastColumn()).getValues()[0],dateI=BatchPlanningTx_findHeader_(avHdr,['Date']),audI=BatchPlanningTx_findHeader_(avHdr,['Auditor_Email','Auditor Email','Email','E-mail','Auditor_Name','Auditor Name']),scopeDates={},scopeAud={},saved={};(snapshot.dates||[]).forEach(function(d){scopeDates[d]=true;});(snapshot.auditors||[]).forEach(function(a){scopeAud[String(a).toLowerCase()]=true;});((snapshot.availability&&snapshot.availability.rows)||[]).forEach(function(v){saved[v.auditor+'|'+v.date]=v.values.slice();});var vals=av.getDataRange().getValues(),deleteRows=[];for(var x=1;x<vals.length;x++){var d=BatchPlanningTx_iso_(vals[x][dateI],ss),a=String(vals[x][audI]||'').trim().toLowerCase(),key=a+'|'+d;if(!scopeDates[d]||!scopeAud[a])continue;if(saved[key]){av.getRange(x+1,1,1,saved[key].length).setValues([saved[key]]);delete saved[key];}else deleteRows.push(x+1);}deleteRows.sort(function(a,b){return b-a;}).forEach(function(rn){av.deleteRow(rn);});Object.keys(saved).forEach(function(k){av.appendRow(saved[k]);});SpreadsheetApp.flush();try{Planning_invalidate_();}catch(e0){}return{success:true,auditPlanningRowsRestored:apRows.length,availabilityRowsRestored:(snapshot.availability&&snapshot.availability.rows||[]).length,availabilityRowsRemoved:deleteRows.length};}
