/**
 * FILE: BatchPlanningAnchorRouteModel.gs
 * BUILD: 2026-09-18_BATCH_PLANNING_ANCHOR_ROUTE_MODEL_R4_SINGLE_READ
 * Read-only boundary resolver. One Audit planning read resolves and enriches nearest Approved/Accepted boundaries.
 */
var BATCH_PLANNING_ANCHOR_ROUTE_MODEL_BUILD='2026-09-18_BATCH_PLANNING_ANCHOR_ROUTE_MODEL_R4_SINGLE_READ';
function BatchPlanningAnchorRouteModel_Resolve(input){input=input||{};var email=String(input.auditorEmail||'').trim().toLowerCase(),from=BatchPlanningCandidateEngine_date_(input.periodFrom),to=BatchPlanningCandidateEngine_date_(input.periodTo);if(!email||!from||!to)return{ok:false,error:'VALID_AUDITOR_PERIOD_REQUIRED',writesPerformed:false};var auditor=BatchPlanningReadModel_GetAuditor(email,false);if(!auditor||!auditor.ok)return{ok:false,error:'AUDITOR_NOT_FOUND',writesPerformed:false};var nearest=BatchPlanningAnchorRouteModel_nearest_(email,from,to),prev=nearest.previousAudit,next=nearest.nextAudit,homeRaw=input.home||input.auditorDeparturePoint||auditor.defaultDepartureFrom||'',inRaw=input.inboundPoint||(prev&&prev.point)||homeRaw,outRaw=input.outboundPoint||(next&&next.point)||homeRaw;return{ok:true,build:BATCH_PLANNING_ANCHOR_ROUTE_MODEL_BUILD,auditor:auditor,previousAudit:prev,nextAudit:next,home:BatchPlanning_normalizePoint_(homeRaw),inbound:BatchPlanning_normalizePoint_(inRaw),outbound:BatchPlanning_normalizePoint_(outRaw),inboundSource:input.inboundPoint?'PLANNER_OVERRIDE':(prev&&prev.point?'PREVIOUS_PLANNED_AUDIT':'HOME'),outboundSource:input.outboundPoint?'PLANNER_OVERRIDE':(next&&next.point?'NEXT_PLANNED_AUDIT':'HOME'),fixedAnchorStatuses:['Approved','Accepted'],nearestAnchorHorizonDays:null,existingAuditsImmutable:true,auditPlanningReads:nearest.auditPlanningReads,writesPerformed:false};}
function BatchPlanningAnchorRouteModel_nearest_(email,from,to){var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Audit planning');if(!sh)return{previousAudit:null,nextAudit:null,auditPlanningReads:0};var v=sh.getDataRange().getValues();if(v.length<2)return{previousAudit:null,nextAudit:null,auditPlanningReads:1};var idx=BatchPlanningCandidateEngine_headerMap_(v[0]),fromMs=from.getTime(),toMs=to.getTime(),prev=null,next=null;for(var r=1;r<v.length;r++){var row=v[r]||[],auditor=BatchPlanningCandidateEngine_text_(row,idx,['Auditor email','Auditor Email','Auditor','AuditorEmail']).toLowerCase();if(auditor!==email)continue;var status=BatchPlanningCandidateEngine_text_(row,idx,['Status']),ns=status.toLowerCase();if(ns!=='approved'&&ns!=='accepted')continue;var id=BatchPlanningCandidateEngine_text_(row,idx,['Audit ID']);if(!id)continue;var d=BatchPlanningAnchorRouteModel_rowDate_(row,idx);if(!d)continue;var ms=d.getTime(),a={auditId:id,date:BatchPlanningCandidateEngine_iso_(d),startTime:BatchPlanningCandidateEngine_text_(row,idx,['Start time','Start Time','Time from','From time']),endTime:BatchPlanningCandidateEngine_text_(row,idx,['End time','End Time','Time to','To time']),status:status,slot:'PLANNING',fixed:true,company:BatchPlanningCandidateEngine_text_(row,idx,['Company']),companyUid:BatchPlanningCandidateEngine_text_(row,idx,['Company_UID','Company UID']),location:BatchPlanningCandidateEngine_text_(row,idx,['Location','Audit location','Execution location'])};if(ms<fromMs&&(!prev||ms>prev._ms)){a._ms=ms;prev=a;}else if(ms>toMs&&(!next||ms<next._ms)){a._ms=ms;next=a;}}if(prev){delete prev._ms;prev=BatchPlanningAnchorRouteModel_enrich_(prev);}if(next){delete next._ms;next=BatchPlanningAnchorRouteModel_enrich_(next);}return{previousAudit:prev,nextAudit:next,auditPlanningReads:1};}
function BatchPlanningAnchorRouteModel_rowDate_(row,idx){var names=['Planned date','Planned Date','Audit date','Audit Date','Date','Start date','Start Date'];for(var i=0;i<names.length;i++){var k=idx[String(names[i]).trim().toLowerCase()];if(k==null)continue;var d=BatchPlanningCandidateEngine_date_(row[k]);if(d)return d;}return null;}
function BatchPlanningAnchorRouteModel_enrich_(a){var loc=BatchPlanning_getCompanyLocation_(a.company,a.location);a.point=loc&&loc.ok?loc.point:'';a.locationResolved=!!a.point;return a;}
