/**
 * FILE: BatchPlanningDayScheduler.gs
 * BUILD: 2026-09-19_BATCH_PLANNING_DAY_SCHEDULER_R12_OPERATIONAL_SCHEDULING_HOURS
 * Read-only scheduler. Preserves route order and splits long audits across feasible days.
 */
var BATCH_PLANNING_DAY_SCHEDULER_BUILD='2026-09-19_BATCH_PLANNING_DAY_SCHEDULER_R12_OPERATIONAL_SCHEDULING_HOURS';
function BatchPlanningDayScheduler_Build(input){
 input=input||{};var auditorEmail=String(input.auditorEmail||'').trim().toLowerCase(),from=BatchPlanningCandidateEngine_date_(input.periodFrom),to=BatchPlanningCandidateEngine_date_(input.periodTo);
 if(!auditorEmail||!from||!to||to.getTime()<from.getTime())return{ok:false,error:'VALID_AUDITOR_PERIOD_REQUIRED',days:[],writesPerformed:false};
 var raw=AvailabilityService.getAuditorAvailabilityRaw(auditorEmail,BatchPlanningCandidateEngine_iso_(from),BatchPlanningCandidateEngine_iso_(to),{})||{days:{}},days=[],map={},d=new Date(from.getTime());
 while(d.getTime()<=to.getTime()){var iso=BatchPlanningCandidateEngine_iso_(d),r=(raw.days||{})[iso]||{},anchors=BatchPlanningDayScheduler_anchors_(r),day={date:iso,fixedAnchors:anchors,conceptAudits:[],auditHours:BatchPlanningDayScheduler_anchorHours_(anchors),targetAuditHours:{min:8,max:9,hardCap:false},warnings:[]};days.push(day);map[iso]=day;d.setDate(d.getDate()+1);}
 var candidates=Array.isArray(input.candidates)?input.candidates:[],unresolved=[],lastAssigned='',tripArrivalTravelConsumed=false,allowWeekend=input.allowWeekend===true;
 candidates.forEach(function(c,routeIndex){
  var formalTotal=Number(c.hoursToBePlanned||0),total=Number(c.schedulingHours==null?formalTotal:c.schedulingHours);if(!isFinite(total)||total<=0){unresolved.push({auditId:c.auditId,reason:'SCHEDULING_HOURS_REQUIRED'});return;}
  var allowed=(c.hardAvailableDays||[]).filter(function(iso){return !!map[iso]&&iso>=String(c.schedulableFrom||'')&&iso<=String(c.schedulableTo||'')&&(!lastAssigned||iso>=lastAssigned)&&(allowWeekend||!BatchPlanningDayScheduler_isWeekend_(iso));});
  if(!allowed.length){unresolved.push({auditId:c.auditId,reason:'NO_ROUTE_ORDERED_SCHEDULABLE_DAY'});return;}
  var remaining=total,segments=[],first=true;
  for(var ai=0;ai<allowed.length&&remaining>0.0001;ai++){
   var day=map[allowed[ai]],travelMinutes=first?Math.ceil(Number(c.routeFromPrevious&&c.routeFromPrevious.durationSeconds||0)/60):0;if(routeIndex===0&&travelMinutes>240&&!tripArrivalTravelConsumed){travelMinutes=0;tripArrivalTravelConsumed=true;}var clockUsed=BatchPlanningDayScheduler_clockUsedMinutes_(day),clockCapacity=Math.max(0,9*60-clockUsed-travelMinutes),capacity=Math.max(0,Math.min(9-day.auditHours,clockCapacity/60));if(capacity<=0.0001)continue;
   var segment=Math.min(remaining,capacity);
   if(remaining>segment&&segment<2)continue;
   var timing=BatchPlanningDayScheduler_allocateTime_(day,segment,travelMinutes);
   if(!timing.ok)continue;
   var part={auditId:c.auditId,company:c.company,hours:segment,startTime:timing.startTime,endTime:timing.endTime,fixed:false,source:'BATCH_CONCEPT',routeIndex:routeIndex,routeFromPrevious:first?(c.routeFromPrevious||null):null,travelMinutesFromPrevious:travelMinutes,hardAvailableDays:(c.hardAvailableDays||[]).slice(),schedulableFrom:c.schedulableFrom||'',schedulableTo:c.schedulableTo||'',planningWindowFrom:c.planningWindowFrom||'',planningWindowTo:c.planningWindowTo||'',softWarnings:(c.softWarnings||[]).slice(),rotation:c.rotation||null,multiDayAudit:total>9,segmentIndex:segments.length,totalAuditHours:formalTotal,totalSchedulingHours:total,schedulingHoursSource:c.schedulingHoursSource||'FORMAL_FALLBACK'};
   day.conceptAudits.push(part);day.auditHours+=segment;segments.push({date:allowed[ai],hours:segment});remaining-=segment;lastAssigned=allowed[ai];first=false;
  }
  if(remaining>0.0001){var assigned=total-remaining;unresolved.push({auditId:c.auditId,company:c.company,reason:'INSUFFICIENT_SCHEDULABLE_HOURS_IN_PERIOD',hoursRequired:total,hoursAssigned:assigned,hoursUnassigned:remaining,formalAuditHours:formalTotal,schedulingHours:total,lastRouteOrderedDate:lastAssigned,hardAvailableDays:(c.hardAvailableDays||[]).slice(),schedulableFrom:c.schedulableFrom||'',schedulableTo:c.schedulableTo||''});BatchPlanningDayScheduler_removeAudit_(days,c.auditId);lastAssigned=BatchPlanningDayScheduler_lastAssigned_(days);}
 });
 days.forEach(function(day){if(day.auditHours>9.0001)day.warnings.push({code:'AUDIT_HOURS_ABOVE_TARGET',advisory:true,hours:day.auditHours});if(day.auditHours>0&&day.auditHours<8)day.warnings.push({code:'AUDIT_HOURS_BELOW_TARGET',advisory:true,hours:day.auditHours});});
 return{ok:true,build:BATCH_PLANNING_DAY_SCHEDULER_BUILD,advisoryOnly:true,auditorEmail:auditorEmail,days:days,unresolved:unresolved,fixedAnchorsImmutable:true,fixedAnchorStatuses:['Approved','Accepted'],auditHoursLeading:false,operationalSchedulingHoursLeading:true,formalAuditHoursPreserved:true,routeOrderPreserved:true,longInboundTravelTreatedAsTripArrival:true,targetAuditHoursPerDay:{min:8,max:9,hardCap:false},travelHardDayCap:false,multiDayAuditsSupported:true,writesPerformed:false};
}
function BatchPlanningDayScheduler_isWeekend_(iso){var d=new Date(String(iso||'')+'T12:00:00');return !isNaN(d.getTime())&&(d.getDay()===0||d.getDay()===6);}
function BatchPlanningDayScheduler_roundUp_(mins,step){step=Number(step)||30;return Math.ceil(Number(mins||0)/step)*step;}
function BatchPlanningDayScheduler_clockUsedMinutes_(day){var min=Infinity,max=-Infinity;(day.fixedAnchors||[]).concat(day.conceptAudits||[]).forEach(function(a){var s=BatchPlanningDayScheduler_minutes_(a.startTime),e=BatchPlanningDayScheduler_minutes_(a.endTime);if(isFinite(s)&&isFinite(e)&&e>s){if(s<min)min=s;if(e>max)max=e;}});return min===Infinity?0:max-min;}
function BatchPlanningDayScheduler_removeAudit_(days,auditId){(days||[]).forEach(function(day){for(var i=day.conceptAudits.length-1;i>=0;i--)if(String(day.conceptAudits[i].auditId||'')===String(auditId||'')){day.auditHours-=Number(day.conceptAudits[i].hours||0);day.conceptAudits.splice(i,1);}});}
function BatchPlanningDayScheduler_lastAssigned_(days){var last='';(days||[]).forEach(function(day){if((day.conceptAudits||[]).length)last=day.date;});return last;}
function BatchPlanningDayScheduler_anchors_(rawDay){var meta=(rawDay&&rawDay.meta)||{},out=[],seen={};function add(id,start,end,status,slot){id=String(id||'').trim();status=String(status||'').trim();var normalized=status.toLowerCase();if(!id||(normalized!=='approved'&&normalized!=='accepted')||seen[id+'|'+slot])return;seen[id+'|'+slot]=true;out.push({auditId:id,startTime:String(start||''),endTime:String(end||''),status:status,slot:slot,fixed:true,source:'AvailabilityService'});}add(meta.auditId1,meta.slot1Start,meta.slot1End,meta.status1,'S1');add(meta.auditId2,meta.slot2Start,meta.slot2End,meta.status2,'S2');return out;}
function BatchPlanningDayScheduler_anchorHours_(anchors){var mins=0;(anchors||[]).forEach(function(a){var s=BatchPlanningDayScheduler_minutes_(a.startTime),e=BatchPlanningDayScheduler_minutes_(a.endTime);if(isFinite(s)&&isFinite(e)&&e>s)mins+=e-s;});return mins/60;}
function BatchPlanningDayScheduler_minutes_(v){var m=String(v||'').match(/^(\d{1,2}):(\d{2})$/);if(!m)return NaN;var h=Number(m[1]),n=Number(m[2]);return h>=0&&h<=23&&n>=0&&n<=59?h*60+n:NaN;}
function BatchPlanningDayScheduler_allocateTime_(day,hours,travelMinutes){var start=8*60,duration=Math.round(Number(hours||0)*60),occupied=[],travel=Math.max(0,Math.round(Number(travelMinutes||0)));(day.fixedAnchors||[]).forEach(function(a){var s=BatchPlanningDayScheduler_minutes_(a.startTime),e=BatchPlanningDayScheduler_minutes_(a.endTime);if(isFinite(s)&&isFinite(e)&&e>s)occupied.push({s:s,e:e});});(day.conceptAudits||[]).forEach(function(a){var s=BatchPlanningDayScheduler_minutes_(a.startTime),e=BatchPlanningDayScheduler_minutes_(a.endTime);if(isFinite(s)&&isFinite(e)&&e>s)occupied.push({s:s,e:e});});occupied.sort(function(a,b){return a.s-b.s;});for(var i=0;i<occupied.length;i++){if(start+travel+duration<=occupied[i].s)break;if(start<occupied[i].e)start=occupied[i].e;}start+=travel;start=BatchPlanningDayScheduler_roundUp_(start,30);if(start+duration>17*60)return{ok:false};function hm(m){return('0'+Math.floor(m/60)).slice(-2)+':'+('0'+(m%60)).slice(-2);}return{ok:true,startTime:hm(start),endTime:hm(start+duration)};}
