/**
 * FILE: BatchPlanningAnchorRouteModel.gs
 * BUILD: 2026-09-17_BATCH_PLANNING_ANCHOR_ROUTE_MODEL_R3_UNBOUNDED_NEAREST
 * Read-only boundary resolver. Immediate previous/next Approved/Accepted audits are resolved without an arbitrary day horizon.
 */
var BATCH_PLANNING_ANCHOR_ROUTE_MODEL_BUILD='2026-09-17_BATCH_PLANNING_ANCHOR_ROUTE_MODEL_R3_UNBOUNDED_NEAREST';
function BatchPlanningAnchorRouteModel_Resolve(input){input=input||{};var email=String(input.auditorEmail||'').trim().toLowerCase(),from=BatchPlanningCandidateEngine_date_(input.periodFrom),to=BatchPlanningCandidateEngine_date_(input.periodTo);if(!email||!from||!to)return{ok:false,error:'VALID_AUDITOR_PERIOD_REQUIRED',writesPerformed:false};var auditor=BatchPlanningReadModel_GetAuditor(email,false);if(!auditor||!auditor.ok)return{ok:false,error:'AUDITOR_NOT_FOUND',writesPerformed:false};var nearest=BatchPlanningAnchorRouteModel_nearest_(email,from,to),prev=nearest.previousAudit,next=nearest.nextAudit,ids=[];if(prev)ids.push(prev.auditId);if(next)ids.push(next.auditId);var details=BatchPlanningAnchorRouteModel_details_(ids);if(prev)prev=BatchPlanningAnchorRouteModel_enrich_(prev,details[prev.auditId]);if(next)next=BatchPlanningAnchorRouteModel_enrich_(next,details[next.auditId]);var homeRaw=input.home||input.auditorDeparturePoint||auditor.defaultDepartureFrom||'',inRaw=input.inboundPoint||(prev&&prev.point)||homeRaw,outRaw=input.outboundPoint||(next&&next.point)||homeRaw;return{ok:true,build:BATCH_PLANNING_ANCHOR_ROUTE_MODEL_BUILD,auditor:auditor,previousAudit:prev,nextAudit:next,home:BatchPlanning_normalizePoint_(homeRaw),inbound:BatchPlanning_normalizePoint_(inRaw),outbound:BatchPlanning_normalizePoint_(outRaw),inboundSource:input.inboundPoint?'PLANNER_OVERRIDE':(prev&&prev.point?'PREVIOUS_PLANNED_AUDIT':'HOME'),outboundSource:input.outboundPoint?'PLANNER_OVERRIDE':(next&&next.point?'NEXT_PLANNED_AUDIT':'HOME'),fixedAnchorStatuses:['Approved','Accepted'],nearestAnchorHorizonDays:null,existingAuditsImmutable:true,writesPerformed:false};}
function BatchPlanningAnchorRouteModel_nearest_(email,from,to){var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Audit planning');if(!sh)return{previousAudit:null,nextAudit:null};var v=sh.getDataRange().getValues();if(v.length<2)return{previousAudit:null,nextAudit:null};var idx=BatchPlanningCandidateEngine_headerMap_(v[0]),fromMs=from.getTime(),toMs=to.getTime(),prev=null,next=null;for(var r=1;r<v.length;r++){var row=v[r]||[],auditor=BatchPlanningCandidateEngine_text_(row,idx,['Auditor email','Auditor Email','Auditor','AuditorEmail']).toLowerCase();if(auditor!==email)continue;var status=BatchPlanningCandidateEngine_text_(row,idx,['Status']),ns=status.toLowerCase();if(ns!=='approved'&&ns!=='accepted')continue;var id=BatchPlanningCandidateEngine_text_(row,idx,['Audit ID']);if(!id)continue;var d=BatchPlanningAnchorRouteModel_rowDate_(row,idx);if(!d)continue;var ms=d.getTime(),a={auditId:id,date:BatchPlanningCandidateEngine_iso_(d),startTime:BatchPlanningCandidateEngine_text_(row,idx,['Start time','Start Time','Time from','From time']),endTime:BatchPlanningCandidateEngine_text_(row,idx,['End time','End Time','Time to','To time']),status:status,slot:'PLANNING',fixed:true};if(ms<fromMs&&(!prev||ms>prev._ms)){a._ms=ms;prev=a;}else if(ms>toMs&&(!next||ms<next._ms)){a._ms=ms;next=a;}}if(prev)delete prev._ms;if(next)delete next._ms;return{previousAudit:prev,nextAudit:next};}
function BatchPlanningAnchorRouteModel_rowDate_(row,idx){var names=['Planned date','Planned Date','Audit date','Audit Date','Date','Start date','Start Date'];for(var i=0;i<names.length;i++){var k=idx[String(names[i]).trim().toLowerCase()];if(k==null)continue;var d=BatchPlanningCandidateEngine_date_(row[k]);if(d)return d;}return null;}
function BatchPlanningAnchorRouteModel_add_(out,date,id,start,end,status,slot){id=String(id||'').trim();status=String(status||'').trim();var normalized=status.toLowerCase();if(id&&(normalized==='approved'||normalized==='accepted'))out.push({auditId:id,date:date,startTime:String(start||''),endTime:String(end||''),status:status,slot:slot,fixed:true});}
function BatchPlanningAnchorRouteModel_details_(ids){var wanted={};(ids||[]).forEach(function(id){wanted[String(id)]=true;});if(!Object.keys(wanted).length)return{};var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Audit planning');if(!sh)return{};var v=sh.getDataRange().getValues();if(v.length<2)return{};var idx=BatchPlanningCandidateEngine_headerMap_(v[0]),out={};for(var r=1;r<v.length;r++){var row=v[r]||[],id=BatchPlanningCandidateEngine_text_(row,idx,['Audit ID']);if(!wanted[id])continue;out[id]={company:BatchPlanningCandidateEngine_text_(row,idx,['Company']),companyUid:BatchPlanningCandidateEngine_text_(row,idx,['Company_UID','Company UID']),location:BatchPlanningCandidateEngine_text_(row,idx,['Location','Audit location','Execution location'])};}return out;}
function BatchPlanningAnchorRouteModel_enrich_(a,d){d=d||{};a.company=d.company||'';a.companyUid=d.companyUid||'';a.location=d.location||'';var loc=BatchPlanning_getCompanyLocation_(a.company,a.location);a.point=loc&&loc.ok?loc.point:'';a.locationResolved=!!a.point;return a;}
