/***********************************************************************
 * CanonicalValidatorRegressionTests.js
 * BUILD: 2026-09-16_ROADMAP_2_4_CANONICAL_VALIDATOR_REGRESSION_R2_ROTATION_GATE
 * Non-destructive regression fixtures. No Sheet writes.
 ***********************************************************************/
var CANONICAL_VALIDATOR_REGRESSION_BUILD='2026-09-16_ROADMAP_2_4_CANONICAL_VALIDATOR_REGRESSION_R2_ROTATION_GATE';
function CVR_assert_(condition,message){if(!condition)throw new Error(message||'Assertion failed');}
function CVR_eq_(actual,expected,message){if(actual!==expected)throw new Error((message||'Values differ')+': expected='+expected+', actual='+actual);}
function CVR_testContractLevels_(){var v1=CanonicalValidator_ok(CanonicalValidatorKind.QUALIFICATION,'Q_OK','ok'),v2=CanonicalValidator_warning(CanonicalValidatorKind.ROTATION,'R_WARN','warn'),v3=CanonicalValidator_waiverRequired(CanonicalValidatorKind.ROTATION,'R_WAIVER','waiver'),v4=CanonicalValidator_hardBlock(CanonicalValidatorKind.AVAILABILITY,'A_BLOCK','block');CVR_eq_(v1.level,'OK','OK verdict');CVR_eq_(v2.level,'WARNING','WARNING verdict');CVR_eq_(v3.level,'WAIVER_REQUIRED','WAIVER_REQUIRED verdict');CVR_eq_(v4.level,'HARD_BLOCK','HARD_BLOCK verdict');CVR_assert_(v3.waiverEligible===true,'Waiver verdict must be waiver eligible');CVR_assert_(v4.waiverEligible===false,'Hard block may not be waiver eligible');}
function CVR_testAggregate_(){var a=CanonicalValidator_aggregate([CanonicalValidator_ok(CanonicalValidatorKind.QUALIFICATION,'Q_OK','ok'),CanonicalValidator_warning(CanonicalValidatorKind.ROTATION,'R_WARN','warn'),CanonicalValidator_waiverRequired(CanonicalValidatorKind.ROTATION,'R_WAIVER','waiver')]);CVR_eq_(a.overallLevel,'WAIVER_REQUIRED','Aggregate worst level');CVR_assert_(a.canCommitWithoutWaiver===false,'Waiver aggregate must block normal commit');CVR_assert_(a.canCommitWithWaiver===true,'Waiver aggregate must permit governed waiver');CVR_eq_(a.counts.warnings,1,'Warning count');CVR_eq_(a.counts.waiversRequired,1,'Waiver count');CVR_eq_(a.counts.hardBlocks,0,'Hard block count');}
function CVR_baseContext_(){return{auditId:'AUD_TEST_CANONICAL_VALIDATORS',auditorEmail:'auditor@example.com',auditorName:'Regression Auditor',company:'Regression Company',requiredScopes:['MPS-ABC'],blocks:[{date:'2026-09-15',start:'09:00',end:'17:00'}],precomputed:{qualification:{success:true,message:'qualified'},availability:{success:true,message:'available'},planningWindow:{startDate:'2026-09-01',endDate:'2026-09-30',mode:'INTERSECTION',activeScopes:['MPS-ABC'],scopeWindows:[],warnings:[]},rotation:{softBlockRotation:false,performedCount:1,maxAllowed:3,performedByScope:{'MPS-ABC':1}}}};}
function CVR_testAllOkWithPrecomputedOwnerResults_(){var r=CanonicalPlanningValidators_evaluate(CVR_baseContext_());CVR_eq_(r.overallLevel,'OK','All-OK aggregate');CVR_assert_(r.canCommitWithoutWaiver===true,'All-OK must permit normal commit');CVR_eq_(r.verdicts.length,4,'Expected four canonical verdicts');}
function CVR_testQualificationHardBlock_(){var c=CVR_baseContext_();c.precomputed.qualification={success:false,message:'not qualified'};var r=CanonicalPlanningValidators_evaluate(c);CVR_eq_(r.overallLevel,'HARD_BLOCK','Qualification failure must hard block');CVR_assert_(r.canCommitWithWaiver===false,'Qualification hard block cannot be waived');}
function CVR_testAvailabilityHardBlock_(){var c=CVR_baseContext_();c.precomputed.availability={success:false,message:'collision'};CVR_eq_(CanonicalPlanningValidators_evaluate(c).overallLevel,'HARD_BLOCK','Availability conflict must hard block');}
function CVR_testPlanningWindowOutsideHardBlock_(){var c=CVR_baseContext_();c.blocks=[{date:'2026-10-01',start:'09:00',end:'17:00'}];var r=CanonicalPlanningValidators_evaluate(c);CVR_eq_(r.overallLevel,'HARD_BLOCK','Outside planning window must hard block');var found=false;for(var i=0;i<r.verdicts.length;i++)if(r.verdicts[i].ruleCode==='PLANNING_WINDOW_OUTSIDE')found=true;CVR_assert_(found,'PLANNING_WINDOW_OUTSIDE verdict missing');}
function CVR_testPlanningWindowSoftWarning_(){var c=CVR_baseContext_();c.precomputed.planningWindow.warnings=[{code:'SCOPE_WINDOW_CONFLICT_EMPTY_INTERSECTION',severity:'WARN',message:'soft conflict'}];c.precomputed.planningWindow.mode='UNION_FALLBACK';var r=CanonicalPlanningValidators_evaluate(c);CVR_eq_(r.overallLevel,'WARNING','Planning-window soft warning must remain advisory');CVR_assert_(r.canCommitWithoutWaiver===true,'WARNING must not block commit');}
function CVR_testRotationSoftWarning_(){var c=CVR_baseContext_();c.precomputed.rotation.softBlockRotation=true;c.precomputed.rotation.performedCount=3;c.precomputed.rotation.maxAllowed=3;var r=CanonicalPlanningValidators_evaluate(c);CVR_eq_(r.overallLevel,'WARNING','Current rotation limit remains warning in this gate');CVR_assert_(r.canCommitWithoutWaiver===true,'Current rotation warning must not block commit');}
function CVR_testExplicitInclude_(){var c=CVR_baseContext_();c.include={qualification:true,availability:false,planningWindow:false,rotation:false};var r=CanonicalPlanningValidators_evaluate(c);CVR_eq_(r.verdicts.length,1,'Explicit include must limit validator set');CVR_eq_(r.verdicts[0].kind,'QUALIFICATION','Qualification-only result');}
function CVR_testGatewayRotationDefaultAdvisory_(){CVR_eq_(CPVG_rotationPolicyMode_({}),'ADVISORY','Gateway default rotation mode');CVR_eq_(CPVG_rotationPolicyMode_({rotationPolicyMode:'unknown'}),'ADVISORY','Unknown rotation mode must fail safe to advisory');var q=CanonicalValidator_ok(CanonicalValidatorKind.QUALIFICATION,'QUALIFICATION_OK','ok',{evidence:{auditor:{softBlockRotation:true,performedCount:3,maxAllowed:3,performedByScope:{'MPS-ABC':3}}}});var v=CPVG_rotationVerdict_({auditId:'AUD_TEST',auditorEmail:'auditor@example.com',auditorName:'Regression Auditor',company:'Regression Company',requiredScopes:['MPS-ABC'],precomputed:{},rotationPolicyMode:'ADVISORY'},q);CVR_eq_(v.level,'WARNING','Gateway must keep current rotation advisory by default');CVR_eq_(v.ruleCode,'ROTATION_SOFT_LIMIT','Gateway must use current soft rotation rule before governed tiered release');}
function CVR_testGatewayTieredModeIsExplicit_(){CVR_eq_(CPVG_rotationPolicyMode_({rotationPolicyMode:'TIERED'}),'TIERED','Tiered mode must require explicit opt-in');CVR_eq_(CPVG_rotationPolicyMode_({rotationPolicyMode:'tiered'}),'TIERED','Tiered mode normalization');}
function RUN_CANONICAL_VALIDATOR_REGRESSION(){var tests=[['contractLevels',CVR_testContractLevels_],['aggregate',CVR_testAggregate_],['allOkPrecomputed',CVR_testAllOkWithPrecomputedOwnerResults_],['qualificationHardBlock',CVR_testQualificationHardBlock_],['availabilityHardBlock',CVR_testAvailabilityHardBlock_],['planningWindowOutside',CVR_testPlanningWindowOutsideHardBlock_],['planningWindowSoftWarning',CVR_testPlanningWindowSoftWarning_],['rotationSoftWarning',CVR_testRotationSoftWarning_],['explicitInclude',CVR_testExplicitInclude_],['gatewayRotationDefaultAdvisory',CVR_testGatewayRotationDefaultAdvisory_],['gatewayTieredModeExplicit',CVR_testGatewayTieredModeIsExplicit_]],results=[],failed=0;for(var i=0;i<tests.length;i++){try{tests[i][1]();results.push({name:tests[i][0],ok:true});}catch(e){failed++;results.push({name:tests[i][0],ok:false,error:String(e&&e.message?e.message:e)});}}var out={ok:failed===0,build:CANONICAL_VALIDATOR_REGRESSION_BUILD,total:tests.length,passed:tests.length-failed,failed:failed,results:results};Logger.log(JSON.stringify(out,null,2));return out;}
