steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ams-transport-proof:$COMMIT_SHA
      - cloudrun/transport-proof
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ams-transport-proof:$COMMIT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ams-transport-proof
      - --image
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ams-transport-proof:$COMMIT_SHA
      - --region
      - europe-west1
      - --service-account
      - 510075419067-compute@developer.gserviceaccount.com
      - --update-env-vars
      - DEV_SSOT_SPREADSHEET_ID=1NhgaGxCU3BsEPMlKk14Iiz2XbPedS3e9sXI7OzeOJRs,GAS_DEV_WRITE_URL=$_GAS_DEV_WRITE_URL
      - --update-secrets
      - AMS_SESSION_SIGNING_SECRET=AMS_SESSION_SIGNING_SECRET:latest,AMS_EXTERNAL_WRITE_BRIDGE_KEY=AMS_EXTERNAL_WRITE_BRIDGE_KEY:latest
images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ams-transport-proof:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
