/**
 * FILE: CompaniesIndexBatchPlanningLocationMetadata.gs
 * BUILD: 2026-09-17_COMPANIES_INDEX_BATCH_LOCATION_METADATA_R2_EXEC_INDEX
 *
 * Batch-only compatibility index for optional Locations_JSON planning metadata.
 * One Companies read maximum per GAS execution; candidate lookups are O(1).
 * CompaniesIndexService V4 AMS01 remains untouched.
 */
var COMPANIES_INDEX_BATCH_LOCATION_METADATA_BUILD='2026-09-17_COMPANIES_INDEX_BATCH_LOCATION_METADATA_R2_EXEC_INDEX';
var COMPANIES_INDEX_BATCH_LOCATION_EXEC_INDEX=null;
function CompaniesIndexBatchPlanning_GetLocations(companyUid,companyName){var index=CompaniesIndexBatchPlanning_index_();if(!index.ok)return{ok:false,error:index.error,locations:[]};var uid=CompaniesIndex_clean_(companyUid),nameKey=CompaniesIndex_nameKey_(companyName),rec=(uid&&index.byUid[uid])||(nameKey&&index.byName[nameKey])||null;if(!rec)return{ok:false,error:'COMPANY_NOT_FOUND',locations:[]};return{ok:true,owner:'Companies.Locations_JSON',companyUid:rec.companyUid,companyName:rec.companyName,locations:rec.locations};}
function CompaniesIndexBatchPlanning_index_(){if(COMPANIES_INDEX_BATCH_LOCATION_EXEC_INDEX)return COMPANIES_INDEX_BATCH_LOCATION_EXEC_INDEX;var ss=SpreadsheetApp.getActiveSpreadsheet(),sh=ss.getSheetByName('Companies');if(!sh)return COMPANIES_INDEX_BATCH_LOCATION_EXEC_INDEX={ok:false,error:'COMPANIES_SHEET_NOT_FOUND',byUid:{},byName:{}};var vals=sh.getDataRange().getValues(),out={ok:true,owner:'Companies.Locations_JSON',byUid:{},byName:{},readCount:1};if(!vals.length)return COMPANIES_INDEX_BATCH_LOCATION_EXEC_INDEX=out;var idx=CompaniesIndex_headerMap_(vals[0]);for(var r=1;r<vals.length;r++){var row=vals[r]||[],uid=CompaniesIndex_clean_(CompaniesIndex_val_(row,idx,['Company_UID','Company UID','CompanyUID','COMPANY_UID','UID'])),name=CompaniesIndex_clean_(CompaniesIndex_val_(row,idx,['Company','Company name','Name','Bedrijf','COMPANY']));if(!uid&&!name)continue;var raw=CompaniesIndex_clean_(CompaniesIndex_val_(row,idx,['Locations_JSON','Locations JSON','LocationsJSON'])),legacyLocation=CompaniesIndex_clean_(CompaniesIndex_val_(row,idx,['Location','HQ Location','HQ'])),legacyGps=CompaniesIndex_clean_(CompaniesIndex_val_(row,idx,['GPS-data','GPS data','GPS','GPS HQ'])),rec={companyUid:uid,companyName:name,locations:CompaniesIndexBatchPlanning_parse_(raw,legacyLocation,legacyGps)};if(uid)out.byUid[uid]=rec;if(name)out.byName[CompaniesIndex_nameKey_(name)]=rec;}COMPANIES_INDEX_BATCH_LOCATION_EXEC_INDEX=out;return out;}
function CompaniesIndexBatchPlanning_ClearExecutionIndex(){COMPANIES_INDEX_BATCH_LOCATION_EXEC_INDEX=null;return{ok:true};}
function CompaniesIndexBatchPlanning_parse_(raw,legacyLocation,legacyGps){if(!raw)return(legacyLocation||legacyGps)?[{code:'HQ',label:legacyLocation||'',gps:legacyGps||'',comment:'',separatePlanningStop:false,defaultPlanningHours:null}]:[];try{var p=JSON.parse(raw),list=p&&Array.isArray(p.locations)?p.locations:(Array.isArray(p)?p:[]);return list.map(function(loc,i){loc=loc||{};var h=loc.defaultPlanningHours;h=(h==null||h==='')?null:Number(h);if(h!=null&&!isFinite(h))h=null;return{code:CompaniesIndex_clean_(loc.code)||('L'+(i+1)),label:CompaniesIndex_clean_(loc.label||loc.name||loc.location),gps:CompaniesIndex_clean_(loc.gps||loc.GPS||loc.gpsData),comment:CompaniesIndex_clean_(loc.comment||loc.notes),separatePlanningStop:loc.separatePlanningStop===true,defaultPlanningHours:h};}).filter(function(loc){return !!(loc.label||loc.gps||loc.comment);});}catch(e){return(legacyLocation||legacyGps)?[{code:'HQ',label:legacyLocation||'',gps:legacyGps||'',comment:'',separatePlanningStop:false,defaultPlanningHours:null}]:[];}}
