/***********************************************************************
 * ConceptPlanningService.js
 * BUILD: 2026-09-23_CONCEPT_PLANNING_R9_PREFERRED_MONTHS_OPT_IN
 ***********************************************************************/
var CONCEPT_PLANNING_BUILD='2026-09-23_CONCEPT_PLANNING_R7_REUSE_DEMAND_COMPANY_META';
function CPS_clean_(v){return String(v==null?'':v).trim();}function CPS_norm_(v){return CPS_clean_(v).toLowerCase();}
function CPS_rankAuditors_(auditors){var out=(auditors||[]).slice();out.sort(function(a,b){var ap=a&&a.isPreassigned===true?0:1,bp=b&&b.isPreassigned===true?0:1;if(ap!==bp)return ap-bp;var ar=a&&a.softBlockRotation===true?1:0,br=b&&b.softBlockRotation===true?1:0;if(ar!==br)return ar-br;var ac=Number(a&&a.performedCount||0)||0,bc=Number(b&&b.performedCount||0)||0;if(ac!==bc)return ac-bc;return CPS_clean_(a&&(a.name||a.email)).localeCompare(CPS_clean_(b&&(b.name||b.email)));});return out;}
function CPS_advisoryCandidate_(a){return{name:CPS_clean_(a&&a.name),email:CPS_norm_(a&&a.email),isPreassigned:!!(a&&a.isPreassigned===true),rotationWarning:!!(a&&a.softBlockRotation===true),performedCount:Number(a&&a.performedCount||0)||0,maxAllowed:Number(a&&a.maxAllowed||0)||0,blockedWeekdays:Array.isArray(a&&a.blockedWeekdays)?a.blockedWeekdays.slice():[]};}
function CPS_demandAuditIds_(rows){var out=[],seen={};for(var i=0;i<(rows||[]).length;i++){var id=CPS_clean_(rows[i]&&rows[i].auditId);if(!id||seen[id])continue;seen[id]=true;out.push(id);}return out;}
function CPS_demandInput_(input){input=input||{};var out={},pass=['from','start','periodFrom','to','end','periodTo','status','auditor','country','region','scope','limit'];for(var p=0;p<pass.length;p++){var k=pass[p];if(Object.prototype.hasOwnProperty.call(input,k))out[k]=input[k];}var needs=input.includeCompanyMeta===true||!!(CPS_clean_(input.country)||CPS_clean_(input.region));if(needs){out.includeCompanyMeta=true;if(input.includePreferredAuditMonths!==false)out.includePreferredAuditMonths=true;}return{input:out,needsCompanyMeta:needs};}
function CPS_refreshPolicy_(eligibility){var ids=[],rows=eligibility&&eligibility.rows?eligibility.rows:[];for(var i=0;i<rows.length;i++)if(rows[i]&&rows[i].requiresCanonicalRefresh===true)ids.push(CPS_clean_(rows[i].auditId));var missing=eligibility&&eligibility.missingAuditIds?eligibility.missingAuditIds:[];for(var m=0;m<missing.length;m++)ids.push(CPS_clean_(missing[m]));var seen={},clean=[];for(var j=0;j<ids.length;j++)if(ids[j]&&!seen[ids[j]]){seen[ids[j]]=true;clean.push(ids[j]);}return{synchronousRefresh:false,hotPathRefreshForbidden:true,refreshService:'EligibilityTargetedRefreshService_refresh',refreshAuditIds:clean,refreshCount:clean.length,recommendedMode:'bounded recovery/warm-up outside primary planning request'};}
function CPS_prefFromDemand_(rows){var byKey={},matched=0,seen={};for(var i=0;i<(rows||[]).length;i++){var r=rows[i]||{},u=CPS_clean_(r.companyUid),n=CPS_clean_(r.company),months=Array.isArray(r.preferredAuditMonths)?r.preferredAuditMonths.slice():[],p={companyUid:u,companyName:n,preferredAuditMonths:months};var uk=u?'UID::'+u:'',nk=n?'NAME::'+CPS_norm_(n).replace(/\s+/g,' '):'';if(uk)byKey[uk]=p;if(nk)byKey[nk]=p;var sk=uk||nk;if(sk&&!seen[sk]){seen[sk]=true;matched++;}}return{byKey:byKey,matched:matched,rowsRead:0,meta:{source:'PlanningDemandService company projection',reusedDemandCompanyMeta:true}};}
function CPS_lookupPref_(pref,row){row=row||{};var u=CPS_clean_(row.companyUid),n=CPS_norm_(row.company).replace(/\s+/g,' '),x=(u&&pref.byKey&&pref.byKey['UID::'+u])||(n&&pref.byKey&&pref.byKey['NAME::'+n])||null;return x&&Array.isArray(x.preferredAuditMonths)?x.preferredAuditMonths.slice():[];}
function ConceptPlanningService_get(input){
 input=input||{};if(!Object.prototype.hasOwnProperty.call(input,'includeCompanyMeta'))input.includeCompanyMeta=false;var perf=typeof DPL_start_==='function'?DPL_start_('ConceptPlanningService_get',{from:input.from||input.start||input.periodFrom||'',to:input.to||input.end||input.periodTo||''}):null;if(typeof PlanningDemandService_get!=='function')throw new Error('ConceptPlanningService: PlanningDemandService_get unavailable');if(typeof EligibilityBatchReadModel_get!=='function')throw new Error('ConceptPlanningService: EligibilityBatchReadModel_get unavailable');
 var demandPlan=CPS_demandInput_(input),demand=PlanningDemandService_get(demandPlan.input),demandRows=demand&&Array.isArray(demand.rows)?demand.rows:[];if(typeof DPL_mark_==='function')DPL_mark_(perf,'planningDemand',{demandRows:demandRows.length,companyMetaLoaded:demandPlan.needsCompanyMeta,companyProjectionUsed:demand&&demand.meta?demand.meta.companyProjectionUsed:false,preferredAuditMonthsProjected:demand&&demand.meta?demand.meta.preferredAuditMonthsProjected:false});
 var auditIds=CPS_demandAuditIds_(demandRows),eligibility=EligibilityBatchReadModel_get({auditIds:auditIds});if(typeof DPL_mark_==='function')DPL_mark_(perf,'eligibilityBatch',{requested:auditIds.length,returned:eligibility&&eligibility.rows?eligibility.rows.length:0,stale:eligibility&&eligibility.meta?eligibility.meta.stale||0:0,missing:eligibility&&eligibility.meta?eligibility.meta.missing||0:0});
 var pref,reusedDemandMeta=!!(demand&&demand.meta&&demand.meta.preferredAuditMonthsProjected===true),wantPreferred=input.includePreferredAuditMonths===true||reusedDemandMeta;if(reusedDemandMeta)pref=CPS_prefFromDemand_(demandRows);else if(wantPreferred&&typeof PlanningPreferredAuditMonthsReadModel_forDemand==='function')pref=PlanningPreferredAuditMonthsReadModel_forDemand(demandRows);else pref={byKey:{},matched:0,rowsRead:0,meta:{skipped:true,reason:'not requested on bootstrap hot path'}};if(typeof DPL_mark_==='function')DPL_mark_(perf,'preferredAuditMonths',{matched:pref.matched||0,rowsRead:pref.rowsRead||0,reusedDemandCompanyMeta:reusedDemandMeta});
 var rows=[],ready=0,refreshRequired=0,noCandidates=0,maxCandidates=Math.max(1,Math.min(20,Number(input.maxCandidates||5)||5));
 for(var i=0;i<demandRows.length;i++){var d=demandRows[i]||{},id=CPS_clean_(d.auditId),e=eligibility&&eligibility.byAuditId?eligibility.byAuditId[id]:null,reason='',candidates=[],requiresRefresh=false,refreshReasons=[];if(!e){requiresRefresh=true;reason='ELIGIBILITY_CACHE_MISSING';refreshReasons=['CACHE_MISSING'];}else if(e.requiresCanonicalRefresh===true||e.stale===true){requiresRefresh=true;reason='ELIGIBILITY_REFRESH_REQUIRED';refreshReasons=Array.isArray(e.refreshReasons)?e.refreshReasons.slice():['REFRESH_REQUIRED'];}else{candidates=CPS_rankAuditors_(e.auditors||[]).slice(0,maxCandidates).map(CPS_advisoryCandidate_);if(!candidates.length)reason='NO_ELIGIBLE_AUDITORS';}if(requiresRefresh)refreshRequired++;else if(!candidates.length)noCandidates++;else ready++;var months=reusedDemandMeta?CPS_lookupPref_(pref,d):(typeof PlanningPreferredAuditMonthsReadModel_lookup==='function'?PlanningPreferredAuditMonthsReadModel_lookup(pref,d):[]);rows.push({auditId:id,companyUid:CPS_clean_(d.companyUid),company:CPS_clean_(d.company),country:CPS_clean_(d.country),region:CPS_clean_(d.region),status:CPS_clean_(d.status),planningWindowFrom:CPS_clean_(d.planningWindowFrom),planningWindowTo:CPS_clean_(d.planningWindowTo),preferredAuditMonths:months,hasPreferredAuditMonths:months.length>0,urgency:CPS_clean_(d.urgency),scopes:Array.isArray(d.scopes)?d.scopes.slice():[],hoursToPlan:Number(d.hoursToPlan||0)||0,candidateAuditors:candidates,advisoryState:requiresRefresh?'REFRESH_REQUIRED':(candidates.length?'READY':'NO_CANDIDATES'),advisoryReason:reason,eligibilityStale:!!(e&&e.stale===true),eligibilityComputedAt:CPS_clean_(e&&e.computedAt),requiresCanonicalRefresh:requiresRefresh,eligibilityRefreshReasons:refreshReasons});}
 if(typeof DPL_mark_==='function')DPL_mark_(perf,'projectAdvisory',{returned:rows.length,ready:ready,refreshRequired:refreshRequired,noCandidates:noCandidates});var refreshPolicy=CPS_refreshPolicy_(eligibility),result={success:true,build:CONCEPT_PLANNING_BUILD,period:demand.period,rows:rows,totals:{audits:rows.length,ready:ready,refreshRequired:refreshRequired,noCandidates:noCandidates},refreshPolicy:refreshPolicy,meta:{writes:false,advisoryOnly:true,commitRevalidationRequired:true,noPerAuditReads:true,directDemandFastPath:true,planningContextSkipped:true,preferredAuditMonthsProjected:true,preferredAuditMonthsAdvisoryOnly:true,preferredAuditMonthsRowsRead:pref.rowsRead||0,preferredAuditMonthsMatched:pref.matched||0,preferredAuditMonthsReusedDemandCompanyMeta:reusedDemandMeta,companyMetaLoaded:demandPlan.needsCompanyMeta,companyProjectionUsed:demand&&demand.meta?demand.meta.companyProjectionUsed:false,synchronousEligibilityRefresh:false,canonicalOwners:{demand:'Audit planning / lifecycle',eligibility:'EligibilityService',company:'Companies',preferredAuditMonths:'Companies'}}};if(typeof DPL_end_==='function')result.devPerformance=DPL_end_(perf,{audits:rows.length,ready:ready,refreshRequired:refreshRequired,noCandidates:noCandidates,preferredAuditMonthsMatched:pref.matched||0,preferredAuditMonthsRowsRead:pref.rowsRead||0,reusedDemandCompanyMeta:reusedDemandMeta});return result;
}
