/***********************************************************************
 * ConceptReservationReadModel.js
 * BUILD: 2026-09-11_AMS01_2_CONCEPT_RESERVATION_READ_MODEL_R3_SINGLE_WINDOW
 *
 * Active Concept Reservations are a contiguous prefix directly below header.
 * Hot path uses one bounded window read. If the active prefix reaches the
 * window boundary, it falls back to the legacy exact read.
 ***********************************************************************/
var CONCEPT_RESERVATION_READ_BUILD='2026-09-11_AMS01_2_CONCEPT_RESERVATION_READ_MODEL_R3_SINGLE_WINDOW';
var CONCEPT_RESERVATION_SHEET='Concept Reservations';
var CRRM_WINDOW_ROWS=256;
var CRRM_WINDOW_COLS=16;
function CRRM_clean_(v){return String(v==null?'':v).trim();}
function CRRM_norm_(v){return CRRM_clean_(v).toLowerCase();}
function CRRM_col_(h,n){var x={};for(var i=0;i<h.length;i++)x[CRRM_norm_(h[i])]=i;for(var j=0;j<n.length;j++){var k=CRRM_norm_(n[j]);if(Object.prototype.hasOwnProperty.call(x,k))return x[k];}return-1;}
function CRRM_blocks_(raw){if(Array.isArray(raw))return raw;var s=CRRM_clean_(raw);if(!s)return[];try{var p=JSON.parse(s);return Array.isArray(p)?p:(p&&Array.isArray(p.blocks)?p.blocks:[]);}catch(e){return[];}}
function CRRM_overlap_(blocks,from,to){for(var i=0;i<blocks.length;i++){var d=CRRM_clean_(blocks[i]&&blocks[i].date);if(d&&d>=from&&d<=to)return true;}return false;}
function CRRM_activePrefixCount_(sh,stateCol){var last=sh.getLastRow();if(last<2)return 0;var states=sh.getRange(2,stateCol,last-1,1).getValues(),n=0;for(var i=0;i<states.length;i++){if(CRRM_clean_(states[i][0]).toUpperCase()!=='ACTIVE')break;n++;}return n;}
function CRRM_legacyRead_(sh,from,to,perf){var last=sh.getLastRow();if(last<2)return{vals:[],header:[],activeCount:0,lastCol:0,fallback:true,totalSheetRows:0};var lastCol=sh.getLastColumn(),h=sh.getRange(1,1,1,lastCol).getValues()[0]||[],cState=CRRM_col_(h,['State']);if(cState<0)throw new Error('ConceptReservationReadModel: required columns missing');var activeCount=CRRM_activePrefixCount_(sh,cState+1),vals=activeCount?sh.getRange(2,1,activeCount,lastCol).getValues():[];if(typeof DPL_mark_==='function')DPL_mark_(perf,'legacyFallback',{rows:activeCount,cols:lastCol,totalSheetRows:Math.max(0,last-1)});return{vals:vals,header:h,activeCount:activeCount,lastCol:lastCol,fallback:true,totalSheetRows:Math.max(0,last-1)};}
function CRRM_windowRead_(sh,perf){try{var values=sh.getRange(1,1,CRRM_WINDOW_ROWS,CRRM_WINDOW_COLS).getValues(),h=values[0]||[],cState=CRRM_col_(h,['State']);if(cState<0)return null;var body=values.slice(1),activeCount=0;for(var i=0;i<body.length;i++){if(CRRM_clean_(body[i][cState]).toUpperCase()!=='ACTIVE')break;activeCount++;}var boundaryActive=activeCount===body.length&&CRRM_clean_(body[body.length-1][cState]).toUpperCase()==='ACTIVE';if(boundaryActive)return null;if(typeof DPL_mark_==='function')DPL_mark_(perf,'singleWindowRead',{rows:CRRM_WINDOW_ROWS,cols:CRRM_WINDOW_COLS,activeRows:activeCount});return{vals:body.slice(0,activeCount),header:h,activeCount:activeCount,lastCol:CRRM_WINDOW_COLS,fallback:false,totalSheetRows:null};}catch(e){return null;}}
function ConceptReservationReadModel_get(input){input=input||{};var from=CRRM_clean_(input.from),to=CRRM_clean_(input.to);if(!from||!to)throw new Error('ConceptReservationReadModel: from/to required');if(to<from)throw new Error('ConceptReservationReadModel: to before from');var perf=(typeof DPL_start_==='function')?DPL_start_('ConceptReservationReadModel_get',{from:from,to:to}):null,sh=SpreadsheetApp.getActive().getSheetByName(CONCEPT_RESERVATION_SHEET);if(!sh){var missing={success:true,build:CONCEPT_RESERVATION_READ_BUILD,period:{from:from,to:to},rows:[],byAuditorEmail:{},meta:{sheet:CONCEPT_RESERVATION_SHEET,rowsRead:0,totalSheetRows:0,returned:0,writes:false,readOnly:true,activePrefixRead:true,singleWindowRead:false,fallbackUsed:false,fullDataRangeRead:false,noPerReservationReads:true,canonicalFinalPlanningOwner:'Audit planning'}};if(typeof DPL_end_==='function')missing.devPerformance=DPL_end_(perf,{returned:0});return missing;}var read=CRRM_windowRead_(sh,perf);if(!read)read=CRRM_legacyRead_(sh,from,to,perf);var h=read.header||[],cId=CRRM_col_(h,['Audit ID','Audit_ID']),cRid=CRRM_col_(h,['Reservation ID','Reservation_ID']),cAud=CRRM_col_(h,['Auditor Email','Auditor_Email']),cName=CRRM_col_(h,['Auditor Name','Auditor_Name']),cBlocks=CRRM_col_(h,['Blocks JSON','Blocks_JSON','Blocks']),cState=CRRM_col_(h,['State']),cRev=CRRM_col_(h,['Source Revision','Source_Revision']);if(cId<0||cAud<0||cBlocks<0||cState<0)throw new Error('ConceptReservationReadModel: required columns missing');var vals=read.vals||[],rows=[],byAud={};for(var r=0;r<vals.length;r++){var v=vals[r]||[],blocks=CRRM_blocks_(v[cBlocks]);if(!CRRM_overlap_(blocks,from,to))continue;var email=CRRM_norm_(v[cAud]),item={auditId:CRRM_clean_(v[cId]),reservationId:cRid>=0?CRRM_clean_(v[cRid]):'',auditorEmail:email,auditorName:cName>=0?CRRM_clean_(v[cName]):'',blocks:blocks,state:'ACTIVE',sourceRevision:cRev>=0?CRRM_clean_(v[cRev]):''};rows.push(item);if(!byAud[email])byAud[email]=[];byAud[email].push(item);}if(typeof DPL_mark_==='function')DPL_mark_(perf,'filterProject',{returned:rows.length,auditors:Object.keys(byAud).length});var out={success:true,build:CONCEPT_RESERVATION_READ_BUILD,period:{from:from,to:to},rows:rows,byAuditorEmail:byAud,meta:{sheet:CONCEPT_RESERVATION_SHEET,rowsRead:read.activeCount,totalSheetRows:read.totalSheetRows,returned:rows.length,writes:false,readOnly:true,activePrefixRead:true,singleWindowRead:!read.fallback,fallbackUsed:!!read.fallback,windowRows:CRRM_WINDOW_ROWS,windowCols:CRRM_WINDOW_COLS,fullDataRangeRead:false,noPerReservationReads:true,preliminaryOnly:true,canonicalFinalPlanningOwner:'Audit planning',canonicalAvailabilityOwner:'AvailabilityService / Auditor availability'}};if(typeof DPL_end_==='function')out.devPerformance=DPL_end_(perf,{returned:rows.length,auditors:Object.keys(byAud).length,activeRowsRead:read.activeCount,singleWindowRead:!read.fallback});return out;}
