/***********************************************************************
 * ConceptPlanningServiceTests.js
 * BUILD: 2026-09-09_ROADMAP_2_4_CONCEPT_PLANNING_ADVISORY_TESTS_R3_REFRESH_POLICY
 * Permanent, non-destructive regression.
 ***********************************************************************/
var CONCEPT_PLANNING_TEST_BUILD='2026-09-09_ROADMAP_2_4_CONCEPT_PLANNING_ADVISORY_TESTS_R3_REFRESH_POLICY';
function CPST_assert_(name,condition,detail,out){var ok=!!condition;out.push({name:name,ok:ok,detail:ok?'':String(detail||'failed')});}
function CPST_period_(){var tz=Session.getScriptTimeZone();var y=Number(Utilities.formatDate(new Date(),tz,'yyyy'));return{from:y+'-01-01',to:y+'-12-31'};}
function RUN_CONCEPT_PLANNING_REGRESSION(){
 var results=[];
 var ranked=CPS_rankAuditors_([{name:'B',performedCount:2,softBlockRotation:false},{name:'A',performedCount:1,softBlockRotation:false},{name:'P',isPreassigned:true,performedCount:99,softBlockRotation:true}]);
 CPST_assert_('preassignedRanksFirst',ranked[0]&&ranked[0].name==='P','preassigned first',results);
 CPST_assert_('lowerRotationCountRanksEarlier',ranked[1]&&ranked[1].name==='A','count rank',results);
 var normalPlan=CPS_demandInput_({from:'2026-01-01',to:'2026-12-31'});CPST_assert_('normalFlowSkipsCompanyMeta',normalPlan.input.includeCompanyMeta===false,'skip Companies',results);
 var countryPlan=CPS_demandInput_({from:'2026-01-01',to:'2026-12-31',country:'NL'});CPST_assert_('countryFilterLoadsCompanyMeta',countryPlan.input.includeCompanyMeta===true,'country needs Companies',results);
 var fakePolicy=CPS_refreshPolicy_({rows:[{auditId:'A',requiresCanonicalRefresh:true},{auditId:'B',requiresCanonicalRefresh:false}],missingAuditIds:['C','A']});
 CPST_assert_('refreshPolicyDedupes',fakePolicy.refreshCount===2&&fakePolicy.refreshAuditIds[0]==='A'&&fakePolicy.refreshAuditIds[1]==='C','dedupe',results);
 CPST_assert_('refreshPolicyForbidsHotPathRefresh',fakePolicy.hotPathRefreshForbidden===true&&fakePolicy.synchronousRefresh===false,'hot path guard',results);
 var p=CPST_period_(),t0=Date.now();var smoke=ConceptPlanningService_get({from:p.from,to:p.to,maxCandidates:5});var smokeMs=Date.now()-t0;
 CPST_assert_('serviceSuccess',smoke&&smoke.success===true,'service',results);CPST_assert_('rowsArray',smoke&&Array.isArray(smoke.rows),'rows',results);CPST_assert_('readOnly',smoke&&smoke.meta&&smoke.meta.writes===false,'read only',results);CPST_assert_('advisoryOnly',smoke&&smoke.meta&&smoke.meta.advisoryOnly===true,'advisory',results);CPST_assert_('commitRevalidationRequired',smoke&&smoke.meta&&smoke.meta.commitRevalidationRequired===true,'commit revalidate',results);CPST_assert_('noPerAuditReads',smoke&&smoke.meta&&smoke.meta.noPerAuditReads===true,'batch',results);CPST_assert_('eligibilityOwner',smoke&&smoke.meta&&smoke.meta.canonicalOwners&&smoke.meta.canonicalOwners.eligibility==='EligibilityService','owner',results);CPST_assert_('totalsPresent',smoke&&smoke.totals&&Number(smoke.totals.audits)>=0,'totals',results);CPST_assert_('directDemandFastPath',smoke&&smoke.meta&&smoke.meta.directDemandFastPath===true,'fast path',results);CPST_assert_('planningContextSkipped',smoke&&smoke.meta&&smoke.meta.planningContextSkipped===true,'skip context',results);CPST_assert_('companyMetaSkippedByDefault',smoke&&smoke.meta&&smoke.meta.companyMetaLoaded===false,'skip Companies',results);
 CPST_assert_('noSynchronousEligibilityRefresh',smoke&&smoke.meta&&smoke.meta.synchronousEligibilityRefresh===false,'no sync refresh',results);CPST_assert_('refreshPolicyPresent',smoke&&smoke.refreshPolicy&&smoke.refreshPolicy.refreshService==='EligibilityTargetedRefreshService_refresh','policy',results);CPST_assert_('refreshPolicyCountMatchesTotals',smoke&&smoke.refreshPolicy&&smoke.totals&&smoke.refreshPolicy.refreshCount===smoke.totals.refreshRequired,'count parity',results);
 var statesOk=true,candidatesOk=true,staleGuardOk=true,reasonsOk=true;
 for(var i=0;i<(smoke.rows||[]).length;i++){var r=smoke.rows[i]||{};if(['READY','REFRESH_REQUIRED','NO_CANDIDATES'].indexOf(r.advisoryState)<0)statesOk=false;if(!Array.isArray(r.candidateAuditors))candidatesOk=false;if(r.advisoryState==='REFRESH_REQUIRED'&&r.candidateAuditors.length!==0)staleGuardOk=false;if(r.advisoryState==='REFRESH_REQUIRED'&&!Array.isArray(r.eligibilityRefreshReasons))reasonsOk=false;}
 CPST_assert_('statesCanonical',statesOk,'states',results);CPST_assert_('candidateArrays',candidatesOk,'candidates',results);CPST_assert_('staleNeverRecommended',staleGuardOk,'stale guard',results);CPST_assert_('refreshReasonsSurfaced',reasonsOk,'reasons',results);
 var countCheck=smoke&&smoke.totals?(Number(smoke.totals.ready||0)+Number(smoke.totals.refreshRequired||0)+Number(smoke.totals.noCandidates||0)===Number(smoke.totals.audits||0)):false;CPST_assert_('totalsBalance',countCheck,'balance',results);
 var passed=results.filter(function(x){return x.ok;}).length;var out={ok:passed===results.length,build:CONCEPT_PLANNING_TEST_BUILD,total:results.length,passed:passed,failed:results.length-passed,period:p,smokeServerMs:smokeMs,audits:smoke&&smoke.totals?smoke.totals.audits:0,ready:smoke&&smoke.totals?smoke.totals.ready:0,refreshRequired:smoke&&smoke.totals?smoke.totals.refreshRequired:0,noCandidates:smoke&&smoke.totals?smoke.totals.noCandidates:0,refreshPolicy:smoke?smoke.refreshPolicy:null,devPerformance:smoke?smoke.devPerformance||null:null,results:results};Logger.log(JSON.stringify(out,null,2));return out;
}
