/***********************************************************************
 * ConceptReservationCommandService.js
 * BUILD: 2026-09-09_ROADMAP_2_4_CONCEPT_RESERVATION_COMMAND_R2_ACTIVE_PREFIX
 ***********************************************************************/
var CONCEPT_RESERVATION_COMMAND_BUILD='2026-09-09_ROADMAP_2_4_CONCEPT_RESERVATION_COMMAND_R2_ACTIVE_PREFIX';
var CONCEPT_RESERVATION_HEADERS=['Audit ID','Reservation ID','Auditor Email','Auditor Name','Blocks JSON','State','Source Revision','Purpose','Note','Created By','Created At','Updated At','Released By','Released At','Release Reason'];
function CRCS_clean_(v){return String(v==null?'':v).trim();}function CRCS_norm_(v){return CRCS_clean_(v).toLowerCase();}function CRCS_now_(){return Utilities.formatDate(new Date(),Session.getScriptTimeZone(),"yyyy-MM-dd'T'HH:mm:ss");}
function CRCS_sheet_(createIfMissing){var ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName(CONCEPT_RESERVATION_SHEET||'Concept Reservations');if(!sh&&createIfMissing===true){sh=ss.insertSheet(CONCEPT_RESERVATION_SHEET||'Concept Reservations');sh.getRange(1,1,1,CONCEPT_RESERVATION_HEADERS.length).setValues([CONCEPT_RESERVATION_HEADERS]);}return sh;}
function CRCS_headerMap_(sh){if(!sh)return{};var last=Math.max(sh.getLastColumn(),CONCEPT_RESERVATION_HEADERS.length),h=sh.getRange(1,1,1,last).getValues()[0]||[],m={};for(var i=0;i<h.length;i++)m[CRCS_norm_(h[i])]=i+1;return m;}
function CRCS_findRow_(sh,auditId){if(!sh||sh.getLastRow()<2)return 0;var map=CRCS_headerMap_(sh),col=map['audit id'];if(!col)throw new Error('ConceptReservationCommandService: Audit ID column missing');var f=sh.getRange(2,col,sh.getLastRow()-1,1).createTextFinder(auditId).matchEntireCell(true).findNext();return f?f.getRow():0;}
function CRCS_rowValues_(r){return[r.auditId,r.reservationId,r.auditorEmail,r.auditorName,JSON.stringify(r.blocks||[]),r.state,r.sourceRevision,r.purpose||'PRELIMINARY_COMPANY_CONFIRMATION',r.note||'',r.createdBy||'',r.createdAt||'',r.updatedAt||'',r.releasedBy||'',r.releasedAt||'',r.releaseReason||''];}
function CRCS_revisionGuard_(auditId,sourceRevision){var rr=PlanningRevisionTokenService_get({auditId:auditId}),g=PlanningOptimisticRevisionGuard_evaluate({auditId:auditId,expectedRevision:sourceRevision,currentRevision:rr&&rr.revision});return{revision:rr,guard:g};}
function CRCS_activePrefixCount_(sh,map){if(!sh||sh.getLastRow()<2)return 0;var col=map['state'];if(!col)throw new Error('ConceptReservationCommandService: State column missing');var s=sh.getRange(2,col,sh.getLastRow()-1,1).getValues(),n=0;for(var i=0;i<s.length;i++){if(CRCS_clean_(s[i][0]).toUpperCase()!=='ACTIVE')break;n++;}return n;}
function CRCS_moveRow_(sh,fromRow,toRow,width){if(fromRow===toRow)return toRow;var vals=sh.getRange(fromRow,1,1,width).getValues()[0];sh.deleteRow(fromRow);if(fromRow<toRow)toRow--;sh.insertRowBefore(toRow);sh.getRange(toRow,1,1,width).setValues([vals]);return toRow;}
function CRCS_promoteActive_(sh,row){var map=CRCS_headerMap_(sh),active=CRCS_activePrefixCount_(sh,map),target=2+active,width=Math.max(sh.getLastColumn(),CONCEPT_RESERVATION_HEADERS.length);if(row>=target)return CRCS_moveRow_(sh,row,target,width);return row;}
function CRCS_demoteReleased_(sh,row){var map=CRCS_headerMap_(sh),active=CRCS_activePrefixCount_(sh,map),lastActive=1+active,width=Math.max(sh.getLastColumn(),CONCEPT_RESERVATION_HEADERS.length);if(row<=lastActive)return CRCS_moveRow_(sh,row,lastActive+1,width);return row;}
function ConceptReservationCommandService_upsert(input){input=input||{};if(typeof Platform_withLock!=='function')throw new Error('ConceptReservationCommandService: Platform_withLock unavailable');if(typeof PlanningRevisionTokenService_get!=='function'||typeof PlanningOptimisticRevisionGuard_evaluate!=='function')throw new Error('ConceptReservationCommandService: revision dependencies unavailable');var built=ConceptReservationService_build(input),r=built.reservation,now=CRCS_clean_(input.updatedAt||input.createdAt)||CRCS_now_();r.createdAt=CRCS_clean_(input.createdAt)||now;r.updatedAt=now;var dryRun=input.dryRun===true;return Platform_withLock('concept-reservation:'+r.auditId,function(){var rg=CRCS_revisionGuard_(r.auditId,r.sourceRevision);if(!rg.guard||rg.guard.accepted!==true)return{success:true,build:CONCEPT_RESERVATION_COMMAND_BUILD,saved:false,reason:'REVISION_CONFLICT',reservation:r,revision:rg.revision,revisionGuard:rg.guard,meta:{writes:false,dryRun:dryRun}};if(dryRun)return{success:true,build:CONCEPT_RESERVATION_COMMAND_BUILD,saved:false,reason:'DRY_RUN_VALID',reservation:r,revision:rg.revision,revisionGuard:rg.guard,meta:{writes:false,dryRun:true}};var sh=CRCS_sheet_(true),row=CRCS_findRow_(sh,r.auditId),vals=CRCS_rowValues_(r);if(row){sh.getRange(row,1,1,vals.length).setValues([vals]);row=CRCS_promoteActive_(sh,row);}else{var map=CRCS_headerMap_(sh),target=2+CRCS_activePrefixCount_(sh,map);if(target<=sh.getLastRow())sh.insertRowBefore(target);row=target;sh.getRange(row,1,1,vals.length).setValues([vals]);}return{success:true,build:CONCEPT_RESERVATION_COMMAND_BUILD,saved:true,reason:'SAVED',rowNumber:row,reservation:r,revision:rg.revision,revisionGuard:rg.guard,meta:{writes:true,preliminaryOnly:true,activePrefixMaintained:true,finalPlanningWrites:false,availabilityWrites:false,statusWrites:false}};},Math.max(500,Math.min(10000,Number(input.lockWaitMs||3000)||3000)));}
function ConceptReservationCommandService_release(input){input=input||{};var auditId=CRCS_clean_(input.auditId);if(!auditId)throw new Error('ConceptReservationCommandService: auditId required');var dryRun=input.dryRun===true;return Platform_withLock('concept-reservation:'+auditId,function(){var sh=CRCS_sheet_(false);if(!sh)return{success:true,build:CONCEPT_RESERVATION_COMMAND_BUILD,released:false,reason:'NOT_FOUND',meta:{writes:false,dryRun:dryRun}};var row=CRCS_findRow_(sh,auditId);if(!row)return{success:true,build:CONCEPT_RESERVATION_COMMAND_BUILD,released:false,reason:'NOT_FOUND',meta:{writes:false,dryRun:dryRun}};var map=CRCS_headerMap_(sh),now=CRCS_clean_(input.releasedAt)||CRCS_now_();if(dryRun)return{success:true,build:CONCEPT_RESERVATION_COMMAND_BUILD,released:false,reason:'DRY_RUN_VALID',rowNumber:row,meta:{writes:false,dryRun:true}};sh.getRange(row,map['state']).setValue('RELEASED');if(map['released by'])sh.getRange(row,map['released by']).setValue(CRCS_norm_(input.releasedBy));if(map['released at'])sh.getRange(row,map['released at']).setValue(now);if(map['release reason'])sh.getRange(row,map['release reason']).setValue(CRCS_clean_(input.reason||'MANUAL_RELEASE'));if(map['updated at'])sh.getRange(row,map['updated at']).setValue(now);row=CRCS_demoteReleased_(sh,row);return{success:true,build:CONCEPT_RESERVATION_COMMAND_BUILD,released:true,reason:'RELEASED',rowNumber:row,meta:{writes:true,preliminaryOnly:true,activePrefixMaintained:true,finalPlanningWrites:false,availabilityWrites:false,statusWrites:false}};},Math.max(500,Math.min(10000,Number(input.lockWaitMs||3000)||3000)));}
