/***********************************************************************
 * ModelCLifecycleReportingReadModel.js
 * BUILD: 2026-09-23_AMS03_PHASE6_LIFECYCLE_REPORTING_R1
 * Read-only lifecycle/reporting projection over Model C owners.
 ***********************************************************************/
var MODEL_C_LIFECYCLE_REPORTING_BUILD='2026-09-23_AMS03_PHASE6_LIFECYCLE_REPORTING_R1';
function MCLR_clean_(v){return String(v==null?'':v).trim();}
function MCLR_date_(v){if(!v)return'';if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v.getTime()))return Utilities.formatDate(v,Session.getScriptTimeZone(),'yyyy-MM-dd');var s=MCLR_clean_(v),m=s.match(/^(\d{4})[-\/]?(\d{2})[-\/]?(\d{2})/);return m?m[1]+'-'+m[2]+'-'+m[3]:'';}
function MCLR_rows_(sh){if(!sh)return[];var v=sh.getDataRange().getValues();return typeof ModelCMigration_rowsToObjects_==='function'?ModelCMigration_rowsToObjects_(v):[];}
function MCLR_bool_(v){var s=MCLR_clean_(v).toUpperCase();return v===true||v===1||s==='TRUE'||s==='YES'||s==='Y'||s==='1'||s==='X';}
function getModelCLifecycleReportingV5(payload){
 payload=payload||{};var t0=Date.now(),ss=SpreadsheetApp.getActive(),cs=MCLR_rows_(ss.getSheetByName(MODEL_C_SHEETS.COMPANY_SCOPES)),ob=MCLR_rows_(ss.getSheetByName(MODEL_C_SHEETS.AUDIT_OBLIGATIONS)),lk=MCLR_rows_(ss.getSheetByName(MODEL_C_SHEETS.VISIT_OBLIGATIONS)),dep=MCLR_rows_(ss.getSheetByName(MODEL_C_SHEETS.SCOPE_DEPENDENCIES)),scope=MCLR_clean_(payload.scope),company=MCLR_clean_(payload.companyUid),state=MCLR_clean_(payload.state).toUpperCase(),csById={},linksByOb={};
 cs.forEach(function(x){csById[MCLR_clean_(x.Company_Scope_ID)]=x;});
 lk.forEach(function(x){if(MCLR_clean_(x.Link_State).toUpperCase()!=='ACTIVE')return;var id=MCLR_clean_(x.Obligation_ID);if(!id)return;(linksByOb[id]=linksByOb[id]||[]).push(MCLR_clean_(x.Audit_ID));});
 var rows=[],byScope={},byState={};
 ob.forEach(function(x){var c=csById[MCLR_clean_(x.Company_Scope_ID)]||{},sc=MCLR_clean_(x.ScopeCode||c.ScopeCode),uid=MCLR_clean_(x.Company_UID||c.Company_UID),st=MCLR_clean_(x.Obligation_State).toUpperCase();if(scope&&sc!==scope)return;if(company&&uid!==company)return;if(state&&st!==state)return;var recurring=MCLR_clean_(c.Lifecycle_Type).toUpperCase()!=='NON_RECURRING',effective=MCLR_date_(x.Effective_Expiry_Date)||MCLR_date_(x.Base_Expiry_Date),item={obligationId:MCLR_clean_(x.Obligation_ID),companyScopeId:MCLR_clean_(x.Company_Scope_ID),companyUid:uid,scopeCode:sc,activeCompanyScope:MCLR_bool_(c.Active),lifecycleType:MCLR_clean_(c.Lifecycle_Type),recurring:recurring,certificateBirthday:MCLR_date_(c.Certificate_Birthday),cycleKey:MCLR_clean_(x.Cycle_Key),state:st,baseExpiryDate:MCLR_date_(x.Base_Expiry_Date),extensionApplied:MCLR_bool_(x.Extension_Applied),effectiveExpiryDate:effective,planningWindowFrom:MCLR_date_(x.Planning_Window_From),planningWindowTo:MCLR_date_(x.Planning_Window_To),formalHours:Number(x.Formal_Hours||0)||0,auditIds:(linksByOb[MCLR_clean_(x.Obligation_ID)]||[]).filter(Boolean).sort()};rows.push(item);byScope[sc]=(byScope[sc]||0)+1;byState[st]=(byState[st]||0)+1;});
 rows.sort(function(a,b){return(a.effectiveExpiryDate||'9999').localeCompare(b.effectiveExpiryDate||'9999')||a.scopeCode.localeCompare(b.scopeCode)||a.obligationId.localeCompare(b.obligationId);});
 var shared=dep.filter(function(d){return MCLR_bool_(d.Active)&&MCLR_bool_(d.Share_Expiry);}).map(function(d){return{parentScopeCode:MCLR_clean_(d.Parent_ScopeCode),childScopeCode:MCLR_clean_(d.Child_ScopeCode),relationshipType:MCLR_clean_(d.Relationship_Type),mustAuditTogether:MCLR_bool_(d.Must_Audit_Together),shareExpiry:true};});
 return{success:true,build:MODEL_C_LIFECYCLE_REPORTING_BUILD,filters:{scope:scope,companyUid:company,state:state},rows:rows,summary:{obligations:rows.length,companyScopes:cs.length,activeVisitLinks:lk.filter(function(x){return MCLR_clean_(x.Link_State).toUpperCase()==='ACTIVE';}).length,byScope:byScope,byState:byState,sharedExpiryDependencies:shared.length},sharedExpiryDependencies:shared,meta:{readOnly:true,writes:false,newSsot:false,companyScopeOwner:'Company_Scopes',obligationOwner:'Audit_Obligations',visitLinkOwner:'Audit_Visit_Obligations',dependencyOwner:'Config_Scope_Dependencies',legacyAuditPlanningProjectionOnly:true,totalMs:Date.now()-t0}};
}
