/***********************************************************************
 * PlanningWorkspaceSelfPlanningService.js
 * BUILD: 2026-09-10_PLANNING_WORKSPACE_SELF_PLANNING_R2_ADVISORY_FILTER
 *
 * PURPOSE
 *   Reuse existing auditor self-planning entitlement while routing the final
 *   planning write through the canonical Planning Workspace commit path.
 ***********************************************************************/
var PLANNING_WORKSPACE_SELF_PLANNING_BUILD='2026-09-10_PLANNING_WORKSPACE_SELF_PLANNING_R2_ADVISORY_FILTER';
function PWSP_clean_(v){return String(v==null?'':v).trim();}
function PWSP_email_(v){return PWSP_clean_(v).toLowerCase();}
function PWSP_activeEmail_(){var e='';if(typeof auditorV5_getActiveEmail_==='function')e=auditorV5_getActiveEmail_();if(!e){try{e=Session.getActiveUser().getEmail()||'';}catch(x){}}return PWSP_email_(e);}
function PWSP_grid_(){if(typeof AuditorV5B_GetAuditorGrid_U20409!=='function')throw new Error('PlanningWorkspaceSelfPlanningService: auditor grid unavailable');var email=PWSP_activeEmail_();if(!email)throw new Error('PlanningWorkspaceSelfPlanningService: active auditor email unavailable');var out=AuditorV5B_GetAuditorGrid_U20409({view:'active',auditorEmail:email,noCache:false});if(!out||out.success===false)throw new Error('PlanningWorkspaceSelfPlanningService: auditor grid load failed');return{email:email,rows:Array.isArray(out.rows)?out.rows:[]};}
function PWSP_findCanPlan_(auditId){auditId=PWSP_clean_(auditId);var g=PWSP_grid_(),row=null;for(var i=0;i<g.rows.length;i++){var r=g.rows[i]||{};if(PWSP_clean_(r.auditId)===auditId){row=r;break;}}if(!row)return{ok:false,reason:'AUDIT_NOT_VISIBLE_TO_ACTIVE_AUDITOR',auditorEmail:g.email,row:null};if(row.canPlan!==true)return{ok:false,reason:'SELF_PLANNING_NOT_ALLOWED',auditorEmail:g.email,row:row};return{ok:true,reason:'OK',auditorEmail:g.email,row:row};}
function PlanningWorkspaceSelfPlanningService_getAdvisory(input){input=input||{};var g=PWSP_grid_(),allowed={};g.rows.forEach(function(r){if(r&&r.canPlan===true&&PWSP_clean_(r.auditId))allowed[PWSP_clean_(r.auditId)]=true;});var advisory=ConceptPlanningService_get(input)||{};var rows=Array.isArray(advisory.rows)?advisory.rows:[];advisory.rows=rows.filter(function(r){return !!allowed[PWSP_clean_(r&&r.auditId)];});advisory.meta=advisory.meta||{};advisory.meta.selfPlanningFiltered=true;advisory.meta.activeAuditorEmail=g.email;advisory.meta.entitlementOwner='AuditorV5B_GetAuditorGrid_U20409.canPlan';advisory.meta.originalRowCount=rows.length;advisory.meta.filteredRowCount=advisory.rows.length;return advisory;}
function PlanningWorkspaceSelfPlanningService_context(input){input=input||{};var auditId=PWSP_clean_(input.auditId),auth=PWSP_findCanPlan_(auditId);return{success:true,build:PLANNING_WORKSPACE_SELF_PLANNING_BUILD,auditId:auditId,canSelfPlan:auth.ok===true,reason:auth.reason,auditorEmail:auth.auditorEmail,row:auth.row||null,meta:{readOnly:true,identityOwner:'ACTIVE_SESSION',entitlementOwner:'AuditorV5B_GetAuditorGrid_U20409.canPlan',existingAuditorPortalPreserved:true,newSsot:false}};}
function PlanningWorkspaceSelfPlanningService_evaluate(input){input=input||{};var auditId=PWSP_clean_(input.auditId),expected=PWSP_clean_(input.expectedRevision);if(!auditId)throw new Error('PlanningWorkspaceSelfPlanningService: auditId required');if(!expected)throw new Error('PlanningWorkspaceSelfPlanningService: expectedRevision required');if(!Array.isArray(input.blocks)||!input.blocks.length)throw new Error('PlanningWorkspaceSelfPlanningService: blocks required');var auth=PWSP_findCanPlan_(auditId);if(!auth.ok)return{success:true,canCommit:false,reason:auth.reason,auditorEmail:auth.auditorEmail};var gate=PlanningCommitGateService_evaluate({auditId:auditId,expectedRevision:expected,auditorEmail:auth.auditorEmail,auditorName:PWSP_clean_(auth.row&&auth.row.auditorName)||auth.auditorEmail,blocks:input.blocks,waiverAccepted:false,actorRole:'AUDITOR',lockWaitMs:input.lockWaitMs});return{success:true,canCommit:gate&&gate.canCommit===true,reason:gate&&gate.canCommit===true?'READY':gate&&gate.reason||'COMMIT_BLOCKED',auditorEmail:auth.auditorEmail,gate:gate||null,meta:{readOnly:true,actorRole:'AUDITOR',identityPinnedToSession:true}};}
function PlanningWorkspaceSelfPlanningService_commit(input){input=input||{};var auditId=PWSP_clean_(input.auditId),expected=PWSP_clean_(input.expectedRevision);if(!auditId)throw new Error('PlanningWorkspaceSelfPlanningService: auditId required');if(!expected)throw new Error('PlanningWorkspaceSelfPlanningService: expectedRevision required');if(!Array.isArray(input.blocks)||!input.blocks.length)throw new Error('PlanningWorkspaceSelfPlanningService: blocks required');var auth=PWSP_findCanPlan_(auditId);if(!auth.ok)return{success:true,committed:false,reason:auth.reason,auditorEmail:auth.auditorEmail};var result=PlanningCanonicalCommitService_commit({auditId:auditId,expectedRevision:expected,auditorEmail:auth.auditorEmail,auditorName:PWSP_clean_(auth.row&&auth.row.auditorName)||auth.auditorEmail,blocks:input.blocks,waiverAccepted:false,actorRole:'AUDITOR',actorEmail:auth.auditorEmail,allowWeekendOverride:input.allowWeekendOverride!==false,lockWaitMs:input.lockWaitMs});if(result&&result.committed===true){result.meta=result.meta||{};result.meta.selfPlanning=true;result.meta.activeAuditorPinned=true;result.meta.expectedStatusAfterCommit='Pending Approval';result.meta.existingAuditorPortalPreserved=true;}return result;}
function PlanningWorkspaceSelfPlanningService_contract(){return{build:PLANNING_WORKSPACE_SELF_PLANNING_BUILD,identityOwner:'ACTIVE_SESSION',entitlementOwner:'AuditorV5B_GetAuditorGrid_U20409.canPlan',advisoryOwner:'ConceptPlanningService_get filtered by existing canPlan entitlement',commitOwner:'PlanningCanonicalCommitService',actorRole:'AUDITOR',statusRule:'PENDING_PLANNING_TO_PENDING_APPROVAL',browserMayChooseAuditor:false,serverFiltersDemand:true,existingAuditorPortalPreserved:true,newSsot:false};}
