/***********************************************************************
 * PlanningWorkspacePlannedAuditActionsTests.js
 * BUILD: 2026-09-13_WORKSPACE_PLANNED_AUDIT_ACTIONS_TESTS_R3_ACCEPTED_REACCEPT
 ***********************************************************************/
var PLANNING_WORKSPACE_PLANNED_AUDIT_ACTIONS_TEST_BUILD='2026-09-13_WORKSPACE_PLANNED_AUDIT_ACTIONS_TESTS_R3_ACCEPTED_REACCEPT';
function RUN_PLANNING_WORKSPACE_PLANNED_AUDIT_ACTIONS_REGRESSION(){
  var r=[];function t(n,o,d){r.push({name:n,ok:!!o,detail:o?'':String(d||'failed')});}
  var ui=PlanningWorkspaceUi_contract(),rpc=PlanningWorkspaceRpc_contract(),svc=PlanningWorkspaceService_contract(),src=HtmlService.createHtmlOutputFromFile('PlanningWorkspacePlannedAuditActions.js').getContent(),readSrc=String(PlanningWorkspacePlannedAuditReadService_get),modifySrc=String(PlanningCanonicalModifyService_modify)+String(PCMOD_transition_)+String(PCMOD_notifyReaccept_);
  t('plannedActionsIncluded',ui.plannedActionsInclude==='PlanningWorkspacePlannedAuditActions.js',ui.plannedActionsInclude);t('clientOnly',ui.plannedActionsClientOnly===true);t('noBootstrapReadCost',ui.plannedDetailOnDemand===true&&rpc.meta.plannedDetailOnDemand===true);t('detailRpcPresent',rpc.endpoints.indexOf('PlanningWorkspaceRpc_getPlannedAudit')>=0);t('modifyRpcPresent',rpc.endpoints.indexOf('PlanningWorkspaceRpc_modifyPlanned')>=0);t('cancelRpcPresent',rpc.endpoints.indexOf('PlanningWorkspaceRpc_cancelPlanned')>=0);t('detailServiceOwner',svc.endpoints.plannedDetail==='PlanningWorkspacePlannedAuditReadService_get',svc.endpoints.plannedDetail);t('detailUsesRevisionOwner',readSrc.indexOf('PlanningRevisionTokenService_get')>=0);t('detailReadOnly',readSrc.indexOf('writes:false')>=0&&readSrc.indexOf('readOnly:true')>=0);t('plannedCardsUseExistingOverlay',src.indexOf('o.availability&&o.availability.byAuditorEmail')>=0&&src.indexOf('slot.auditRef')>=0);t('plannedCardsNoExtraListRpc',String(src.match(/function enhance\(\)[\s\S]*?function schedule/)||'').indexOf('google.script.run')<0);t('modifyAction',src.indexOf("button('Modify'")>=0&&src.indexOf('openModify(id)')>=0);t('cancelAction',src.indexOf("button('Cancel'")>=0&&src.indexOf('openCancel(id)')>=0);
  t('acceptedModifyEnabled',readSrc.indexOf("normalized==='ACCEPTED'")>=0&&readSrc.indexOf('acceptedModifyAllowed:true')>=0);t('acceptedWarningVisible',src.indexOf('withdraws the previous acceptance')>=0&&src.indexOf('must Accept again')>=0);t('acceptedMovesToApproved',modifySrc.indexOf("s==='ACCEPTED'?'APPROVED':s")>=0);t('acceptedRequiresReacceptance',modifySrc.indexOf("reaccept=status==='ACCEPTED'")>=0&&modifySrc.indexOf('reacceptanceRequired:reaccept')>=0);t('acceptedNotificationUsesCanonicalEvent',modifySrc.indexOf("'AUDIT_PLANNED_BY_MANAGER'")>=0&&modifySrc.indexOf('StatusNotificationBridge_QueueWithLock_')>=0);t('acceptedNotificationUsesFreshBriefing',modifySrc.indexOf('StatusNotificationBridge_LoadEcasAuditBriefing_')>=0);t('notificationFailureDoesNotRollback',modifySrc.indexOf('notificationFailureDoesNotRollbackLifecycle:true')>=0);
  t('modifySameAuditorNoSelector',src.indexOf('auditorEmail:detail.auditorEmail')>=0);t('modifyEditableBlocks',src.indexOf("field('Date','date'")>=0&&src.indexOf("field('Start','time'")>=0&&src.indexOf("field('End','time'")>=0);t('modifyCanAddRemoveBlocks',src.indexOf("button('Add block'")>=0&&src.indexOf("button('Remove'")>=0);t('modifyUsesRevision',src.indexOf('expectedRevision:detail.revision')>=0);t('cancelReasonRequiredClient',src.indexOf('A cancel reason is required.')>=0);t('cancelUsesRevision',src.indexOf('expectedRevision:detail.revision')>=0&&src.indexOf('reason:why')>=0);t('cancelExplainsPendingPlanning',src.indexOf('returns the audit to Pending Planning')>=0);t('refreshAfterModifyCancel',src.indexOf("c.load('load')")>=0);t('modifyUsesLoadedAvailability',src.indexOf('function occupiedSlots(')>=0&&src.indexOf('records(email,date)')>=0);t('knownOverlapDetectedClientSide',src.indexOf('function firstKnownConflict(')>=0&&src.indexOf('function overlaps(')>=0);t('secondAuditNonOverlapExplained',src.indexOf('A second audit is allowed when times do not overlap.')>=0);t('knownOverlapBlocksSaveBeforeRpc',src.indexOf("toast('Blocked: selected time overlaps '")>=0);t('finalCanonicalValidationRetained',src.indexOf('Final canonical validation still runs on Save.')>=0);t('availabilityContextNoExtraRpc',String(src.match(/function renderAvailabilityContext\([\s\S]*?function openModify/)||'').indexOf('google.script.run')<0);t('noDirectSheetAccess',src.indexOf('SpreadsheetApp')<0&&readSrc.indexOf('setValue(')<0&&readSrc.indexOf('setValues(')<0);t('noNewSsot',readSrc.indexOf('newSsot:false')>=0&&rpc.meta.newSsot===false&&svc.meta.newSsot===false);
  var failed=r.filter(function(x){return!x.ok;}).length,out={ok:failed===0,build:PLANNING_WORKSPACE_PLANNED_AUDIT_ACTIONS_TEST_BUILD,total:r.length,passed:r.length-failed,failed:failed,results:r,meta:{nonDestructive:true,contractOnly:true,liveReadsPerformed:false,liveWritesPerformed:false,modify:'Pending Approval/Approved preserve status. Accepted reschedule becomes Approved and requires auditor re-acceptance.',notification:'Accepted reschedule reuses canonical AUDIT_PLANNED_BY_MANAGER queue event with fresh post-write briefing.',cancel:'Browser-proven: canonical CANCEL returns audit to Pending Planning.'}};console.log(JSON.stringify(out,null,2));return out;
}
