/***********************************************************************
 * PlanningWorkspacePlannedAuditActionsTests.js
 * BUILD: 2026-09-14_WORKSPACE_PLANNED_AUDIT_ACTIONS_TESTS_R7_MONDAY_GATE_REASON
 ***********************************************************************/
var PLANNING_WORKSPACE_PLANNED_AUDIT_ACTIONS_TEST_BUILD='2026-09-14_WORKSPACE_PLANNED_AUDIT_ACTIONS_TESTS_R7_MONDAY_GATE_REASON';
function RUN_PLANNING_WORKSPACE_PLANNED_AUDIT_ACTIONS_REGRESSION(){
  var r=[];function t(n,o,d){r.push({name:n,ok:!!o,detail:o?'':String(d||'failed')});}
  var ui=PlanningWorkspaceUi_contract(),rpc=PlanningWorkspaceRpc_contract(),svc=PlanningWorkspaceService_contract(),src=HtmlService.createHtmlOutputFromFile('PlanningWorkspacePlannedAuditActions.js').getContent(),dragSrc=HtmlService.createHtmlOutputFromFile('PlanningWorkspaceDragDrop.js').getContent(),readSrc=String(PlanningWorkspacePlannedAuditReadService_get),modifySrc=String(PlanningCanonicalModifyService_modify)+String(PCMOD_transition_)+String(PCMOD_notifyReaccept_)+String(PCMOD_failure_),writerValidateSrc=String(PlanningCanonicalRowWriter_validate),writerExecuteSrc=String(PlanningCanonicalRowWriter_execute);
  t('plannedActionsIncluded',ui.plannedActionsInclude==='PlanningWorkspacePlannedAuditActions.js',ui.plannedActionsInclude);t('clientOnly',ui.plannedActionsClientOnly===true);t('detailRpcStillAvailableFallback',rpc.endpoints.indexOf('PlanningWorkspaceRpc_getPlannedAudit')>=0);t('modifyRpcPresent',rpc.endpoints.indexOf('PlanningWorkspaceRpc_modifyPlanned')>=0);t('cancelRpcPresent',rpc.endpoints.indexOf('PlanningWorkspaceRpc_cancelPlanned')>=0);t('detailServiceOwner',svc.endpoints.plannedDetail==='PlanningWorkspacePlannedAuditReadService_get',svc.endpoints.plannedDetail);t('detailUsesRevisionOwner',readSrc.indexOf('PlanningRevisionTokenService_get')>=0);t('detailReadOnly',readSrc.indexOf('writes:false')>=0&&readSrc.indexOf('readOnly:true')>=0);
  t('plannedCardsUseExistingOverlay',src.indexOf('o.availability&&o.availability.byAuditorEmail')>=0&&src.indexOf('slot.auditRef')>=0);t('localDetailPresent',src.indexOf('function localDetail(')>=0);t('openModifyNoDetailRpc',String(src.match(/function openModify\([\s\S]*?function openCancel/)||'').indexOf('PlanningWorkspaceRpc_getPlannedAudit')<0);t('openCancelNoDetailRpc',String(src.match(/function openCancel\([\s\S]*?function renderCard/)||'').indexOf('PlanningWorkspaceRpc_getPlannedAudit')<0);t('modifyRevisionHydratedServerSide',src.indexOf('PlanningWorkspaceRpc_modifyPlanned({auditId:detail.auditId,auditorEmail:detail.auditorEmail')>=0&&rpc.meta.plannedCommandRevisionHydration===true);t('cancelRevisionHydratedServerSide',src.indexOf('PlanningWorkspaceRpc_cancelPlanned({auditId:detail.auditId,reason:why})')>=0&&rpc.meta.plannedCommandRevisionHydration===true);
  t('acceptedModifyEnabled',readSrc.indexOf("normalized==='ACCEPTED'")>=0&&readSrc.indexOf('acceptedModifyAllowed:true')>=0);t('acceptedWarningVisible',src.indexOf('withdraws the previous acceptance')>=0&&src.indexOf('must Accept again')>=0);t('acceptedMovesToApproved',modifySrc.indexOf("s==='ACCEPTED'?'APPROVED':s")>=0);t('acceptedRequiresReacceptance',modifySrc.indexOf("reaccept=status==='ACCEPTED'")>=0&&modifySrc.indexOf('reacceptanceRequired:reaccept')>=0);t('acceptedNotificationUsesCanonicalEvent',modifySrc.indexOf("'AUDIT_PLANNED_BY_MANAGER'")>=0&&modifySrc.indexOf('StatusNotificationBridge_QueueWithLock_')>=0);t('acceptedNotificationUsesFreshBriefing',modifySrc.indexOf('StatusNotificationBridge_LoadEcasAuditBriefing_')>=0);t('notificationFailureDoesNotRollback',modifySrc.indexOf('notificationFailureDoesNotRollbackLifecycle:true')>=0);
  t('modifySameAuditorNoSelector',src.indexOf('auditorEmail:detail.auditorEmail')>=0);t('modifyEditableBlocks',src.indexOf("field('Date','date'")>=0&&src.indexOf("field('Start','time'")>=0&&src.indexOf("field('End','time'")>=0);t('modifyCanAddRemoveBlocks',src.indexOf("button('Add block'")>=0&&src.indexOf("button('Remove'")>=0);t('availabilityPickerPresent',src.indexOf('function renderAvailabilityPicker(')>=0&&src.indexOf('Auditor availability — click a date')>=0);t('pickerUsesLoadedOverlayOnly',String(src.match(/function renderAvailabilityPicker\([\s\S]*?function ensureCalendarStyle/)||'').indexOf('google.script.run')<0);t('pickerShowsOccupied',src.indexOf('occupied but second audit may fit')>=0);t('calendarOccupiedVisual',src.indexOf('pw-day-occupied')>=0&&src.indexOf('decorateCells')>=0);t('calendarWeekendVisual',src.indexOf('pw-weekend-soft')>=0);t('weekendSoftModify',src.indexOf('Weekend selected: soft warning only')>=0);t('weekendSoftDragDrop',dragSrc.indexOf("return{level:'WARNING',reason:'Weekend/default availability is a soft warning")>=0);t('weekendNotSkippedInMultiday',dragSrc.indexOf('!isWeekend(date)&&withinWindow')<0);t('explicitUnavailableStillHard',dragSrc.indexOf("return{level:'BLOCK',reason:'Auditor is explicitly unavailable on this date.'}")>=0);
  t('cancelReasonRequiredClient',src.indexOf('A cancel reason is required.')>=0);t('cancelExplainsPendingPlanning',src.indexOf('returns the audit to Pending Planning')>=0);t('refreshAfterModifyCancel',src.indexOf("c.load('load')")>=0);t('modifyUsesLoadedAvailability',src.indexOf('function occupiedSlots(')>=0&&src.indexOf('records(email,date)')>=0);t('knownOverlapDetectedClientSide',src.indexOf('function firstKnownConflict(')>=0&&src.indexOf('function overlaps(')>=0);t('secondAuditNonOverlapExplained',src.indexOf('A second audit is allowed when times do not overlap.')>=0);t('knownOverlapBlocksSaveBeforeRpc',src.indexOf("toast('Blocked: selected time overlaps '")>=0);t('finalCanonicalValidationRetained',src.indexOf('Final canonical validation still runs on Save.')>=0||src.indexOf('canonical validation still runs')>=0);t('availabilityContextNoExtraRpc',String(src.match(/function renderAvailabilityContext\([\s\S]*?function failureMessage/)||'').indexOf('google.script.run')<0);t('dragObserverNarrow',dragSrc.indexOf("observe(cal,{childList:true})")>=0&&dragSrc.indexOf("observe(att,{childList:true})")>=0&&dragSrc.indexOf("subtree:true")<0);t('noDirectSheetAccess',src.indexOf('SpreadsheetApp')<0&&dragSrc.indexOf('SpreadsheetApp')<0&&readSrc.indexOf('setValue(')<0&&readSrc.indexOf('setValues(')<0);t('noNewSsot',readSrc.indexOf('newSsot:false')>=0&&rpc.meta.newSsot===false&&svc.meta.newSsot===false);

  t('writerReadOnlyValidationPresent',writerValidateSrc.indexOf('PLANNED_HOURS_BELOW_REQUIRED')>=0&&writerValidateSrc.indexOf('plannedHours')>=0&&writerValidateSrc.indexOf('requiredHours')>=0);
  t('writerExecuteSupportsPrevalidated',writerExecuteSrc.indexOf('opts.prevalidated')>=0);
  t('modifyPrevalidatesBeforeAvailability',modifySrc.indexOf('PlanningCanonicalRowWriter_validate')>=0&&modifySrc.indexOf('PlanningCanonicalRowWriter_validate')<modifySrc.indexOf('PlanningCanonicalAvailabilityAdapter_release'));
  t('modifyValidationFailureNoAvailabilityWrite',modifySrc.indexOf('availabilityMutated:false')>=0&&modifySrc.indexOf('validatedBeforeAvailability:true')>=0);
  t('modifyPropagatesConcreteFailure',modifySrc.indexOf('validation&&validation.message')>=0&&modifySrc.indexOf('plannedHours:validation&&validation.plannedHours')>=0&&modifySrc.indexOf('requiredHours:validation&&validation.requiredHours')>=0);
  t('multiBlockPickerUsesActiveBlock',src.indexOf('function activeDateInput(')>=0&&src.indexOf('pw-active-block')>=0&&src.indexOf('highlighted block')>=0);
  t('plannedHoursVisibleClientSide',src.indexOf('function plannedHours(')>=0&&src.indexOf("'Planned: '+h+' h. '")>=0);
  t('detailedModifyFailureVisible',src.indexOf('function failureMessage(')>=0&&src.indexOf('d.validation&&clean(d.validation.message)')>=0);
  t('pickerStartsOnMonday',src.indexOf('function mondayStart(')>=0&&src.indexOf('start=mondayStart(anchor)')>=0);
  t('gateHardBlockReasonVisible',src.indexOf('d.gate&&d.gate.preflight&&d.gate.preflight.validatorResult')>=0&&src.indexOf("normStatus(verdicts[i]&&verdicts[i].level)==='HARD_BLOCK'")>=0);

  var failed=r.filter(function(x){return!x.ok;}).length,out={ok:failed===0,build:PLANNING_WORKSPACE_PLANNED_AUDIT_ACTIONS_TEST_BUILD,total:r.length,passed:r.length-failed,failed:failed,results:r,meta:{nonDestructive:true,contractOnly:true,liveReadsPerformed:false,liveWritesPerformed:false,performance:'Modify/Cancel open and availability picker use loaded overlay; drag/drop observers narrowed.',availability:'Modify shows 35-day loaded availability with occupied/free/weekend/unavailable states.',weekend:'Weekend/default availability is soft warning; explicit unavailability remains hard block.',modify:'Accepted reschedule becomes Approved; row rules prevalidate before Availability mutation; picker weeks start Monday; concrete canonical hard-block reason is surfaced.'}};console.log(JSON.stringify(out,null,2));return out;
}
