/***********************************************************************
 * PlanningWorkspaceBulkCanonicalPlanningService.js
 * BUILD: 2026-09-10_PLANNING_WORKSPACE_BULK_CANONICAL_SERVICE_R1
 *
 * Safe batch wrapper around the existing canonical single-audit commit owner.
 * - PREVIEW validates every selected audit through PlanningCommitGateService.
 * - COMMIT is allowed only when every selected audit passes a fresh preflight.
 * - Canonical writes remain owned by PlanningCanonicalCommitService.
 * - Cross-audit rollback is intentionally NOT invented. Unexpected runtime
 *   partial success is returned loudly as PARTIAL_COMMIT_REQUIRES_REVIEW.
 ***********************************************************************/
var PLANNING_WORKSPACE_BULK_CANONICAL_SERVICE_BUILD='2026-09-10_PLANNING_WORKSPACE_BULK_CANONICAL_SERVICE_R1';
function PWBC_clean_(v){return String(v==null?'':v).trim();}
function PWBC_items_(input){var src=input&&Array.isArray(input.items)?input.items:[];if(!src.length)throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: items required');if(src.length>25)throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: maximum 25 items per batch');var seen={};return src.map(function(x){x=x||{};var id=PWBC_clean_(x.auditId),rev=PWBC_clean_(x.expectedRevision||x.sourceRevision),email=PWBC_clean_(x.auditorEmail).toLowerCase();if(!id)throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: auditId required');if(seen[id])throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: duplicate auditId '+id);seen[id]=1;if(!rev)throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: expectedRevision required for '+id);if(!email)throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: auditorEmail required for '+id);if(!Array.isArray(x.blocks)||!x.blocks.length)throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: blocks required for '+id);return{auditId:id,expectedRevision:rev,auditorEmail:email,auditorName:PWBC_clean_(x.auditorName),blocks:x.blocks,waiverAccepted:x.waiverAccepted===true,actorRole:'MANAGER',actorEmail:PWBC_clean_(x.actorEmail||input.actorEmail||''),allowWeekendOverride:x.allowWeekendOverride!==false,lockWaitMs:x.lockWaitMs};});}
function PWBC_previewOne_(x){var g=PlanningCommitGateService_evaluate({auditId:x.auditId,expectedRevision:x.expectedRevision,auditorEmail:x.auditorEmail,auditorName:x.auditorName,blocks:x.blocks,waiverAccepted:x.waiverAccepted===true,actorRole:'MANAGER',lockWaitMs:x.lockWaitMs});return{auditId:x.auditId,ok:!!(g&&g.canCommit===true),reason:g&&g.reason||'GATE_FAILED',overallLevel:g&&g.preflight&&g.preflight.overallLevel||g&&g.overallLevel||'',requiresWaiver:!!(g&&g.preflight&&g.preflight.requiresWaiver),gate:g||null};}
function PWBC_preview_(items){var out=[];for(var i=0;i<items.length;i++)out.push(PWBC_previewOne_(items[i]));return out;}
function PlanningWorkspaceBulkCanonicalPlanningService_preview(input){if(typeof PlanningCommitGateService_evaluate!=='function')throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: PlanningCommitGateService_evaluate unavailable');var items=PWBC_items_(input||{}),preview=PWBC_preview_(items),blocked=preview.filter(function(x){return!x.ok;});return{success:true,build:PLANNING_WORKSPACE_BULK_CANONICAL_SERVICE_BUILD,canCommit:blocked.length===0,reason:blocked.length?'BATCH_PREFLIGHT_BLOCKED':'BATCH_PREFLIGHT_ACCEPTED',preview:preview,meta:{writes:false,requested:items.length,accepted:preview.length-blocked.length,blocked:blocked.length,allMustPass:true,applyOkOnly:false,preflightOwner:'PlanningCommitGateService',commitOwner:'PlanningCanonicalCommitService',canonicalWrites:false,newSsot:false}};}
function PlanningWorkspaceBulkCanonicalPlanningService_commit(input){input=input||{};if(input.confirmCanonicalBatchCommit!==true)throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: explicit batch confirmation required');if(typeof PlanningCanonicalCommitService_commit!=='function')throw new Error('PlanningWorkspaceBulkCanonicalPlanningService: PlanningCanonicalCommitService_commit unavailable');var items=PWBC_items_(input),pre=PWBC_preview_(items),blocked=pre.filter(function(x){return!x.ok;});if(blocked.length)return{success:true,build:PLANNING_WORKSPACE_BULK_CANONICAL_SERVICE_BUILD,committed:false,reason:'BATCH_PREFLIGHT_BLOCKED',preview:pre,results:[],meta:{writes:false,requested:items.length,committedCount:0,blocked:blocked.length,allMustPass:true,partialCommit:false,commitOwner:'PlanningCanonicalCommitService',newSsot:false}};var results=[],committedCount=0,failure=null;for(var i=0;i<items.length;i++){var x=items[i],r;try{r=PlanningCanonicalCommitService_commit(x);}catch(e){r={success:false,committed:false,reason:String(e&&e.message||e)};}var ok=!!(r&&r.success===true&&r.committed===true);results.push({auditId:x.auditId,committed:ok,reason:r&&r.reason||'COMMIT_FAILED',newRevision:r&&r.newRevision||'',writeResult:r&&r.writeResult||null,repairRequired:!!(r&&r.meta&&(r.meta.availabilityRepairRequired||r.meta.reservationReleaseRepairRequired))});if(ok){committedCount++;continue;}failure={auditId:x.auditId,index:i,reason:r&&r.reason||'COMMIT_FAILED'};break;}var all=committedCount===items.length;if(all)return{success:true,build:PLANNING_WORKSPACE_BULK_CANONICAL_SERVICE_BUILD,committed:true,reason:'BATCH_COMMITTED',preview:pre,results:results,meta:{writes:true,requested:items.length,committedCount:committedCount,allMustPass:true,partialCommit:false,commitOwner:'PlanningCanonicalCommitService',statusOwner:'StatusMachine',availabilityOwner:'AvailabilityService via canonical commit',newSsot:false}};var remaining=items.slice(results.length).map(function(x){return x.auditId;});return{success:false,build:PLANNING_WORKSPACE_BULK_CANONICAL_SERVICE_BUILD,committed:false,reason:committedCount>0?'PARTIAL_COMMIT_REQUIRES_REVIEW':'BATCH_COMMIT_FAILED',preview:pre,results:results,failure:failure,remainingAuditIds:remaining,meta:{writes:committedCount>0,requested:items.length,committedCount:committedCount,allMustPass:true,partialCommit:committedCount>0,partialCommitExplicit:true,silentPartialSuccess:false,crossAuditRollbackInvented:false,commitOwner:'PlanningCanonicalCommitService',statusOwner:'StatusMachine',availabilityOwner:'AvailabilityService via canonical commit',newSsot:false}};}
function PlanningWorkspaceBulkCanonicalPlanningService_contract(){return{build:PLANNING_WORKSPACE_BULK_CANONICAL_SERVICE_BUILD,maxItems:25,previewOwner:'PlanningCommitGateService',commitOwner:'PlanningCanonicalCommitService',allMustPassBeforeWrite:true,applyOkOnly:false,partialCommitExplicit:true,silentPartialSuccess:false,crossAuditRollbackInvented:false,newSsot:false};}
