/***********************************************************************
 * PlanningCanonicalRowWriter.js
 * BUILD: 2026-09-09_ROADMAP_2_4_CANONICAL_ROW_WRITER_R1
 *
 * Canonical commit write boundary after Availability has already been
 * reserved by PlanningCanonicalAvailabilityAdapter. This writer owns only
 * the Audit planning row mutation and never touches Availability.
 ***********************************************************************/
var PLANNING_CANONICAL_ROW_WRITER_BUILD='2026-09-09_ROADMAP_2_4_CANONICAL_ROW_WRITER_R1';
function PlanningCanonicalRowWriter_execute(rowInfo,transition,opts){opts=opts||{};var nb=normalizeBlocks_(opts.blocks||[]);if(nb.hard.length)return failHard_(nb.hard);var blocksN=nb.blocks,reqH=Number(rowInfo.requiredHours||0),sumH=blocksN.reduce(function(a,b){return a+b.hours;},0);if(sumH<reqH)return failHard_([{date:null,reason:'Planned hours < required hours'}]);var auditorOwner=String(opts.auditorEmail||opts.auditorName||'').trim();if(!auditorOwner)return fail_('Missing auditor owner for planning');var hard=checkHardConflicts_(rowInfo.ctx,rowInfo,blocksN,auditorOwner,opts.auditId);if(hard.length)return failHard_(hard);var softObj=checkSoftConflicts_(rowInfo.ctx,rowInfo,blocksN,auditorOwner,{allowWeekend:opts.allowWeekend!==false});if(softObj.hard.length)return failHard_(softObj.hard);var planningJson={blocks:blocksN,totalPlannedHours:sumH,auditorEmail:opts.auditorEmail||'',auditorName:opts.auditorName||''},row=rowInfo.row.slice();while(row.length<rowInfo.ctx.hdr.length)row.push('');if(rowInfo.ctx.colJson>0)row[rowInfo.ctx.colJson-1]=JSON.stringify(planningJson);if(rowInfo.ctx.colAssigned>0)row[rowInfo.ctx.colAssigned-1]=auditorOwner;if(rowInfo.ctx.colDatePlanned>0)row[rowInfo.ctx.colDatePlanned-1]=blocksN[0].date;if(rowInfo.ctx.colStatus>0)row[rowInfo.ctx.colStatus-1]=transition.afterStatusDisplay;rowInfo.ctx.sh.getRange(rowInfo.rowIndex,1,1,row.length).setValues([row]);Planning_invalidate_();return{success:true,code:'OK',action:opts.isReschedule?'RESCHEDULE':'PLAN',auditId:String(opts.auditId||'').trim(),beforeStatus:transition.beforeStatus,beforeStatusDisplay:transition.beforeStatusDisplay,newStatus:transition.afterStatusDisplay,afterStatus:transition.afterStatus,afterStatusDisplay:transition.afterStatusDisplay,planningJson:JSON.stringify(planningJson),plannedDate:blocksN[0].date,plannedDates:blocksN.map(function(b){return b.date;}),assignedTo:auditorOwner,hoursPlanned:sumH,requiredHours:reqH,softConflicts:softObj.soft,hardConflicts:[],meta:{availabilityWrites:false,canonicalAvailabilityHandledBy:'PlanningCanonicalAvailabilityAdapter'}};}
