/***********************************************************************
 * PlanningWorkspaceService.js
 * BUILD: 2026-09-10_PLANNING_WORKSPACE_2_0_SERVICE_FACADE_R5_BULK_CONCEPT
 * Thin RPC/service facade. Existing owners and entrypoints are preserved.
 ***********************************************************************/
var PLANNING_WORKSPACE_SERVICE_BUILD='2026-09-10_PLANNING_WORKSPACE_2_0_SERVICE_FACADE_R5_BULK_CONCEPT';
function PWS_dependencies_(){return{advisory:typeof ConceptPlanningService_get==='function',overlays:typeof PlanningWorkspaceOverlayBundle_get==='function',conceptUpsert:typeof ConceptReservationCommandService_upsert==='function',conceptRelease:typeof ConceptReservationCommandService_release==='function',bulkConceptSave:typeof PlanningWorkspaceBulkConceptService_save==='function',canonicalCommit:typeof PlanningCanonicalCommitService_commit==='function',reAdjustEvaluate:typeof PlanningReAdjustService_evaluate==='function',reAdjustCommit:typeof PlanningReAdjustService_commit==='function',selfPlanningAdvisory:typeof PlanningWorkspaceSelfPlanningService_getAdvisory==='function',selfPlanningContext:typeof PlanningWorkspaceSelfPlanningService_context==='function',selfPlanningEvaluate:typeof PlanningWorkspaceSelfPlanningService_evaluate==='function',selfPlanningCommit:typeof PlanningWorkspaceSelfPlanningService_commit==='function'};}
function PWS_assert_(name){var d=PWS_dependencies_();if(!d[name])throw new Error('PlanningWorkspaceService: dependency unavailable: '+name);}
function PlanningWorkspaceService_getAdvisory(input){PWS_assert_('advisory');return ConceptPlanningService_get(input||{});}
function PlanningWorkspaceService_getOverlays(input){PWS_assert_('overlays');return PlanningWorkspaceOverlayBundle_get(input||{});}
function PlanningWorkspaceService_saveConcept(input){PWS_assert_('conceptUpsert');return ConceptReservationCommandService_upsert(input||{});}
function PlanningWorkspaceService_releaseConcept(input){PWS_assert_('conceptRelease');return ConceptReservationCommandService_release(input||{});}
function PlanningWorkspaceService_saveConceptBatch(input){PWS_assert_('bulkConceptSave');return PlanningWorkspaceBulkConceptService_save(input||{});}
function PlanningWorkspaceService_commit(input){PWS_assert_('canonicalCommit');return PlanningCanonicalCommitService_commit(input||{});}
function PlanningWorkspaceService_reAdjustEvaluate(input){PWS_assert_('reAdjustEvaluate');return PlanningReAdjustService_evaluate(input||{});}
function PlanningWorkspaceService_reAdjustCommit(input){PWS_assert_('reAdjustCommit');return PlanningReAdjustService_commit(input||{});}
function PlanningWorkspaceService_selfPlanningAdvisory(input){PWS_assert_('selfPlanningAdvisory');return PlanningWorkspaceSelfPlanningService_getAdvisory(input||{});}
function PlanningWorkspaceService_selfPlanningContext(input){PWS_assert_('selfPlanningContext');return PlanningWorkspaceSelfPlanningService_context(input||{});}
function PlanningWorkspaceService_selfPlanningEvaluate(input){PWS_assert_('selfPlanningEvaluate');return PlanningWorkspaceSelfPlanningService_evaluate(input||{});}
function PlanningWorkspaceService_selfPlanningCommit(input){PWS_assert_('selfPlanningCommit');return PlanningWorkspaceSelfPlanningService_commit(input||{});}
function PlanningWorkspaceService_contract(){return{build:PLANNING_WORKSPACE_SERVICE_BUILD,dependencies:PWS_dependencies_(),endpoints:{advisory:'ConceptPlanningService_get',overlays:'PlanningWorkspaceOverlayBundle_get',saveConcept:'ConceptReservationCommandService_upsert',releaseConcept:'ConceptReservationCommandService_release',saveConceptBatch:'PlanningWorkspaceBulkConceptService_save',commit:'PlanningCanonicalCommitService_commit',reAdjustEvaluate:'PlanningReAdjustService_evaluate',reAdjustCommit:'PlanningReAdjustService_commit',selfPlanningAdvisory:'PlanningWorkspaceSelfPlanningService_getAdvisory',selfPlanningContext:'PlanningWorkspaceSelfPlanningService_context',selfPlanningEvaluate:'PlanningWorkspaceSelfPlanningService_evaluate',selfPlanningCommit:'PlanningWorkspaceSelfPlanningService_commit'},meta:{thinFacade:true,newSsot:false,directSheetReads:false,directSheetWrites:false,canonicalCommitOnly:true,legacyPlanningWriterCalledDirectly:false,legacyPlanningEntrypointsPreserved:true,existingAuditorPortalPreserved:true,selfPlanningServerFiltered:true,bulkConceptOwnerPreserved:true}};}
