/***********************************************************************
 * PlanningWorkspaceConceptLifecycle.js
 * BUILD: 2026-09-13_WORKSPACE_CONCEPT_LIFECYCLE_R1
 *
 * Read-only lifecycle projection for preliminary Concept Reservations.
 * Audit planning remains canonical lifecycle owner. Only concepts whose
 * canonical status is Pending Planning are active/planable in Workspace.
 ***********************************************************************/
var PLANNING_WORKSPACE_CONCEPT_LIFECYCLE_BUILD='2026-09-13_WORKSPACE_CONCEPT_LIFECYCLE_R1';
function PWCL_clean_(v){return String(v==null?'':v).trim();}
function PWCL_norm_(v){return PWCL_clean_(v).toLowerCase();}
function PWCL_col_(hdr,names){var m={};for(var i=0;i<(hdr||[]).length;i++)m[PWCL_norm_(hdr[i])]=i;for(var j=0;j<(names||[]).length;j++){var k=PWCL_norm_(names[j]);if(Object.prototype.hasOwnProperty.call(m,k))return m[k];}return-1;}
function PWCL_normalizedStatus_(raw){if(typeof Status_normalizeStatus_==='function')return Status_normalizeStatus_(raw);return PWCL_clean_(raw).toUpperCase().replace(/[\s-]+/g,'_');}
function PWCL_projectFromStatusMap_(rows,statusById){rows=Array.isArray(rows)?rows:[];statusById=statusById||{};var active=[],stale=[],missing=[];for(var i=0;i<rows.length;i++){var src=rows[i]||{},id=PWCL_clean_(src.auditId),raw=Object.prototype.hasOwnProperty.call(statusById,id)?PWCL_clean_(statusById[id]):'',normalized=PWCL_normalizedStatus_(raw),item={};for(var k in src)if(Object.prototype.hasOwnProperty.call(src,k))item[k]=src[k];item.canonicalStatus=raw;item.canonicalStatusNormalized=normalized;item.lifecycleCurrent=normalized==='PENDING_PLANNING';item.staleLifecycle=!item.lifecycleCurrent;if(!id||!raw){item.lifecycleReason='CANONICAL_AUDIT_OR_STATUS_MISSING';missing.push(item);stale.push(item);}else if(item.lifecycleCurrent){item.lifecycleReason='PENDING_PLANNING';active.push(item);}else{item.lifecycleReason='CANONICAL_STATUS_'+normalized;stale.push(item);}}return{activeRows:active,staleRows:stale,missingRows:missing};}
function PlanningWorkspaceConceptLifecycle_project(rows){rows=Array.isArray(rows)?rows:[];if(!rows.length)return{success:true,build:PLANNING_WORKSPACE_CONCEPT_LIFECYCLE_BUILD,activeRows:[],staleRows:[],missingRows:[],meta:{requested:0,active:0,stale:0,missing:0,batchSheetReads:0,perAuditReads:0,writes:false,newSsot:false,canonicalOwner:'Audit planning'}};var wanted={},ids=[];for(var i=0;i<rows.length;i++){var id=PWCL_clean_(rows[i]&&rows[i].auditId);if(id&&!wanted[id]){wanted[id]=1;ids.push(id);}}var ss=SpreadsheetApp.getActive(),pack=(typeof __mp_getSheetDataCached_==='function')?__mp_getSheetDataCached_(ss,'Audit planning'):null,sh=pack&&pack.sh?pack.sh:ss.getSheetByName('Audit planning');if(!sh)throw new Error('PlanningWorkspaceConceptLifecycle: Audit planning sheet missing');var values=pack&&Array.isArray(pack.data)?pack.data:sh.getDataRange().getValues(),hdr=values.length?values[0]:[],cId=PWCL_col_(hdr,['Audit ID','Audit_ID','AuditId']),cStatus=PWCL_col_(hdr,['Status']);if(cId<0||cStatus<0)throw new Error('PlanningWorkspaceConceptLifecycle: required Audit planning columns missing');var statusById={};for(var r=1;r<values.length;r++){var row=values[r]||[],auditId=PWCL_clean_(row[cId]);if(wanted[auditId]&&!Object.prototype.hasOwnProperty.call(statusById,auditId))statusById[auditId]=PWCL_clean_(row[cStatus]);}var projected=PWCL_projectFromStatusMap_(rows,statusById);return{success:true,build:PLANNING_WORKSPACE_CONCEPT_LIFECYCLE_BUILD,activeRows:projected.activeRows,staleRows:projected.staleRows,missingRows:projected.missingRows,meta:{requested:rows.length,uniqueAuditIds:ids.length,active:projected.activeRows.length,stale:projected.staleRows.length,missing:projected.missingRows.length,batchSheetReads:pack&&Array.isArray(pack.data)?0:1,executionCacheUsed:!!(pack&&Array.isArray(pack.data)),perAuditReads:0,writes:false,newSsot:false,canonicalOwner:'Audit planning',activeDefinition:'canonical status Pending Planning'}};}
