/***********************************************************************
 * PlanningTripWorkweekReadModel.js
 * BUILD: 2026-09-23_AMS03_PHASE8_TRIP_WORKWEEK_R2_PROFILE_CONTEXT
 * Read-only trip/workweek decision projection. No routing engine / no new SSoT.
 ***********************************************************************/
var AMS03_TRIP_WORKWEEK_BUILD='2026-09-23_AMS03_PHASE8_TRIP_WORKWEEK_R2_PROFILE_CONTEXT';
function PTW_clean_(v){return String(v==null?'':v).trim();}
function PTW_date_(v){if(!v)return'';if(v instanceof Date&&!isNaN(v.getTime()))return Utilities.formatDate(v,Session.getScriptTimeZone(),'yyyy-MM-dd');var s=PTW_clean_(v),m=s.match(/^(\d{4}-\d{2}-\d{2})/);return m?m[1]:'';}
function PTW_isoWeek_(s){var d=new Date(s+'T12:00:00');if(isNaN(d.getTime()))return'';var x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);var y=new Date(Date.UTC(x.getUTCFullYear(),0,1)),w=Math.ceil((((x-y)/86400000)+1)/7);return x.getUTCFullYear()+'-W'+('0'+w).slice(-2);}
function getPlanningTripWorkweekV5(payload){
 payload=payload||{};var t0=Date.now(),email=PTW_clean_(payload.auditorEmail).toLowerCase(),from=PTW_date_(payload.from),to=PTW_date_(payload.to),base=CompanyMap_getDataset_AuditorLayer_C01(email),profiles=PlanningProfilesService_get({includeCompanies:false,auditorEmails:email?[email]:[]}),auditorProfile=(profiles.auditors||[])[0]||{},rows=((base.auditLayers&&base.auditLayers.myAuditWorkload)||[]).map(function(x){var date=PTW_date_(x.dateLabel);return{auditId:PTW_clean_(x.auditId),companyUid:PTW_clean_(x.companyId),company:PTW_clean_(x.companyName),locationCode:PTW_clean_(x.locationCode),region:PTW_clean_(x.region),country:PTW_clean_(x.country),date:date,week:date?PTW_isoWeek_(date):'',status:PTW_clean_(x.auditStatus||x.status),scopes:PTW_clean_(x.scopesLabel),auditHours:Number(x.auditHours||0)||0,lat:x.lat,lng:x.lng,gpsValid:x.gpsValid===true};}).filter(function(x){if(from&&x.date&&x.date<from)return false;if(to&&x.date&&x.date>to)return false;return true;});
 var weeks={},regions={};rows.forEach(function(x){var k=x.week||'UNSCHEDULED',w=weeks[k]||(weeks[k]={week:k,audits:0,auditHours:0,regions:{},countries:{},auditIds:[]});w.audits++;w.auditHours+=x.auditHours;w.auditIds.push(x.auditId);if(x.region)w.regions[x.region]=true;if(x.country)w.countries[x.country]=true;if(x.region)regions[x.region]=(regions[x.region]||0)+1;});
 var workweeks=Object.keys(weeks).sort().map(function(k){var w=weeks[k];return{week:w.week,audits:w.audits,auditHours:Math.round(w.auditHours*100)/100,regions:Object.keys(w.regions).sort(),countries:Object.keys(w.countries).sort(),auditIds:w.auditIds.filter(Boolean),multiRegion:Object.keys(w.regions).length>1};});
 return{success:true,build:AMS03_TRIP_WORKWEEK_BUILD,auditorEmail:email,filters:{from:from,to:to},audits:rows,workweeks:workweeks,auditorProfile:{name:PTW_clean_(auditorProfile.name),baseLocation:PTW_clean_(auditorProfile.baseLocation),timezone:PTW_clean_(auditorProfile.timezone),blockedWeekdays:PTW_clean_(auditorProfile.blockedWeekdays)},summary:{audits:rows.length,weeks:workweeks.length,regions:Object.keys(regions).length,multiRegionWeeks:workweeks.filter(function(w){return w.multiRegion;}).length},meta:{readOnly:true,writes:false,newSsot:false,sourceOwner:'CompanyMap auditor workload projection',auditorProfileOwner:'Auditors via PlanningProfilesService',availabilityOwner:'Auditor Availability',routeOptimization:false,travelTimeCalculated:false,advisoryOnly:true,totalMs:Date.now()-t0}};
}
