/***********************************************************************
 * PlanningWorkspaceBulkConceptLiveDryRunTests.js
 * BUILD: 2026-09-10_PLANNING_WORKSPACE_BULK_CONCEPT_LIVE_DRYRUN_R2_RESILIENT
 * Live DEV/read-only verification of batch concept path. No business writes.
 ***********************************************************************/
var PLANNING_WORKSPACE_BULK_CONCEPT_LIVE_DRYRUN_BUILD='2026-09-10_PLANNING_WORKSPACE_BULK_CONCEPT_LIVE_DRYRUN_R2_RESILIENT';
function PWBLDR_nextWeekday_(s){var p=String(s||'').split('-'),d=new Date(Number(p[0]),Number(p[1])-1,Number(p[2]));while(d.getDay()===0||d.getDay()===6)d.setDate(d.getDate()+1);return Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}
function PWBLDR_blocks_(row){var req=Math.max(1,Number(row&&row.hoursToPlan||0)||1),date=PWBLDR_nextWeekday_(row&&row.planningWindowFrom||''),to=String(row&&row.planningWindowTo||''),out=[];while(req>0&&date&&(!to||date<=to)&&out.length<20){var h=Math.min(8,req),end=9+h;out.push({date:date,start:'09:00',end:String(Math.floor(end)).padStart(2,'0')+':00',hours:h});req-=h;if(req>0){var p=String(date).split('-'),d=new Date(Number(p[0]),Number(p[1])-1,Number(p[2]));do{d.setDate(d.getDate()+1);}while(d.getDay()===0||d.getDay()===6);date=Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}}return out;}
function RUN_PLANNING_WORKSPACE_BULK_CONCEPT_LIVE_DRYRUN(){var r=[];function t(n,o,d){r.push({name:n,ok:!!o,detail:o?'':String(d||'failed')});}var demand=PlanningDemandService_get({from:'2026-09-01',to:'2027-08-31',status:'Pending Planning',limit:500,includeCompanyMeta:false}),rows=demand&&demand.rows||[],chosen=rows.length?rows[0]:null;t('demandLiveRead',demand&&demand.success===true);t('pendingPlanningFound',!!chosen,'No Pending Planning audit found');var out=null;if(chosen){var rev=PlanningRevisionTokenService_get({auditId:chosen.auditId}),blocks=PWBLDR_blocks_(chosen),email=String(chosen.preassignedAuditor||chosen.assignedTo||'').trim().toLowerCase();if(email.indexOf('@')<0)email='david@agriqa.es';t('revisionLoaded',!!(rev&&rev.revision));t('revisionStatusPendingPlanning',String(rev&&rev.snapshot&&rev.snapshot.status||'').toLowerCase()==='pending planning');t('blocksPrepared',blocks.length>0&&blocks.reduce(function(a,b){return a+Number(b.hours||0);},0)>=(Number(chosen.hoursToPlan||0)||0));out=PlanningWorkspaceBulkConceptService_save({dryRun:true,items:[{auditId:chosen.auditId,auditorEmail:email,blocks:blocks,sourceRevision:rev&&rev.revision||'',expectedRevision:rev&&rev.revision||'',createdBy:'bulk-concept-live-dryrun'}]});t('bulkDryRunSuccess',out&&out.success===true&&out.reason==='DRY_RUN_VALID');t('statusGuardProven',out&&out.meta&&out.meta.statusGuard==='Pending Planning');t('bulkDryRunNoWrite',out&&out.meta&&out.meta.writes===false&&out.meta.canonicalWrites===false&&out.meta.availabilityWrites===false&&out.meta.statusWrites===false);t('ownerPreserved',out&&out.meta&&out.meta.owner==='ConceptReservationCommandService');}else{t('revisionLoaded',false,'Skipped');t('revisionStatusPendingPlanning',false,'Skipped');t('blocksPrepared',false,'Skipped');t('bulkDryRunSuccess',false,'Skipped');t('statusGuardProven',false,'Skipped');t('bulkDryRunNoWrite',false,'Skipped');t('ownerPreserved',false,'Skipped');}var f=r.filter(function(x){return!x.ok;}).length,res={ok:f===0,build:PLANNING_WORKSPACE_BULK_CONCEPT_LIVE_DRYRUN_BUILD,total:r.length,passed:r.length-f,failed:f,results:r,meta:{nonDestructive:true,liveReadsPerformed:true,liveWritesPerformed:false,selectedAuditId:chosen&&chosen.auditId||'',bulkConceptDryRun:true,statusGuard:'Pending Planning',canonicalWrites:false,availabilityWrites:false,statusWrites:false}};Logger.log(JSON.stringify(res,null,2));return res;}
