/***********************************************************************
 * PlanningWorkspaceToolkit2BatchTests.js
 * BUILD: 2026-09-10_PLANNING_WORKSPACE_TOOLKIT2_BATCH_TEST_R18_UX_LAYER
 ***********************************************************************/
var PLANNING_WORKSPACE_TOOLKIT2_BATCH_TEST_BUILD='2026-09-10_PLANNING_WORKSPACE_TOOLKIT2_BATCH_TEST_R18_UX_LAYER';
function RUN_PLANNING_WORKSPACE_TOOLKIT2_BATCH_REGRESSION(){
  var parts=[];function run(name,fn){try{var out=fn();parts.push({name:name,ok:!!(out&&out.ok),build:out&&out.build||'',total:out&&out.total||0,passed:out&&out.passed||0,failed:out&&out.failed||0,liveReads:!!(out&&out.meta&&out.meta.liveReadsPerformed),liveWrites:!!(out&&out.meta&&out.meta.liveWritesPerformed)});}catch(e){parts.push({name:name,ok:false,build:'',total:0,passed:0,failed:1,error:String(e&&e.message||e),liveReads:false,liveWrites:false});}}
  run('dragDropCalendar',RUN_PLANNING_WORKSPACE_DRAG_DROP_REGRESSION);run('selfPlanningSharedUi',RUN_PLANNING_WORKSPACE_SELF_PLANNING_REGRESSION);run('conceptCalendarInteraction',RUN_PLANNING_WORKSPACE_TOOLKIT2_INTERACTION_REGRESSION);run('calendarAuditorAvailability',RUN_PLANNING_WORKSPACE_CALENDAR_AVAILABILITY_REGRESSION);run('canonicalPlannedCalendar',RUN_PLANNING_WORKSPACE_CANONICAL_CALENDAR_REGRESSION);run('calendarDensityAndAuditorLoad',RUN_PLANNING_WORKSPACE_CALENDAR_DENSITY_REGRESSION);run('calendarFacets',RUN_PLANNING_WORKSPACE_CALENDAR_FACET_REGRESSION);run('bulkConceptPlanning',RUN_PLANNING_WORKSPACE_BULK_CONCEPT_REGRESSION);run('bulkConceptLiveDryRun',RUN_PLANNING_WORKSPACE_BULK_CONCEPT_LIVE_DRYRUN);run('bulkCanonicalPlanning',RUN_PLANNING_WORKSPACE_BULK_CANONICAL_REGRESSION);run('bulkCanonicalLivePreview',RUN_PLANNING_WORKSPACE_BULK_CANONICAL_LIVE_PREVIEW);run('plannerAuditorFocus',RUN_PLANNING_WORKSPACE_PLANNER_FOCUS_REGRESSION);run('planningWindowGuide',RUN_PLANNING_WORKSPACE_WINDOW_GUIDE_REGRESSION);run('plannerSummary',RUN_PLANNING_WORKSPACE_PLANNER_SUMMARY_REGRESSION);run('plannerAttention',RUN_PLANNING_WORKSPACE_PLANNER_ATTENTION_REGRESSION);run('batchDemandSelection',RUN_PLANNING_WORKSPACE_BATCH_SELECTION_REGRESSION);run('batchAgendaReview',RUN_PLANNING_WORKSPACE_BATCH_AGENDA_REGRESSION);run('plannerUx',RUN_PLANNING_WORKSPACE_UX_REGRESSION);
  var failedParts=parts.filter(function(x){return!x.ok;}).length,total=parts.reduce(function(a,x){return a+Number(x.total||0);},0),passed=parts.reduce(function(a,x){return a+Number(x.passed||0);},0);var out={ok:failedParts===0,build:PLANNING_WORKSPACE_TOOLKIT2_BATCH_TEST_BUILD,total:total,passed:passed,failed:total-passed,parts:parts,meta:{nonDestructive:true,liveReadsPerformed:parts.some(function(x){return x.liveReads;}),liveWritesPerformed:parts.some(function(x){return x.liveWrites;}),existingFunctionalityRemoved:false,batchAgendaReview:true,batchAgendaWarnings:['planning window','same auditor/day collision','>8h auditor/day'],batchAgendaReopensExistingEditor:true,plannerUxDefaults:true,legacyPlanningPreserved:true,existingAuditorPortalPreserved:true,conceptSaveOwnerPreserved:true,reAdjustOwnerPreserved:true,canonicalPlanningSsot:'Audit planning.Planning JSON',bulkConceptOwner:'ConceptReservationCommandService',bulkPreflightOwner:'PlanningCommitGateService',bulkCanonicalCommitOwner:'PlanningCanonicalCommitService',silentPartialSuccess:false,newSsot:false}};Logger.log(JSON.stringify(out,null,2));return out;
}
