/***********************************************************************
 * PlanningCanonicalAvailabilityTransaction.js
 * BUILD: 2026-09-09_ROADMAP_2_4_CANONICAL_AVAILABILITY_TRANSACTION_R1
 *
 * Pure orchestration helper. The caller supplies reserve/write/rollback
 * functions. If the canonical planning write fails after Availability was
 * reserved, Availability is compensated before the result is returned.
 ***********************************************************************/
var PLANNING_CANONICAL_AVAILABILITY_TRANSACTION_BUILD='2026-09-09_ROADMAP_2_4_CANONICAL_AVAILABILITY_TRANSACTION_R1';
function PlanningCanonicalAvailabilityTransaction_execute(input){input=input||{};var reserveFn=input.reserveFn,writeFn=input.writeFn,rollbackFn=input.rollbackFn;if(typeof reserveFn!=='function'||typeof writeFn!=='function'||typeof rollbackFn!=='function')throw new Error('PlanningCanonicalAvailabilityTransaction: reserveFn/writeFn/rollbackFn required');var reserveResult;try{reserveResult=reserveFn();}catch(e0){return{success:false,committed:false,reason:'AVAILABILITY_RESERVE_EXCEPTION',reserveResult:null,writeResult:null,rollbackResult:null,rollbackAttempted:false,error:String(e0&&e0.message||e0)};}if(!reserveResult||reserveResult.success===false)return{success:false,committed:false,reason:'AVAILABILITY_RESERVE_FAILED',reserveResult:reserveResult||null,writeResult:null,rollbackResult:null,rollbackAttempted:false};var writeResult,writeError='';try{writeResult=writeFn();}catch(e1){writeError=String(e1&&e1.message||e1);writeResult=null;}if(writeResult&&writeResult.success===true)return{success:true,committed:true,reason:'COMMITTED',reserveResult:reserveResult,writeResult:writeResult,rollbackResult:null,rollbackAttempted:false};var rollbackResult,rollbackError='';try{rollbackResult=rollbackFn();}catch(e2){rollbackError=String(e2&&e2.message||e2);rollbackResult=null;}var repaired=!!(rollbackResult&&rollbackResult.success!==false);return{success:false,committed:false,reason:repaired?'CANONICAL_WRITE_FAILED_AVAILABILITY_ROLLED_BACK':'CANONICAL_WRITE_FAILED_AVAILABILITY_REPAIR_REQUIRED',reserveResult:reserveResult,writeResult:writeResult,writeError:writeError,rollbackResult:rollbackResult,rollbackError:rollbackError,rollbackAttempted:true,repairRequired:!repaired};}
