/***********************************************************************
 * PlanningCanonicalCommitService.js
 * BUILD: 2026-09-17_ROADMAP_2_4_CANONICAL_COMMIT_R8_NOTIFICATION_OUTSIDE_LOCK
 ***********************************************************************/
var PLANNING_CANONICAL_COMMIT_BUILD='2026-09-17_ROADMAP_2_4_CANONICAL_COMMIT_R8_NOTIFICATION_OUTSIDE_LOCK';
function PCCS_clean_(v){return String(v==null?'':v).trim();}
function PCCS_dependencies_(){return{lock:typeof Platform_withLock==='function',lockedGate:typeof PlanningCommitGateService_evaluateLocked_==='function',statusMachine:typeof Status_applyTransition_==='function',loadContext:typeof loadContext_==='function',findAudit:typeof findAudit_==='function',canonicalRowWriter:typeof PlanningCanonicalRowWriter_execute==='function',revisionBuilder:typeof PRT_tokenFromSnapshot_==='function',reservationReleaseBridge:typeof ConceptReservationCommitReleaseBridge_releaseLocked==='function',postCommitRelease:typeof PlanningCanonicalPostCommitFinalizer_release==='function',postCommitNotification:typeof PlanningCanonicalPostCommitFinalizer_notification==='function',notificationBridge:typeof StatusNotificationBridge_Dispatch_==='function',availabilityOwnerGuard:typeof PlanningCanonicalAvailabilityOwnerGuard_evaluate==='function',availabilityAdapterReserve:typeof PlanningCanonicalAvailabilityAdapter_reserve==='function',availabilityAdapterRelease:typeof PlanningCanonicalAvailabilityAdapter_release==='function',availabilityTransaction:typeof PlanningCanonicalAvailabilityTransaction_execute==='function'};}
function PCCS_assertDependencies_(){var d=PCCS_dependencies_();Object.keys(d).forEach(function(k){if(!d[k])throw new Error('PlanningCanonicalCommitService: dependency unavailable: '+k);});}
function PCCS_blocked_(input,gate,reason,extra){return{success:true,build:PLANNING_CANONICAL_COMMIT_BUILD,auditId:PCCS_clean_(input&&input.auditId),committed:false,canCommit:false,reason:reason||(gate&&gate.reason)||'COMMIT_BLOCKED',gate:gate||null,writeResult:null,newRevision:'',reservationRelease:null,notification:null,availabilityOwnerGuard:extra&&extra.availabilityOwnerGuard||null,canonicalStatus:extra&&extra.canonicalStatus||'',transitionCode:extra&&extra.transitionCode||'',availabilityTransaction:null,meta:{lockUsed:true,oneLockThroughWriteBoundary:true,canonicalWriterCalled:false,canonicalWriter:'PlanningCanonicalRowWriter_execute',statusOwner:'StatusMachine',availabilityOwner:'AvailabilityService via PlanningCanonicalAvailabilityAdapter',notificationOwner:'StatusNotificationBridge -> Notification Queue',notificationOutsidePlanningLock:true,revisionRole:'derived concurrency token only',reservationReleasedAfterCommit:false,directAvailabilityFallbackAccepted:false}};}
function PCCS_postWriteRevision_(w){if(!w||w.success!==true)return'';return PRT_tokenFromSnapshot_({auditId:PCCS_clean_(w.auditId),status:PCCS_clean_(w.newStatus||w.afterStatusDisplay),assignedTo:PCCS_clean_(w.assignedTo),datePlanned:PCCS_clean_(w.plannedDate),planningJson:PCCS_clean_(w.planningJson)});}
function PCCS_notificationContext_(rowInfo,auditId){return{auditId:auditId,status:rowInfo&&rowInfo.status||'',row:rowInfo&&rowInfo.row||null};}
function PCCS_notificationResult_(writeResult){return{success:true,beforeStatus:writeResult&&writeResult.beforeStatusDisplay||writeResult&&writeResult.beforeStatus||'',afterStatus:writeResult&&writeResult.afterStatus||'',afterStatusDisplay:writeResult&&writeResult.afterStatusDisplay||writeResult&&writeResult.newStatus||'',newStatus:writeResult&&writeResult.newStatus||''};}
function PCCS_mergePostCommit_(locked,note){if(!locked||locked.committed!==true)return locked;note=note||{notification:null,notificationRepairRequired:true,reason:'COMMITTED_NOTIFICATION_REPAIR_REQUIRED'};locked.notification=note.notification||null;locked.meta=locked.meta||{};locked.meta.notificationRequired=true;locked.meta.notificationOutsidePlanningLock=true;locked.meta.notificationFailureDoesNotUndoCanonicalCommit=true;locked.meta.notificationRepairRequired=note.notificationRepairRequired===true;locked.meta.postCommitRepairRequired=locked.meta.reservationReleaseRepairRequired===true||note.notificationRepairRequired===true;if(locked.meta.reservationReleaseRepairRequired&&note.notificationRepairRequired)locked.reason='COMMITTED_POST_COMMIT_REPAIR_REQUIRED';else if(locked.meta.reservationReleaseRepairRequired)locked.reason='COMMITTED_RESERVATION_RELEASE_REPAIR_REQUIRED';else if(note.notificationRepairRequired)locked.reason='COMMITTED_NOTIFICATION_REPAIR_REQUIRED';else locked.reason='COMMITTED';return locked;}
function PlanningCanonicalCommitService_commit(input){
  input=input||{};var auditId=PCCS_clean_(input.auditId),expectedRevision=PCCS_clean_(input.expectedRevision),actorRole=PCCS_clean_(input.actorRole||'MANAGER').toUpperCase();if(!auditId)throw new Error('PlanningCanonicalCommitService: auditId is required');if(!expectedRevision)throw new Error('PlanningCanonicalCommitService: expectedRevision is required');if(!Array.isArray(input.blocks)||!input.blocks.length)throw new Error('PlanningCanonicalCommitService: blocks are required');PCCS_assertDependencies_();var perf=typeof DPL_start_==='function'?DPL_start_('PlanningCanonicalCommitService_commit',{auditId:auditId,blockCount:input.blocks.length,actorRole:actorRole}):null,lockWaitMs=Math.max(500,Math.min(10000,Number(input.lockWaitMs||3000)||3000));
  var locked=Platform_withLock('planning-commit:'+auditId,function(){
    var gate=PlanningCommitGateService_evaluateLocked_({auditId:auditId,expectedRevision:expectedRevision,auditorEmail:input.auditorEmail,auditorName:input.auditorName,blocks:input.blocks,waiverAccepted:input.waiverAccepted===true},perf);if(!gate||gate.canCommit!==true)return PCCS_blocked_(input,gate,gate&&gate.reason);
    var availabilityOwnerGuard=PlanningCanonicalAvailabilityOwnerGuard_evaluate();if(typeof DPL_mark_==='function')DPL_mark_(perf,'availabilityOwnerGuard',{canProceed:availabilityOwnerGuard.canProceed===true,owner:availabilityOwnerGuard.selectedOwner||''});if(!availabilityOwnerGuard||availabilityOwnerGuard.canProceed!==true)return PCCS_blocked_(input,gate,'CANONICAL_AVAILABILITY_OWNER_UNAVAILABLE',{availabilityOwnerGuard:availabilityOwnerGuard});
    var ss=SpreadsheetApp.getActive(),sh=ss&&ss.getSheetByName('Audit planning');if(!sh)return PCCS_blocked_(input,gate,"Sheet 'Audit planning' missing.",{availabilityOwnerGuard:availabilityOwnerGuard});var ctx=loadContext_(sh),rowInfo=findAudit_(ctx,auditId);if(!rowInfo)return PCCS_blocked_(input,gate,'AUDIT_NOT_FOUND_AT_WRITE_BOUNDARY',{availabilityOwnerGuard:availabilityOwnerGuard});var transition=Status_applyTransition_({status:rowInfo.status,action:'PLAN',role:actorRole});if(!transition||!transition.ok){var canonicalStatus=PCCS_clean_(rowInfo.status),normalized=typeof Status_normalizeStatus_==='function'?Status_normalizeStatus_(canonicalStatus):canonicalStatus,stale=normalized&&normalized!=='PENDING_PLANNING';return PCCS_blocked_(input,gate,stale?'CONCEPT_STALE_CANONICAL_STATUS':'STATUS_TRANSITION_BLOCKED',{availabilityOwnerGuard:availabilityOwnerGuard,canonicalStatus:canonicalStatus,transitionCode:transition&&transition.code||''});}
    if(typeof DPL_mark_==='function')DPL_mark_(perf,'freshStatusTransition',{beforeStatus:rowInfo.status||'',afterStatus:transition.afterStatusDisplay||''});var tx=PlanningCanonicalAvailabilityTransaction_execute({reserveFn:function(){return PlanningCanonicalAvailabilityAdapter_reserve({auditId:auditId,auditorEmail:input.auditorEmail||input.auditorName||'',auditorName:input.auditorName||'',blocks:input.blocks});},writeFn:function(){return PlanningCanonicalRowWriter_execute(rowInfo,transition,{auditId:auditId,blocks:input.blocks,auditorName:input.auditorName||'',auditorEmail:input.auditorEmail||'',allowWeekend:input.allowWeekendOverride!==false,isReschedule:false});},rollbackFn:function(){return PlanningCanonicalAvailabilityAdapter_release({auditId:auditId});}});if(typeof DPL_mark_==='function')DPL_mark_(perf,'canonicalAvailabilityTransaction',{committed:tx&&tx.committed===true,reason:tx&&tx.reason||'',rollbackAttempted:tx&&tx.rollbackAttempted===true,repairRequired:tx&&tx.repairRequired===true});
    if(!tx||tx.committed!==true)return{success:false,build:PLANNING_CANONICAL_COMMIT_BUILD,auditId:auditId,committed:false,canCommit:true,reason:tx&&tx.reason||'CANONICAL_TRANSACTION_FAILED',gate:gate,availabilityOwnerGuard:availabilityOwnerGuard,availabilityTransaction:tx||null,writeResult:tx&&tx.writeResult||null,newRevision:'',reservationRelease:null,notification:null,meta:{lockUsed:true,oneLockThroughWriteBoundary:true,canonicalWriterCalled:!!(tx&&tx.writeResult),canonicalWriter:'PlanningCanonicalRowWriter_execute',availabilityRollbackAttempted:!!(tx&&tx.rollbackAttempted),availabilityRepairRequired:!!(tx&&tx.repairRequired),reservationReleasedAfterCommit:false,notificationOutsidePlanningLock:true,directAvailabilityFallbackAccepted:false}};
    var writeResult=tx.writeResult,newRevision=PCCS_postWriteRevision_(writeResult),release=PlanningCanonicalPostCommitFinalizer_release({releaseFn:function(){return ConceptReservationCommitReleaseBridge_releaseLocked({auditId:auditId,releasedBy:input.actorEmail||input.releasedBy||'',reason:'CANONICAL_COMMIT'});}});if(typeof DPL_mark_==='function')DPL_mark_(perf,'conceptReservationRelease',{released:release.reservationRelease&&release.reservationRelease.released===true,reason:release.reservationRelease&&release.reservationRelease.reason||'',repairRequired:release.releaseRepairRequired===true});
    return{success:true,build:PLANNING_CANONICAL_COMMIT_BUILD,auditId:auditId,committed:true,canCommit:true,reason:release.reason,gate:gate,availabilityOwnerGuard:availabilityOwnerGuard,availabilityTransaction:tx,writeResult:writeResult,newRevision:newRevision,reservationRelease:release.reservationRelease,notification:null,_notificationIntent:{context:PCCS_notificationContext_(rowInfo,auditId),result:PCCS_notificationResult_(writeResult)},meta:{lockUsed:true,oneLockThroughWriteBoundary:true,canonicalWriterCalled:true,canonicalWriter:'PlanningCanonicalRowWriter_execute',statusOwner:'StatusMachine',availabilityOwner:availabilityOwnerGuard.selectedOwner,notificationOwner:'StatusNotificationBridge -> Notification Queue',notificationRequired:true,notificationOutsidePlanningLock:true,availabilityRollbackContract:true,availabilityRepairRequired:false,revisionRole:'derived concurrency token only',postWriteRevisionExtraRead:false,legacyEntrypointsChanged:false,reservationReleaseAttemptedAfterCommit:true,reservationReleaseNestedLock:false,reservationReleaseFailureDoesNotUndoCanonicalCommit:true,reservationReleaseRepairRequired:release.releaseRepairRequired===true,postCommitRepairRequired:release.releaseRepairRequired===true,postCommitFinalizer:true,directAvailabilityFallbackAccepted:false}};
  },lockWaitMs);
  if(locked&&locked.committed===true){var intent=locked._notificationIntent||{},note=PlanningCanonicalPostCommitFinalizer_notification({notificationRequired:true,notificationFn:function(){var n=StatusNotificationBridge_Dispatch_('PLAN',actorRole,intent.context||{auditId:auditId},{actorEmail:input.actorEmail||'',auditorEmail:input.auditorEmail||'',assignedTo:input.auditorEmail||input.auditorName||''},intent.result||{});return n||{success:false,reason:'NOTIFICATION_DISPATCH_NO_RESULT'};}});delete locked._notificationIntent;PCCS_mergePostCommit_(locked,note);if(typeof DPL_mark_==='function')DPL_mark_(perf,'notificationQueueOutsidePlanningLock',{success:locked.notification&&locked.notification.success===true,reason:locked.notification&&locked.notification.reason||'',repairRequired:locked.meta.notificationRepairRequired===true});}
  if(typeof DPL_end_==='function')locked.devPerformance=DPL_end_(perf,{committed:locked&&locked.committed===true,reason:locked&&locked.reason||'',canonicalWriterCalled:!!(locked&&locked.meta&&locked.meta.canonicalWriterCalled),reservationReleased:!!(locked&&locked.reservationRelease&&locked.reservationRelease.released),notificationRepairRequired:!!(locked&&locked.meta&&locked.meta.notificationRepairRequired),notificationOutsidePlanningLock:!!(locked&&locked.meta&&locked.meta.notificationOutsidePlanningLock),availabilityRollbackAttempted:!!(locked&&locked.meta&&locked.meta.availabilityRollbackAttempted)});return locked;
}
