/***********************************************************************
 * PlanningRevisionTokenService.js
 * BUILD: 2026-09-17_ROADMAP_2_4_PLANNING_REVISION_TOKEN_R6_TRUTHFUL_READ_TELEMETRY
 ***********************************************************************/
var PLANNING_REVISION_TOKEN_BUILD='2026-09-17_ROADMAP_2_4_PLANNING_REVISION_TOKEN_R6_TRUTHFUL_READ_TELEMETRY';
var PLANNING_REVISION_TOKEN_MAX_BULK=20;
function PRT_clean_(v){if(v==null)return'';if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v.getTime()))return Utilities.formatDate(v,'UTC','yyyy-MM-dd');return String(v).trim();}
function PRT_normJson_(v){var s=PRT_clean_(v);if(!s)return'';try{return JSON.stringify(JSON.parse(s));}catch(e){return s;}}
function PRT_findCol_(headers,candidates){headers=headers||[];var n=headers.map(function(h){return PRT_clean_(h).toLowerCase().replace(/[ _\-–—]/g,'');});for(var c=0;c<candidates.length;c++){var k=PRT_clean_(candidates[c]).toLowerCase().replace(/[ _\-–—]/g,'');var ix=n.indexOf(k);if(ix>=0)return ix;}return-1;}
function PRT_value_(headers,row,candidates){var ix=PRT_findCol_(headers,candidates);return ix>=0?row[ix]:'';}
function PRT_snapshotFromRow_(headers,row){return{auditId:PRT_clean_(PRT_value_(headers,row,['Audit ID','Audit_ID','AuditId','Audit Id'])),status:PRT_clean_(PRT_value_(headers,row,['Status'])),assignedTo:PRT_clean_(PRT_value_(headers,row,['Assigned to','Assigned To','Assigned auditor','Auditor'])),datePlanned:PRT_clean_(PRT_value_(headers,row,['Date - Planned','Date planned','Date Planned','Planned date'])),planningJson:PRT_normJson_(PRT_value_(headers,row,['Planning JSON','PlanningJson','Planning_JSON']))};}
function PRT_serializeSnapshot_(s){s=s||{};return['auditId='+PRT_clean_(s.auditId),'status='+PRT_clean_(s.status),'assignedTo='+PRT_clean_(s.assignedTo).toLowerCase(),'datePlanned='+PRT_clean_(s.datePlanned),'planningJson='+PRT_normJson_(s.planningJson)].join('\n');}
function PRT_sha1_(text){var b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_1,String(text||'')),out='';for(var i=0;i<b.length;i++){var n=b[i]<0?b[i]+256:b[i],h=n.toString(16);out+=h.length===1?'0'+h:h;}return out;}
function PRT_tokenFromSnapshot_(s){return'PRT1-'+PRT_sha1_(PRT_serializeSnapshot_(s));}
function PRT_readCanonicalRow_(auditId,perf){auditId=PRT_clean_(auditId);if(!auditId)throw new Error('PlanningRevisionTokenService: auditId is required');var ss=SpreadsheetApp.getActiveSpreadsheet();if(typeof __mp_getAuditPlanningRow_==='function'){var t=__mp_getAuditPlanningRow_(ss,auditId);if(t&&t.row){if(typeof DPL_mark_==='function')DPL_mark_(perf,'targetedRead',{source:'__mp_getAuditPlanningRow_',rowNumber:t.rowNumber||0});return{headers:t.hdr||[],row:t.row,rowNumber:t.rowNumber||0,source:'__mp_getAuditPlanningRow_'};}}if(typeof Platform_findRowByKey==='function'&&typeof Platform_readRow==='function'){var rn=Platform_findRowByKey('Audit planning','Audit ID',auditId);if(rn){var o=Platform_readRow('Audit planning',rn);if(typeof DPL_mark_==='function')DPL_mark_(perf,'targetedRead',{source:'Platform PAL fallback',rowNumber:rn});return{headers:o._hdr||[],row:o._raw||[],rowNumber:rn,source:'Platform PAL fallback'};}}throw new Error('PlanningRevisionTokenService: audit not found: '+auditId);}
function PRT_result_(auditId,headers,row,source,rowNumber){var s=PRT_snapshotFromRow_(headers,row);if(s.auditId&&s.auditId!==auditId)throw new Error('PlanningRevisionTokenService: canonical row Audit ID mismatch');s.auditId=auditId;return{success:true,build:PLANNING_REVISION_TOKEN_BUILD,auditId:auditId,revision:PRT_tokenFromSnapshot_(s),snapshot:s,meta:{writes:false,readOnly:true,derivedOnly:true,revisionIsConcurrencyTokenOnly:true,canonicalOwner:'Audit planning',fields:['Status','Assigned to','Date - Planned','Planning JSON'],rowSource:source,rowNumber:rowNumber||0,lockRequiredForCommitReread:true,lockOwner:'Platform_withLock'}};}
function PlanningRevisionTokenService_get(input){input=input||{};var id=PRT_clean_(input.auditId);if(!id)throw new Error('PlanningRevisionTokenService: auditId is required');var perf=typeof DPL_start_==='function'?DPL_start_('PlanningRevisionTokenService_get',{auditId:id}):null,c=PRT_readCanonicalRow_(id,perf),r=PRT_result_(id,c.headers,c.row,c.source,c.rowNumber);if(typeof DPL_mark_==='function')DPL_mark_(perf,'deriveRevision',{source:c.source,planningJsonChars:r.snapshot.planningJson.length});if(typeof DPL_end_==='function')r.devPerformance=DPL_end_(perf,{rowSource:c.source,revisionPrefix:r.revision.substring(0,9)});return r;}
function PlanningRevisionTokenService_getMany(input){input=input||{};var ids=Array.isArray(input.auditIds)?input.auditIds:[],clean=[],seen={};for(var i=0;i<ids.length;i++){var id=PRT_clean_(ids[i]);if(id&&!seen[id]){seen[id]=1;clean.push(id);}}if(!clean.length)return{success:true,build:PLANNING_REVISION_TOKEN_BUILD,items:[],byAuditId:{},meta:{readOnly:true,writes:false,derivedOnly:true,bounded:true,maxItems:20,bulkRequest:true,physicalReadMode:'NONE',physicalSheetReads:0,rowPayloadPhysicalSheetReads:0,indexPhysicalSheetReads:0,physicalSheetReadsTotal:0,canonicalOwner:'Audit planning',newSsot:false}};if(clean.length>20)throw new Error('PlanningRevisionTokenService: maximum 20 auditIds per bulk request');if(typeof __mp_getAuditPlanningRows_!=='function')throw new Error('PlanningRevisionTokenService: bulk row reader unavailable');var ss=SpreadsheetApp.getActiveSpreadsheet(),bulk=__mp_getAuditPlanningRows_(ss,clean);if(!bulk||!bulk.items)throw new Error('PlanningRevisionTokenService: bulk canonical read failed');var out=[],by={};for(var j=0;j<clean.length;j++){var key=clean[j],p=bulk.items[key];if(!p||!p.row)throw new Error('PlanningRevisionTokenService: audit not found: '+key);var item=PRT_result_(key,p.hdr||bulk.hdr||[],p.row,'__mp_getAuditPlanningRows_ true bulk',p.rowNumber||0);out.push(item);by[key]=item.revision;}var bm=bulk.meta||{},rowReads=Number(bm.rowPayloadPhysicalSheetReads!=null?bm.rowPayloadPhysicalSheetReads:bm.physicalSheetReads||0),indexReads=Number(bm.indexPhysicalSheetReads||0);return{success:true,build:PLANNING_REVISION_TOKEN_BUILD,items:out,byAuditId:by,meta:{readOnly:true,writes:false,derivedOnly:true,bounded:true,maxItems:20,bulkRequest:true,indexedBulk:true,trueBulkRowRead:true,fullSheetScan:false,requested:clean.length,physicalReadMode:'NARROW_INDEX_PLUS_ONE_BOUNDED_RANGE_PLUS_CACHE',physicalSheetReads:rowReads,rowPayloadPhysicalSheetReads:rowReads,indexPhysicalSheetReads:indexReads,physicalSheetReadsTotal:Number(bm.physicalSheetReadsTotal!=null?bm.physicalSheetReadsTotal:indexReads+rowReads),coldIndexBuild:bm.coldIndexBuild===true,indexBuildMode:bm.indexBuildMode||'UNKNOWN',cacheHits:Number(bm.cacheHits||0),rangeRows:Number(bm.rangeRows||0),nPlusOneSheetReads:false,canonicalOwner:'Audit planning',newSsot:false}};}
