/***********************************************************************
 * PlanningWorkspaceCanonicalCalendarReadModel.js
 * BUILD: 2026-09-10_PLANNING_WORKSPACE_CANONICAL_CALENDAR_READ_R2_AUDIT_SCOPE
 *
 * Read-only bounded projection of canonical Planning JSON for the Workspace
 * calendar. Audit planning remains the SSoT. One header read + one bounded
 * contiguous body read; no per-audit reads and no writes.
 ***********************************************************************/
var PLANNING_WORKSPACE_CANONICAL_CALENDAR_READ_BUILD='2026-09-10_PLANNING_WORKSPACE_CANONICAL_CALENDAR_READ_R2_AUDIT_SCOPE';
function PWCCR_clean_(v){return String(v==null?'':v).trim();}
function PWCCR_norm_(v){return PWCCR_clean_(v).toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ');}
function PWCCR_find_(h,names){var m={};for(var i=0;i<h.length;i++)m[PWCCR_norm_(h[i])]=i;for(var j=0;j<names.length;j++){var k=PWCCR_norm_(names[j]);if(Object.prototype.hasOwnProperty.call(m,k))return m[k];}return-1;}
function PWCCR_status_(v){var s=PWCCR_norm_(v);return s==='pending approval'||s==='approved'||s==='accepted';}
function PWCCR_blocks_(raw){raw=PWCCR_clean_(raw);if(!raw)return[];try{var p=JSON.parse(raw),a=Array.isArray(p)?p:(p&&Array.isArray(p.blocks)?p.blocks:(p&&Array.isArray(p.slots)?p.slots:(p&&Array.isArray(p.days)?p.days:[]))),o=[];for(var i=0;i<a.length;i++){var b=a[i]||{},d=PWCCR_clean_(b.date||b.day).slice(0,10),st=PWCCR_clean_(b.start||b.startTime),en=PWCCR_clean_(b.end||b.endTime);if(d)o.push({date:d,start:st,end:en,hours:Number(b.hours||0)||0});}return o;}catch(e){return[];}}
function PWCCR_overlaps_(blocks,from,to){for(var i=0;i<blocks.length;i++){var d=blocks[i].date;if((!from||d>=from)&&(!to||d<=to))return true;}return false;}
function PWCCR_idSet_(raw){var a=Array.isArray(raw)?raw:[],s={};for(var i=0;i<a.length;i++){var id=PWCCR_clean_(a[i]);if(id)s[id]=1;}return{set:s,count:Object.keys(s).length,requested:a.length>0};}
function PlanningWorkspaceCanonicalCalendarReadModel_get(input){input=input||{};var from=PWCCR_clean_(input.from||input.start||input.periodFrom),to=PWCCR_clean_(input.to||input.end||input.periodTo);if(!from||!to)throw new Error('PlanningWorkspaceCanonicalCalendarReadModel: from/to required');var idScope=PWCCR_idSet_(input.auditIds);var ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName('Audit planning');if(!sh)throw new Error("PlanningWorkspaceCanonicalCalendarReadModel: missing sheet 'Audit planning'");var lastRow=sh.getLastRow(),lastCol=sh.getLastColumn();if(lastRow<2||lastCol<1)return{success:true,build:PLANNING_WORKSPACE_CANONICAL_CALENDAR_READ_BUILD,period:{from:from,to:to},rows:[],meta:{writes:false,rowsRead:0,colsRead:0,batchReads:1,perAuditReads:0,source:'Audit planning',auditScopeApplied:idScope.requested,auditScopeCount:idScope.count}};var h=sh.getRange(1,1,1,lastCol).getValues()[0]||[],cId=PWCCR_find_(h,['Audit ID','Audit_ID','AuditId','Audit Id']),cStatus=PWCCR_find_(h,['Status']),cAssigned=PWCCR_find_(h,['Assigned to','Assigned auditor','Auditor']),cPlan=PWCCR_find_(h,['Planning JSON','Planning','PlanningJSON','Planning_Js']),cCompany=PWCCR_find_(h,['Company']);if(cId<0||cStatus<0||cAssigned<0||cPlan<0)throw new Error('PlanningWorkspaceCanonicalCalendarReadModel: required columns missing');var used=[cId,cStatus,cAssigned,cPlan];if(cCompany>=0)used.push(cCompany);var min=Math.min.apply(null,used),max=Math.max.apply(null,used),width=max-min+1,vals=sh.getRange(2,min+1,lastRow-1,width).getValues(),rel=function(x){return x<0?-1:x-min;},rId=rel(cId),rStatus=rel(cStatus),rAssigned=rel(cAssigned),rPlan=rel(cPlan),rCompany=rel(cCompany),rows=[];for(var r=0;r<vals.length;r++){var v=vals[r]||[],auditId=PWCCR_clean_(v[rId]);if(idScope.requested&&!idScope.set[auditId])continue;var status=PWCCR_clean_(v[rStatus]);if(!PWCCR_status_(status))continue;var blocks=PWCCR_blocks_(v[rPlan]);if(!blocks.length||!PWCCR_overlaps_(blocks,from,to))continue;rows.push({auditId:auditId,company:rCompany>=0?PWCCR_clean_(v[rCompany]):'',status:status,auditorEmail:PWCCR_clean_(v[rAssigned]).toLowerCase(),auditorName:PWCCR_clean_(v[rAssigned]),blocks:blocks,rowNumber:r+2});}return{success:true,build:PLANNING_WORKSPACE_CANONICAL_CALENDAR_READ_BUILD,period:{from:from,to:to},rows:rows,meta:{writes:false,readOnly:true,rowsRead:vals.length,colsRead:width,batchReads:1,perAuditReads:0,canonicalOwner:'Audit planning.Planning JSON',statuses:['Pending Approval','Approved','Accepted'],auditScopeApplied:idScope.requested,auditScopeCount:idScope.count,newSsot:false}};}
function PlanningWorkspaceCanonicalCalendarReadModel_contract(){return{build:PLANNING_WORKSPACE_CANONICAL_CALENDAR_READ_BUILD,source:'Audit planning.Planning JSON',statuses:['Pending Approval','Approved','Accepted'],batchReads:1,perAuditReads:0,optionalAuditIdScope:true,writes:false,newSsot:false};}
