/***********************************************************************
 * PlanningWorkspaceBulkConceptService.js
 * BUILD: 2026-09-10_PLANNING_WORKSPACE_BULK_CONCEPT_SERVICE_R3_CANONICAL_GATE
 * Batch wrapper around existing ConceptReservationCommandService owner.
 * Preliminary Concept Reservations only; never canonical planning writes.
 ***********************************************************************/
var PLANNING_WORKSPACE_BULK_CONCEPT_SERVICE_BUILD='2026-09-10_PLANNING_WORKSPACE_BULK_CONCEPT_SERVICE_R3_CANONICAL_GATE';
function PWB_clean_(v){return String(v==null?'':v).trim();}
function PWB_normStatus_(v){return PWB_clean_(v).toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ');}
function PWB_items_(input){var a=input&&Array.isArray(input.items)?input.items:[];if(!a.length)throw new Error('PlanningWorkspaceBulkConceptService: items required');if(a.length>25)throw new Error('PlanningWorkspaceBulkConceptService: maximum 25 items per batch');var seen={};return a.map(function(x){x=x||{};var id=PWB_clean_(x.auditId);if(!id)throw new Error('PlanningWorkspaceBulkConceptService: auditId required');if(seen[id])throw new Error('PlanningWorkspaceBulkConceptService: duplicate auditId '+id);seen[id]=1;if(!PWB_clean_(x.auditorEmail))throw new Error('PlanningWorkspaceBulkConceptService: auditorEmail required for '+id);if(!PWB_clean_(x.sourceRevision||x.expectedRevision))throw new Error('PlanningWorkspaceBulkConceptService: sourceRevision required for '+id);if(!Array.isArray(x.blocks)||!x.blocks.length)throw new Error('PlanningWorkspaceBulkConceptService: blocks required for '+id);return{auditId:id,auditorEmail:PWB_clean_(x.auditorEmail).toLowerCase(),auditorName:PWB_clean_(x.auditorName),blocks:x.blocks,sourceRevision:PWB_clean_(x.sourceRevision||x.expectedRevision),expectedRevision:PWB_clean_(x.expectedRevision||x.sourceRevision),createdBy:PWB_clean_(x.createdBy||input.createdBy||'planning-workspace'),purpose:PWB_clean_(x.purpose||'PRELIMINARY_COMPANY_CONFIRMATION'),note:PWB_clean_(x.note),lockWaitMs:x.lockWaitMs};});}
function PWB_gateReason_(g){if(!g)return'CANONICAL_GATE_FAILED';if(g.canCommit===true)return'OK';return PWB_clean_(g.reason||g.code||g.verdict||'CANONICAL_GATE_BLOCKED');}
function PWB_precheck_(item){var p={};Object.keys(item).forEach(function(k){p[k]=item[k];});p.dryRun=true;var r=ConceptReservationCommandService_upsert(p),status=PWB_normStatus_(r&&r.revision&&r.revision.snapshot&&r.revision.snapshot.status),revisionOk=!!(r&&r.success===true&&r.reason==='DRY_RUN_VALID'),statusOk=status==='pending planning',gate=null,gateOk=false;if(revisionOk&&statusOk){gate=PlanningCommitGateService_evaluate({auditId:item.auditId,expectedRevision:item.expectedRevision,auditorEmail:item.auditorEmail,auditorName:item.auditorName,blocks:item.blocks,waiverAccepted:false,actorRole:'MANAGER',lockWaitMs:item.lockWaitMs});gateOk=!!(gate&&gate.canCommit===true);}var reason=!revisionOk?(r&&r.reason||'PRECHECK_FAILED'):(!statusOk?'STATUS_NOT_PENDING_PLANNING':(gateOk?'DRY_RUN_VALID':PWB_gateReason_(gate)));return{auditId:item.auditId,ok:revisionOk&&statusOk&&gateOk,reason:reason,status:status,canonicalGate:gate,canonicalGateAccepted:gateOk};}
function PlanningWorkspaceBulkConceptService_save(input){input=input||{};if(typeof ConceptReservationCommandService_upsert!=='function')throw new Error('PlanningWorkspaceBulkConceptService: ConceptReservationCommandService_upsert unavailable');if(typeof PlanningCommitGateService_evaluate!=='function')throw new Error('PlanningWorkspaceBulkConceptService: PlanningCommitGateService_evaluate unavailable');var items=PWB_items_(input),pre=[];for(var i=0;i<items.length;i++)pre.push(PWB_precheck_(items[i]));var bad=pre.filter(function(x){return!x.ok;});if(bad.length)return{success:true,build:PLANNING_WORKSPACE_BULK_CONCEPT_SERVICE_BUILD,saved:false,reason:'BATCH_PREFLIGHT_FAILED',precheck:pre,results:[],meta:{writes:false,preliminaryOnly:true,atomicPrecheck:true,statusGuard:'Pending Planning',canonicalGateOwner:'PlanningCommitGateService',canonicalGateRequired:true,canonicalWrites:false,newSsot:false,owner:'ConceptReservationCommandService'}};if(input.dryRun===true)return{success:true,build:PLANNING_WORKSPACE_BULK_CONCEPT_SERVICE_BUILD,saved:false,reason:'DRY_RUN_VALID',precheck:pre,results:[],meta:{writes:false,preliminaryOnly:true,statusGuard:'Pending Planning',canonicalGateOwner:'PlanningCommitGateService',canonicalGateRequired:true,canonicalWrites:false,availabilityWrites:false,statusWrites:false,newSsot:false,owner:'ConceptReservationCommandService'}};var results=[];for(var j=0;j<items.length;j++){var out=ConceptReservationCommandService_upsert(items[j]);results.push({auditId:items[j].auditId,saved:!!(out&&out.saved===true),reason:out&&out.reason||'SAVE_FAILED',rowNumber:out&&out.rowNumber||0});if(!(out&&out.saved===true))break;}var savedCount=results.filter(function(x){return x.saved;}).length,all=savedCount===items.length;return{success:true,build:PLANNING_WORKSPACE_BULK_CONCEPT_SERVICE_BUILD,saved:all,reason:all?'SAVED':'PARTIAL_WRITE_REQUIRES_REVIEW',precheck:pre,results:results,meta:{writes:savedCount>0,preliminaryOnly:true,statusGuard:'Pending Planning',canonicalGateOwner:'PlanningCommitGateService',canonicalGateRequired:true,canonicalWrites:false,availabilityWrites:false,statusWrites:false,newSsot:false,owner:'ConceptReservationCommandService',requested:items.length,savedCount:savedCount,partialFailurePossibleAfterPrecheck:true}};}
function PlanningWorkspaceBulkConceptService_contract(){return{build:PLANNING_WORKSPACE_BULK_CONCEPT_SERVICE_BUILD,maxItems:25,owner:'ConceptReservationCommandService',atomicPrecheck:true,statusGuard:'Pending Planning',canonicalGateOwner:'PlanningCommitGateService',canonicalGateRequired:true,canonicalWrites:false,availabilityWrites:false,statusWrites:false,newSsot:false};}
