/***********************************************************************
 * PlanningWorkspaceBulkCanonicalLivePreviewTests.js
 * BUILD: 2026-09-10_PLANNING_WORKSPACE_BULK_CANONICAL_LIVE_PREVIEW_R1
 * Live DEV/read-only verification. Never performs canonical writes.
 ***********************************************************************/
var PLANNING_WORKSPACE_BULK_CANONICAL_LIVE_PREVIEW_BUILD='2026-09-10_PLANNING_WORKSPACE_BULK_CANONICAL_LIVE_PREVIEW_R1';
function PWBCLP_nextWeekday_(s){var p=String(s||'').split('-'),d=new Date(Number(p[0]),Number(p[1])-1,Number(p[2]));while(d.getDay()===0||d.getDay()===6)d.setDate(d.getDate()+1);return Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}
function PWBCLP_blocks_(row){var req=Math.max(1,Number(row&&row.hoursToPlan||0)||1),date=PWBCLP_nextWeekday_(row&&row.planningWindowFrom||''),to=String(row&&row.planningWindowTo||''),out=[];while(req>0&&date&&(!to||date<=to)&&out.length<20){var h=Math.min(8,req),end=9+h;out.push({date:date,start:'09:00',end:String(Math.floor(end)).padStart(2,'0')+':00',hours:h});req-=h;if(req>0){var p=String(date).split('-'),d=new Date(Number(p[0]),Number(p[1])-1,Number(p[2]));do{d.setDate(d.getDate()+1);}while(d.getDay()===0||d.getDay()===6);date=Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}}return out;}
function RUN_PLANNING_WORKSPACE_BULK_CANONICAL_LIVE_PREVIEW(){var r=[];function t(n,o,d){r.push({name:n,ok:!!o,detail:o?'':String(d||'failed')});}var demand=PlanningDemandService_get({from:'2026-09-01',to:'2027-08-31',status:'Pending Planning',limit:500,includeCompanyMeta:false}),rows=demand&&demand.rows||[],chosen=null,preview=null,email='',rev=null,blocks=[];t('demandLiveRead',demand&&demand.success===true);for(var i=0;i<rows.length&&i<10;i++){var x=rows[i]||{},rv=PlanningRevisionTokenService_get({auditId:x.auditId}),bs=PWBCLP_blocks_(x),em=String(x.preassignedAuditor||x.assignedTo||'').trim().toLowerCase();if(em.indexOf('@')<0)em='david@agriqa.es';var p=PlanningWorkspaceBulkCanonicalPlanningService_preview({items:[{auditId:x.auditId,auditorEmail:em,blocks:bs,expectedRevision:rv&&rv.revision||'',sourceRevision:rv&&rv.revision||''}]});if(p&&p.canCommit===true){chosen=x;preview=p;email=em;rev=rv;blocks=bs;break;}}t('canonicalReadyPendingPlanningFound',!!chosen,'No canonically READY Pending Planning audit found in bounded sample');if(chosen){t('revisionLoaded',!!(rev&&rev.revision));t('blocksPrepared',blocks.length>0);t('previewSuccess',preview&&preview.success===true&&preview.reason==='BATCH_PREFLIGHT_ACCEPTED');t('previewCanCommit',preview&&preview.canCommit===true);t('previewNoWrites',preview&&preview.meta&&preview.meta.writes===false&&preview.meta.canonicalWrites===false);t('allMustPass',preview&&preview.meta&&preview.meta.allMustPass===true&&preview.meta.applyOkOnly===false);t('ownersPreserved',preview&&preview.meta&&preview.meta.preflightOwner==='PlanningCommitGateService'&&preview.meta.commitOwner==='PlanningCanonicalCommitService');}else{t('revisionLoaded',false,'Skipped');t('blocksPrepared',false,'Skipped');t('previewSuccess',false,'Skipped');t('previewCanCommit',false,'Skipped');t('previewNoWrites',false,'Skipped');t('allMustPass',false,'Skipped');t('ownersPreserved',false,'Skipped');}var f=r.filter(function(x){return!x.ok;}).length,out={ok:f===0,build:PLANNING_WORKSPACE_BULK_CANONICAL_LIVE_PREVIEW_BUILD,total:r.length,passed:r.length-f,failed:f,results:r,meta:{nonDestructive:true,liveReadsPerformed:true,liveWritesPerformed:false,selectedAuditId:chosen&&chosen.auditId||'',selectedAuditorEmail:email,bulkCanonicalPreview:true,canonicalWrites:false}};Logger.log(JSON.stringify(out,null,2));return out;}
