/***********************************************************************
 * PlanningCommitGateService.js
 * BUILD: 2026-09-16_ROADMAP_2_4_PLANNING_COMMIT_GATE_R4_BULK_PREVIEW_REVISION
 * Commit remains fresh + locked. Preview may reuse a canonical bulk revision
 * read; canonical planning preflight still executes per audit. No writes.
 ***********************************************************************/
var PLANNING_COMMIT_GATE_BUILD='2026-09-16_ROADMAP_2_4_PLANNING_COMMIT_GATE_R4_BULK_PREVIEW_REVISION';
function PCG_clean_(v){return String(v==null?'':v).trim();}
function PCG_requiredFunctions_(){return{lock:typeof Platform_withLock==='function',revision:typeof PlanningRevisionTokenService_get==='function',guard:typeof PlanningOptimisticRevisionGuard_evaluate==='function',preflight:typeof PlanningCommitPreflightService_evaluate==='function'};}
function PCG_assertDependencies_(){var f=PCG_requiredFunctions_();if(!f.lock)throw new Error('PlanningCommitGateService: Platform_withLock unavailable');if(!f.revision)throw new Error('PlanningCommitGateService: PlanningRevisionTokenService_get unavailable');if(!f.guard)throw new Error('PlanningCommitGateService: PlanningOptimisticRevisionGuard_evaluate unavailable');if(!f.preflight)throw new Error('PlanningCommitGateService: PlanningCommitPreflightService_evaluate unavailable');}
function PCG_conflictResult_(auditId,expectedRevision,revisionRead,guard,lockMode){return{success:true,build:PLANNING_COMMIT_GATE_BUILD,auditId:auditId,canCommit:false,reason:guard&&guard.reason||'REVISION_CONFLICT',revisionAccepted:false,currentRevision:revisionRead&&revisionRead.revision||'',expectedRevision:expectedRevision,revision:revisionRead||null,revisionGuard:guard||null,preflight:null,meta:{writes:false,readOnly:true,lockUsed:lockMode!=='READ_ONLY_PREVIEW',lockMode:lockMode||'CALLER_OWNED',conflictFastPath:true,preflightSkippedOnConflict:true,canonicalPreflightPerformed:false,futureWriteAllowed:false,canonicalPlanningOwner:'Audit planning',revisionRole:'derived concurrency token only'}};}
function PCG_successResult_(auditId,expectedRevision,revisionRead,guard,preflight,lockMode){var canCommit=!!(guard&&guard.accepted===true&&preflight&&preflight.canCommit===true);return{success:true,build:PLANNING_COMMIT_GATE_BUILD,auditId:auditId,canCommit:canCommit,reason:canCommit?'GATE_ACCEPTED':(preflight&&preflight.decisionReason||'PREFLIGHT_BLOCKED'),revisionAccepted:!!(guard&&guard.accepted===true),currentRevision:revisionRead&&revisionRead.revision||'',expectedRevision:expectedRevision,revision:revisionRead||null,revisionGuard:guard||null,preflight:preflight||null,meta:{writes:false,readOnly:true,lockUsed:lockMode!=='READ_ONLY_PREVIEW',lockMode:lockMode||'CALLER_OWNED',conflictFastPath:false,preflightSkippedOnConflict:false,canonicalPreflightPerformed:true,futureWriteAllowed:canCommit,canonicalPlanningOwner:'Audit planning',revisionRole:'derived concurrency token only'}};}
function PCG_evaluateCore_(input,perf,lockMode,providedRevision){input=input||{};var auditId=PCG_clean_(input.auditId),expectedRevision=PCG_clean_(input.expectedRevision);if(!auditId)throw new Error('PlanningCommitGateService: auditId is required');if(!expectedRevision)throw new Error('PlanningCommitGateService: expectedRevision is required');PCG_assertDependencies_();var revisionRead=providedRevision||PlanningRevisionTokenService_get({auditId:auditId});if(!revisionRead||PCG_clean_(revisionRead.auditId)!==auditId||!PCG_clean_(revisionRead.revision))throw new Error('PlanningCommitGateService: valid canonical revision read required for '+auditId);if(typeof DPL_mark_==='function')DPL_mark_(perf,'revisionReread',{revisionPrefix:PCG_clean_(revisionRead.revision).substring(0,9),lockMode:lockMode,provided:!!providedRevision});var guard=PlanningOptimisticRevisionGuard_evaluate({auditId:auditId,expectedRevision:expectedRevision,currentRevision:revisionRead.revision});if(typeof DPL_mark_==='function')DPL_mark_(perf,'revisionGuard',{accepted:guard&&guard.accepted===true,conflict:guard&&guard.conflict===true,reason:guard&&guard.reason||''});if(!guard||guard.accepted!==true)return PCG_conflictResult_(auditId,expectedRevision,revisionRead,guard,lockMode);var preflight=PlanningCommitPreflightService_evaluate({auditId:auditId,auditorEmail:input.auditorEmail,auditorName:input.auditorName,blocks:input.blocks,waiverAccepted:input.waiverAccepted===true});if(typeof DPL_mark_==='function')DPL_mark_(perf,'canonicalPreflight',{canCommit:preflight&&preflight.canCommit===true,overallLevel:preflight&&preflight.overallLevel||'',reason:preflight&&preflight.decisionReason||''});return PCG_successResult_(auditId,expectedRevision,revisionRead,guard,preflight,lockMode);}
function PlanningCommitGateService_evaluateLocked_(input,perf){return PCG_evaluateCore_(input,perf,'CALLER_OWNED',null);}
function PlanningCommitGateService_evaluate(input){input=input||{};var auditId=PCG_clean_(input.auditId),expectedRevision=PCG_clean_(input.expectedRevision);if(!auditId)throw new Error('PlanningCommitGateService: auditId is required');if(!expectedRevision)throw new Error('PlanningCommitGateService: expectedRevision is required');PCG_assertDependencies_();var perf=typeof DPL_start_==='function'?DPL_start_('PlanningCommitGateService_evaluate',{auditId:auditId,blockCount:Array.isArray(input.blocks)?input.blocks.length:0}):null,lockWaitMs=Math.max(500,Math.min(10000,Number(input.lockWaitMs||3000)||3000)),result=Platform_withLock('planning-commit:'+auditId,function(){var locked=PlanningCommitGateService_evaluateLocked_(input,perf);if(locked&&locked.meta)locked.meta.lockMode='SERVICE_OWNED';return locked;},lockWaitMs);if(typeof DPL_end_==='function')result.devPerformance=DPL_end_(perf,{canCommit:result&&result.canCommit===true,reason:result&&result.reason||'',conflictFastPath:!!(result&&result.meta&&result.meta.conflictFastPath)});return result;}
function PlanningCommitGateService_preview(input){input=input||{};var perf=typeof DPL_start_==='function'?DPL_start_('PlanningCommitGateService_preview',{auditId:PCG_clean_(input.auditId),blockCount:Array.isArray(input.blocks)?input.blocks.length:0}):null,result=PCG_evaluateCore_(input,perf,'READ_ONLY_PREVIEW',null);if(typeof DPL_end_==='function')result.devPerformance=DPL_end_(perf,{canCommit:result&&result.canCommit===true,reason:result&&result.reason||'',lockUsed:false});return result;}
function PlanningCommitGateService_previewWithRevision(input,revisionRead){input=input||{};var perf=typeof DPL_start_==='function'?DPL_start_('PlanningCommitGateService_previewWithRevision',{auditId:PCG_clean_(input.auditId),blockCount:Array.isArray(input.blocks)?input.blocks.length:0}):null,result=PCG_evaluateCore_(input,perf,'READ_ONLY_PREVIEW',revisionRead);if(result&&result.meta)result.meta.revisionReadReused=true;if(typeof DPL_end_==='function')result.devPerformance=DPL_end_(perf,{canCommit:result&&result.canCommit===true,reason:result&&result.reason||'',lockUsed:false,revisionReadReused:true});return result;}
function PlanningCommitGateService_contract(){return{build:PLANNING_COMMIT_GATE_BUILD,commitEndpoint:'PlanningCommitGateService_evaluate',previewEndpoint:'PlanningCommitGateService_preview',batchPreviewEndpoint:'PlanningCommitGateService_previewWithRevision',meta:{writes:false,commitLock:true,previewLock:false,previewReadOnly:true,batchPreviewBulkRevisionCompatible:true,commitRevalidationRequired:true,canonicalPlanningOwner:'Audit planning',revisionRole:'derived concurrency token only',newSsot:false}};}
