/***********************************************************************
 * PlanningWorkspaceRpc.js
 * BUILD: 2026-09-09_PLANNING_WORKSPACE_2_0_RPC_R6_STATUS_AWARE_PREFLIGHT
 * Browser-facing RPC boundary. Thin delegation only.
 ***********************************************************************/
var PLANNING_WORKSPACE_RPC_BUILD='2026-09-09_PLANNING_WORKSPACE_2_0_RPC_R6_STATUS_AWARE_PREFLIGHT';
function PWR_clean_(v){return String(v==null?'':v).trim();}
function PWR_envelope_(action,fn){var started=Date.now();try{var data=fn();return{ok:true,build:PLANNING_WORKSPACE_RPC_BUILD,action:action,data:data,error:null,durationMs:Date.now()-started};}catch(e){return{ok:false,build:PLANNING_WORKSPACE_RPC_BUILD,action:action,data:null,error:{message:String(e&&e.message||e)},durationMs:Date.now()-started};}}
function PWR_assertDevCommit_(input){var isDev=(typeof V5_ENTRY_isDevEnv_==='function'&&V5_ENTRY_isDevEnv_()===true);if(!isDev)throw new Error('PLANNING_WORKSPACE_COMMIT_DEV_ONLY');if(input.confirmCanonicalCommit!==true)throw new Error('CANONICAL_COMMIT_CONFIRMATION_REQUIRED');}
function PlanningWorkspaceRpc_loadAdvisory(input){input=input||{};return PWR_envelope_('loadAdvisory',function(){return PlanningWorkspaceService_getAdvisory(input);});}
function PlanningWorkspaceRpc_loadOverlays(input){input=input||{};return PWR_envelope_('loadOverlays',function(){return PlanningWorkspaceService_getOverlays({from:input.from||input.start||input.periodFrom||'',to:input.to||input.end||input.periodTo||'',auditorEmails:input.auditorEmails||input.candidateAuditorEmails||[],auditIds:input.auditIds||[]});});}
function PlanningWorkspaceRpc_bootstrap(input){input=input||{};return PWR_envelope_('bootstrap',function(){var advisory=PlanningWorkspaceService_getAdvisory(input),overlayInput={from:input.from||input.start||input.periodFrom||'',to:input.to||input.end||input.periodTo||'',auditorEmails:input.auditorEmails||[],auditIds:input.auditIds||[]};var overlays=PlanningWorkspaceService_getOverlays(overlayInput);return{advisory:advisory,overlays:overlays,meta:{coarseGrained:true,uiBootstrap:true,serviceFacadeOnly:true,legacyCombinedBootstrap:true}};});}
function PlanningWorkspaceRpc_getRevision(input){input=input||{};return PWR_envelope_('getRevision',function(){var auditId=PWR_clean_(input.auditId);if(!auditId)throw new Error('auditId required');return PlanningRevisionTokenService_get({auditId:auditId});});}
function PlanningWorkspaceRpc_saveConcept(input){return PWR_envelope_('saveConcept',function(){return PlanningWorkspaceService_saveConcept(input||{});});}
function PlanningWorkspaceRpc_releaseConcept(input){return PWR_envelope_('releaseConcept',function(){return PlanningWorkspaceService_releaseConcept(input||{});});}
function PlanningWorkspaceRpc_commitPreflight(input){input=input||{};return PWR_envelope_('commitPreflight',function(){var auditId=PWR_clean_(input.auditId),expectedRevision=PWR_clean_(input.expectedRevision);if(!auditId)throw new Error('auditId required');if(!expectedRevision)throw new Error('expectedRevision required');if(!Array.isArray(input.blocks)||!input.blocks.length)throw new Error('blocks required');return PlanningCommitGateService_evaluate({auditId:auditId,expectedRevision:expectedRevision,auditorEmail:input.auditorEmail,auditorName:input.auditorName,blocks:input.blocks,waiverAccepted:input.waiverAccepted===true,actorRole:PWR_clean_(input.actorRole||'MANAGER').toUpperCase(),lockWaitMs:input.lockWaitMs});});}
function PlanningWorkspaceRpc_commit(input){input=input||{};return PWR_envelope_('commit',function(){PWR_assertDevCommit_(input);var auditId=PWR_clean_(input.auditId),expectedRevision=PWR_clean_(input.expectedRevision);if(!auditId)throw new Error('auditId required');if(!expectedRevision)throw new Error('expectedRevision required');if(!Array.isArray(input.blocks)||!input.blocks.length)throw new Error('blocks required');return PlanningWorkspaceService_commit({auditId:auditId,expectedRevision:expectedRevision,auditorEmail:input.auditorEmail,auditorName:input.auditorName,blocks:input.blocks,waiverAccepted:input.waiverAccepted===true,actorRole:PWR_clean_(input.actorRole||'MANAGER').toUpperCase(),actorEmail:PWR_clean_(input.actorEmail||''),allowWeekendOverride:input.allowWeekendOverride!==false,lockWaitMs:input.lockWaitMs});});}
function PlanningWorkspaceRpc_contract(){return{build:PLANNING_WORKSPACE_RPC_BUILD,endpoints:['PlanningWorkspaceRpc_loadAdvisory','PlanningWorkspaceRpc_loadOverlays','PlanningWorkspaceRpc_bootstrap','PlanningWorkspaceRpc_getRevision','PlanningWorkspaceRpc_saveConcept','PlanningWorkspaceRpc_releaseConcept','PlanningWorkspaceRpc_commitPreflight','PlanningWorkspaceRpc_commit'],meta:{browserFacing:true,coarseGrained:true,splitFirstPaint:true,targetedOverlayPhase:true,legacyCombinedBootstrapRetained:true,directSheetReads:false,directSheetWrites:false,canonicalOwnersBypassed:false,newSsot:false,revisionOwner:'PlanningRevisionTokenService',commitPreflightOwner:'PlanningCommitGateService',commitOwner:'PlanningCanonicalCommitService via PlanningWorkspaceService',canonicalCommitDevOnly:true,canonicalCommitExplicitConfirmation:true,statusAwarePreflight:true}};}
