/***********************************************************************
 * PlanningWorkspaceRpc.js
 * BUILD: 2026-09-24_AMS03_WORKSPACE_RPC_R19_ROLE_SCOPE
 ***********************************************************************/
var PLANNING_WORKSPACE_RPC_BUILD='2026-09-24_AMS03_WORKSPACE_RPC_R19_ROLE_SCOPE';
function PWR_clean_(v){return String(v==null?'':v).trim();}function PWR_normEmail_(v){return PWR_clean_(v).toLowerCase();}
function PWR_jsonChars_(v){try{return JSON.stringify(v).length;}catch(e){return-1;}}
function PWR_envelope_(action,fn){var started=Date.now();try{return{ok:true,build:PLANNING_WORKSPACE_RPC_BUILD,action:action,data:fn(),error:null,durationMs:Date.now()-started};}catch(e){return{ok:false,build:PLANNING_WORKSPACE_RPC_BUILD,action:action,data:null,error:{message:String(e&&e.message||e)},durationMs:Date.now()-started};}}
function PWR_candidateEmails_(advisory){var out=[],seen={},rows=advisory&&Array.isArray(advisory.rows)?advisory.rows:[];for(var i=0;i<rows.length;i++){var a=rows[i]&&Array.isArray(rows[i].candidateAuditors)?rows[i].candidateAuditors:[];for(var c=0;c<a.length;c++){var e=PWR_normEmail_(a[c]&&a[c].email);if(e&&!seen[e]){seen[e]=1;out.push(e);}}}return out;}
function PWR_overlayInput_(input,auditorEmails,auditContextById){input=input||{};return{from:input.from||input.start||input.periodFrom||'',to:input.to||input.end||input.periodTo||'',auditorEmails:Array.isArray(auditorEmails)?auditorEmails:(input.auditorEmails||[]),auditIds:input.auditIds||[],auditContextById:auditContextById||{}};}
function PWR_auditContext_(advisory){var out={},rows=advisory&&Array.isArray(advisory.rows)?advisory.rows:[];for(var i=0;i<rows.length;i++){var r=rows[i]||{},id=PWR_clean_(r.auditId);if(!id)continue;out[id]={company:PWR_clean_(r.company),scopes:Array.isArray(r.scopes)?r.scopes.slice():[],status:PWR_clean_(r.status)};}return out;}
function PWR_conceptInput_(input){input=input||{};var out={};for(var k in input)if(Object.prototype.hasOwnProperty.call(input,k))out[k]=input[k];if(!PWR_clean_(out.sourceRevision||out.expectedRevision)){var rr=PlanningRevisionTokenService_get({auditId:PWR_clean_(out.auditId)});out.sourceRevision=PWR_clean_(rr&&rr.revision);if(!out.sourceRevision)throw new Error('PlanningWorkspaceRpc: canonical planning revision unavailable');}return out;}
function PWR_commandInput_(input){input=input||{};var out={};for(var k in input)if(Object.prototype.hasOwnProperty.call(input,k))out[k]=input[k];if(!PWR_clean_(out.expectedRevision)){var rr=PlanningRevisionTokenService_get({auditId:PWR_clean_(out.auditId)});out.expectedRevision=PWR_clean_(rr&&rr.revision);if(!out.expectedRevision)throw new Error('PlanningWorkspaceRpc: canonical planning revision unavailable');}return out;}
function PWR_batchCommandInput_(input){input=input||{};var out={actorRole:PWR_clean_(input.actorRole||'MANAGER'),actorEmail:PWR_clean_(input.actorEmail),items:[]},items=Array.isArray(input.items)?input.items:[],missing=[],seen={};for(var i=0;i<items.length;i++){var src=items[i]||{},copy={};for(var k in src)if(Object.prototype.hasOwnProperty.call(src,k))copy[k]=src[k];copy.auditId=PWR_clean_(copy.auditId);copy.auditorEmail=PWR_normEmail_(copy.auditorEmail);if(!PWR_clean_(copy.expectedRevision)&&copy.auditId&&!seen[copy.auditId]){seen[copy.auditId]=1;missing.push(copy.auditId);}out.items.push(copy);}var revisions={};if(missing.length){var rr=PlanningRevisionTokenService_getMany({auditIds:missing});revisions=rr&&rr.byAuditId||{};}for(var j=0;j<out.items.length;j++){var x=out.items[j];if(!PWR_clean_(x.expectedRevision))x.expectedRevision=PWR_clean_(revisions[x.auditId]);if(!PWR_clean_(x.expectedRevision))throw new Error('PlanningWorkspaceRpc: canonical planning revision unavailable for '+x.auditId);}return out;}
function PWR_conceptPreflight_(input){return PlanningCommitGateService_evaluate({auditId:PWR_clean_(input.auditId),expectedRevision:PWR_clean_(input.sourceRevision||input.expectedRevision),auditorEmail:PWR_normEmail_(input.auditorEmail),auditorName:PWR_clean_(input.auditorName),blocks:Array.isArray(input.blocks)?input.blocks:[],waiverAccepted:input.waiverAccepted===true});}
function PWR_saveConcept_(input){var p=PWR_conceptInput_(input),g=PWR_conceptPreflight_(p);if(!g||g.canCommit!==true)return{success:true,saved:false,reason:g&&g.reason||'CONCEPT_PREFLIGHT_BLOCKED',preflightGate:g||null,meta:{writes:false,conceptPreflight:true,canonicalValidatorOwner:'PlanningCommitGateService_evaluate',canonicalRulesReimplemented:false}};var s=PlanningWorkspaceService_saveConcept(p);if(s&&typeof s==='object'){s.preflightGate=g;s.meta=s.meta||{};s.meta.conceptPreflight=true;s.meta.canonicalValidatorOwner='PlanningCommitGateService_evaluate';s.meta.canonicalRulesReimplemented=false;}return s;}
function PWR_roleScope_(input){input=input||{};var role=PWR_clean_(input.actorRole||input.role).toUpperCase(),actor=PWR_normEmail_(input.actorEmail||input.auditorEmail);if(role!=='AUDITOR')return input;if(!actor)throw new Error('PlanningWorkspaceRpc: auditor actorEmail is required');input.actorRole='AUDITOR';input.actorEmail=actor;input.auditorEmail=actor;return input;}
function PWR_enforceAuditorCommand_(input){input=PWR_roleScope_(input||{});if(PWR_clean_(input.actorRole).toUpperCase()==='AUDITOR'){var actor=PWR_normEmail_(input.actorEmail),aud=PWR_normEmail_(input.auditorEmail);if(!actor||aud!==actor)throw new Error('PlanningWorkspaceRpc: auditor may plan only for self');input.auditorEmail=actor;}return input;}
function PlanningWorkspaceRpc_getAdvisory(input){return PWR_envelope_('getAdvisory',function(){return PlanningWorkspaceService_getAdvisory(input||{});});}
function PlanningWorkspaceRpc_getOverlays(input){return PWR_envelope_('getOverlays',function(){input=input||{};return PlanningWorkspaceService_getOverlays(PWR_overlayInput_(input,input.auditorEmails||[]));});}
function PlanningWorkspaceRpc_bootstrap(input){input=PWR_roleScope_(input||{});if(!Object.prototype.hasOwnProperty.call(input,'includeCompanyMeta'))input.includeCompanyMeta=false;return PWR_envelope_('bootstrap',function(){var t0=Date.now(),a=PlanningWorkspaceService_getDecision(input),t1=Date.now(),e=Array.isArray(a&&a.candidateAuditorEmails)?a.candidateAuditorEmails:PWR_candidateEmails_(a),ctx=a&&a.auditContextById||PWR_auditContext_(a),t2=Date.now(),o=PlanningWorkspaceService_getOverlays(PWR_overlayInput_(input,e,ctx)),t3=Date.now(),aChars=PWR_jsonChars_(a),oChars=PWR_jsonChars_(o),payloadChars=aChars>=0&&oChars>=0?aChars+oChars:-1;return{advisory:a,overlays:o,meta:{coarseGrained:true,uiBootstrap:true,serviceFacadeOnly:true,compactDecisionModel:true,decisionReadModelBuild:a&&a.build||'',candidateAuditors:e.length,overlayBoundedToCandidates:true,stageMs:{advisory:t1-t0,candidateProjection:t2-t1,overlays:t3-t2,serverTotal:t3-t0},payload:{advisoryChars:aChars,overlayChars:oChars,dataCharsApprox:payloadChars,diagnosticOnly:true}}};});}
function PlanningWorkspaceRpc_saveConcept(input){return PWR_envelope_('saveConcept',function(){return PWR_saveConcept_(PWR_enforceAuditorCommand_(input||{}));});}
function PlanningWorkspaceRpc_saveConceptsBatch(input){return PWR_envelope_('saveConceptsBatch',function(){input=input||{};var items=Array.isArray(input.items)?input.items:[],ids=items.map(function(x){return PWR_clean_(x&&x.auditId)}),rr=PlanningRevisionTokenService_getMany({auditIds:ids}),by=rr&&rr.byAuditId||{},prepared=[];for(var i=0;i<items.length;i++){var x={},src=items[i]||{};for(var k in src)if(Object.prototype.hasOwnProperty.call(src,k))x[k]=src[k];x.auditId=PWR_clean_(x.auditId);x.auditorEmail=PWR_normEmail_(x.auditorEmail);x.sourceRevision=PWR_clean_(x.sourceRevision||by[x.auditId]);if(!x.sourceRevision)throw new Error('PlanningWorkspaceRpc: canonical planning revision unavailable for '+x.auditId);var g=PWR_conceptPreflight_(x);if(!g||g.canCommit!==true)return{success:true,saved:false,reason:g&&g.reason||'CONCEPT_PREFLIGHT_BLOCKED',auditId:x.auditId,preflightGate:g||null,meta:{writes:false,batch:true}};prepared.push(x);}return ConceptReservationCommandService_upsertBatch({items:prepared});});}function PlanningWorkspaceRpc_releaseConcept(input){return PWR_envelope_('releaseConcept',function(){return PlanningWorkspaceService_releaseConcept(input||{});});}function PlanningWorkspaceRpc_commit(input){return PWR_envelope_('commit',function(){return PlanningWorkspaceService_commit(PWR_enforceAuditorCommand_(input||{}));});}
function PlanningWorkspaceRpc_batchPreflight(input){return PWR_envelope_('batchPreflight',function(){return PlanningWorkspaceService_batchPreflight(PWR_batchCommandInput_(PWR_enforceAuditorCommand_(input||{})));});}function PlanningWorkspaceRpc_batchCommit(input){return PWR_envelope_('batchCommit',function(){return PlanningWorkspaceService_batchCommit(PWR_batchCommandInput_(PWR_enforceAuditorCommand_(input||{})));});}
function PlanningWorkspaceRpc_getPlannedAudit(input){return PWR_envelope_('getPlannedAudit',function(){return PlanningWorkspaceService_getPlannedAudit(input||{});});}function PlanningWorkspaceRpc_modifyPlanned(input){return PWR_envelope_('modifyPlanned',function(){return PlanningWorkspaceService_modifyPlanned(PWR_commandInput_(input||{}));});}function PlanningWorkspaceRpc_cancelPlanned(input){return PWR_envelope_('cancelPlanned',function(){return PlanningWorkspaceService_cancelPlanned(PWR_commandInput_(input||{}));});}
function PlanningWorkspaceRpc_contract(){return{build:PLANNING_WORKSPACE_RPC_BUILD,endpoints:['PlanningWorkspaceRpc_getAdvisory','PlanningWorkspaceRpc_getOverlays','PlanningWorkspaceRpc_bootstrap','PlanningWorkspaceRpc_saveConcept','PlanningWorkspaceRpc_saveConceptsBatch','PlanningWorkspaceRpc_releaseConcept','PlanningWorkspaceRpc_commit','PlanningWorkspaceRpc_batchPreflight','PlanningWorkspaceRpc_batchCommit','PlanningWorkspaceRpc_getPlannedAudit','PlanningWorkspaceRpc_modifyPlanned','PlanningWorkspaceRpc_cancelPlanned'],meta:{browserFacing:true,coarseGrained:true,singleDecisionRpc:true,batchPreflightSingleRpc:true,batchPreflightReadOnly:true,batchCommitSingleRpc:true,batchRevisionHydrationBulk:true,batchRevisionHydrationPhysicalReads:'NARROW_INDEX_PLUS_ONE_BOUNDED_RANGE_PLUS_CACHE',batchRevisionHydrationTotalReadTelemetry:true,batchRevisionHydrationPhysicalNPlusOnePossible:false,batchCommitBounded:true,stageDiagnostics:true,payloadDiagnostics:true,overlayBoundedToCandidates:true,conceptDropRevisionHydration:true,conceptDropCanonicalPreflight:true,conceptDropPreflightOwner:'PlanningCommitGateService_evaluate',plannedDetailOnDemand:true,plannedCommandRevisionHydration:true,modifyPlannedCanonicalCommand:true,cancelPlannedCanonicalCommand:true,directSheetReads:false,directSheetWrites:false,canonicalOwnersBypassed:false,newSsot:false}};}
