/***********************************************************************
 * PlanningBatchPreflightService.js
 * BUILD: 2026-09-16_ROADMAP_2_4_BATCH_PREFLIGHT_R3_BULK_REVISION_PREVIEW
 * Read-only bounded preview. One bulk revision reread, no write locks.
 * Commit remains authoritative and performs fresh locked revalidation.
 ***********************************************************************/
var PLANNING_BATCH_PREFLIGHT_BUILD='2026-09-16_ROADMAP_2_4_BATCH_PREFLIGHT_R3_BULK_REVISION_PREVIEW';
var PLANNING_BATCH_PREFLIGHT_MAX_ITEMS=20;
function PBP_clean_(v){return String(v==null?'':v).trim();}
function PBP_normalize_(input){input=input||{};var items=Array.isArray(input.items)?input.items:[];if(!items.length)throw new Error('PlanningBatchPreflightService: items are required');if(items.length>PLANNING_BATCH_PREFLIGHT_MAX_ITEMS)throw new Error('PlanningBatchPreflightService: maximum 20 items per batch');var out=[],seen={};for(var i=0;i<items.length;i++){var x=items[i]||{},id=PBP_clean_(x.auditId);if(!id)throw new Error('PlanningBatchPreflightService: auditId is required for item '+(i+1));if(seen[id])throw new Error('PlanningBatchPreflightService: duplicate auditId '+id);seen[id]=1;if(!PBP_clean_(x.expectedRevision))throw new Error('PlanningBatchPreflightService: expectedRevision is required for '+id);if(!Array.isArray(x.blocks)||!x.blocks.length)throw new Error('PlanningBatchPreflightService: blocks are required for '+id);out.push({auditId:id,expectedRevision:PBP_clean_(x.expectedRevision),auditorEmail:PBP_clean_(x.auditorEmail).toLowerCase(),auditorName:PBP_clean_(x.auditorName),blocks:x.blocks,waiverAccepted:x.waiverAccepted===true});}return out;}
function PBP_revisionReads_(items){if(typeof PlanningRevisionTokenService_getMany!=='function')throw new Error('PlanningBatchPreflightService: PlanningRevisionTokenService_getMany unavailable');var b=PlanningRevisionTokenService_getMany({auditIds:items.map(function(x){return x.auditId;})}),by={};(b.items||[]).forEach(function(x){by[x.auditId]=x;});return{bulk:b,byAuditId:by};}
function PlanningBatchPreflightService_evaluate(input){if(typeof PlanningCommitGateService_previewWithRevision!=='function')throw new Error('PlanningBatchPreflightService: PlanningCommitGateService_previewWithRevision unavailable');var items=PBP_normalize_(input),started=Date.now(),rr=PBP_revisionReads_(items),outcomes=[],ready=0,blocked=0,errors=0;for(var i=0;i<items.length;i++){var x=items[i],t0=Date.now(),gate=null,error=null;try{gate=PlanningCommitGateService_previewWithRevision(x,rr.byAuditId[x.auditId]);}catch(e){error=e;}var canCommit=!error&&gate&&gate.canCommit===true;if(canCommit)ready++;else if(error)errors++;else blocked++;outcomes.push({auditId:x.auditId,ok:!error,canCommit:canCommit,reason:error?'EXCEPTION':PBP_clean_(gate&&gate.reason),message:error?PBP_clean_(error&&error.message||error):'',elapsedMs:Date.now()-t0,gate:gate||null});}return{success:errors===0,build:PLANNING_BATCH_PREFLIGHT_BUILD,requested:items.length,ready:ready,blocked:blocked,errors:errors,allReady:ready===items.length,outcomes:outcomes,durationMs:Date.now()-started,meta:{readOnly:true,writes:false,bounded:true,maxItems:20,perItemCanonicalGate:true,canonicalGateOwner:'PlanningCommitGateService_previewWithRevision',previewLock:false,bulkRevisionReread:true,bulkRevisionReadCount:1,revisionOwner:'PlanningRevisionTokenService_getMany',commitRevalidationRequired:true,newSsot:false,directSheetWrites:false}};}
function PlanningBatchPreflightService_contract(){return{build:PLANNING_BATCH_PREFLIGHT_BUILD,maxItems:20,dependency:'PlanningCommitGateService_previewWithRevision',revisionDependency:'PlanningRevisionTokenService_getMany',meta:{readOnly:true,writes:false,bounded:true,perItemCanonicalGate:true,previewLock:false,bulkRevisionReread:true,bulkRevisionReadCount:1,commitRevalidationRequired:true,newSsot:false,directSheetWrites:false}};}
