var EXTERNAL_MANAGER_ACTION_RELAY_BUILD='2026-10-01_MANAGER_ACTION_RELAY_R2_GET';
var EXTERNAL_MANAGER_ACTION_RELAY_PARENT_ORIGIN='https://ams-transport-proof-510075419067.europe-west1.run.app';
var EXTERNAL_MANAGER_ACTION_RELAY_MAX_FUTURE_MS=15*60*1000;
function ExternalManagerActionRelay_b64url_(b){return Utilities.base64EncodeWebSafe(b).replace(/=+$/g,'');}
function ExternalManagerActionRelay_payload_(email,role,exp,origin){return['v1','MANAGER_ACTION_RELAY',String(email||'').trim().toLowerCase(),String(role||'').trim(),String(exp||'').trim(),String(origin||'').trim()].join('\n');}
function ExternalManagerActionRelay_sign_(payload,key){return ExternalManagerActionRelay_b64url_(Utilities.computeHmacSha256Signature(String(payload||''),String(key||'')));}
function ExternalManagerActionRelay_safeEq_(a,b){a=String(a||'');b=String(b||'');if(!a||!b||a.length!==b.length)return false;var x=0;for(var i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;}
function ExternalManagerActionRelay_verify_(p){p=p||{};if(!V5_ENTRY_isDevEnv_())return{ok:false,error:'DEV_ONLY'};var email=String(p.email||'').trim().toLowerCase(),role=String(p.role||'').trim(),exp=Number(String(p.exp||'').trim()),origin=String(p.origin||'').trim(),supplied=String(p.signature||'').trim(),now=Date.now();if(!email||role!=='Manager'||!exp||!origin||!supplied)return{ok:false,error:'MISSING_FIELDS'};if(origin!==EXTERNAL_MANAGER_ACTION_RELAY_PARENT_ORIGIN)return{ok:false,error:'ORIGIN_FORBIDDEN'};if(exp<now)return{ok:false,error:'ASSERTION_EXPIRED'};if(exp-now>EXTERNAL_MANAGER_ACTION_RELAY_MAX_FUTURE_MS)return{ok:false,error:'ASSERTION_TOO_FAR'};var secret=String(PropertiesService.getScriptProperties().getProperty('AMS_EXTERNAL_WRITE_BRIDGE_KEY')||'').trim();if(secret.length<32)return{ok:false,error:'BRIDGE_KEY_NOT_CONFIGURED'};var expected=ExternalManagerActionRelay_sign_(ExternalManagerActionRelay_payload_(email,role,exp,origin),secret);if(!ExternalManagerActionRelay_safeEq_(supplied,expected))return{ok:false,error:'BAD_SIGNATURE'};return{ok:true,email:email,role:role,origin:origin};}
var EXTERNAL_MANAGER_ACTION_RELAY_BASE_DOGET_=doGet;
doGet=function(e){var p=e&&e.parameter?e.parameter:{},raw=String(p.action||'').trim().toLowerCase();if(raw!=='externalmanageractionrelay')return EXTERNAL_MANAGER_ACTION_RELAY_BASE_DOGET_(e);var v=ExternalManagerActionRelay_verify_(p);if(!v.ok)return HtmlService.createHtmlOutput('<pre>'+String(v.error||'RELAY_FAILED').replace(/[<>]/g,'')+'</pre>').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);var auditId=String(p.auditId||'').trim(),managerAction=String(p.managerAction||'').trim().toLowerCase(),reason=String(p.reason||p.comment||'').trim();if(!managerAction)return HtmlService.createHtmlOutput('<pre>'+EXTERNAL_MANAGER_ACTION_RELAY_BUILD+'</pre>').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);if(!auditId||['approve','cancel','reject'].indexOf(managerAction)<0)return HtmlService.createHtmlOutput('<pre>INVALID_ACTION_REQUEST</pre>').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);if((managerAction==='cancel'||managerAction==='reject')&&!reason)return HtmlService.createHtmlOutput('<pre>ACTION_REASON_REQUIRED</pre>').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);try{managerV5Action(auditId,managerAction,{reason:reason,comment:reason,actorEmail:v.email,managerEmail:v.email,externalSession:true});return HtmlService.createHtmlOutput('<pre>OK</pre>').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}catch(err){return HtmlService.createHtmlOutput('<pre>'+String(err&&err.message?err.message:err).replace(/[<>]/g,'')+'</pre>').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}};
function RUN_EXTERNAL_MANAGER_ACTION_RELAY_CONTRACT_ACCEPTANCE(){var src=String(doGet),out={ok:true,build:EXTERNAL_MANAGER_ACTION_RELAY_BUILD,writesPerformed:false,checks:[]};function c(n,o){out.checks.push({name:n,ok:!!o});if(!o)out.ok=false;}c('devOnly',V5_ENTRY_isDevEnv_());c('managerAdapterAvailable',typeof managerV5Action==='function');c('baseDoGetPreserved',typeof EXTERNAL_MANAGER_ACTION_RELAY_BASE_DOGET_==='function');c('signedRelay',src.indexOf('ExternalManagerActionRelay_verify_')>=0);c('canonicalManagerAction',src.indexOf('managerV5Action')>=0);c('legacyReadyHandshakeRemoved',src.indexOf('AMS_MANAGER_ACTION_RELAY_READY')<0);try{Logger.log(JSON.stringify(out,null,2));}catch(e){}return out;}
