import fs from 'node:fs';
const r4=fs.readFileSync(new URL('./server-r4.js',import.meta.url),'utf8');
const r5=fs.readFileSync(new URL('./server-r5.js',import.meta.url),'utf8');
const backend=fs.readFileSync(new URL('../../ManagerPlanningBackend_CORE_SPLIT.js',import.meta.url),'utf8');
const handoff=fs.readFileSync(new URL('../../zz_ExternalPlanningWorkspaceHandoff.js',import.meta.url),'utf8');
const manager=fs.readFileSync(new URL('./manager-portal.js',import.meta.url),'utf8');
const entry=fs.readFileSync(new URL('../../EntryV5.js',import.meta.url),'utf8');
const checks=[
 ['r5 focused planning route',r5.includes("u.pathname==='/planning'")&&r5.includes('planningHtml(auditId)')],
 ['r5 canonical save route',r5.includes("u.pathname==='/api/v1/planning/save'")&&r5.includes('canonicalPlanningSave')],
 ['r5 session required',r5.includes("error:'SESSION_REQUIRED'")],
 ['r5 canonical GAS writer',r5.includes("searchParams.set('action','externalplanningworkspace')")],
 ['r5 required-hours UI',r5.includes('id="requiredHours"')&&r5.includes('a.requiredHours')],
 ['r5 preassigned UI',r5.includes('id="preassigned"')&&r5.includes('a.preassignedAuditor')],
 ['r5 warning surface',r5.includes('id="warnings"')&&r5.includes('warningMessages()')],
 ['r5 planning-window hard date guard',r5.includes("d>=a.planningWindowFrom")&&r5.includes("d<=a.planningWindowTo")],
 ['r5 required-hours soft warning',r5.includes('required audit time is')&&r5.includes('These are soft warnings. Continue?')],
 ['r5 multi-slot UI',r5.includes('id="addSlot"')&&r5.includes('id="slotList"')&&r5.includes('draftBlocks=[]')],
 ['r5 multi-slot canonical payload',r5.includes('blocks:draftBlocks.slice()')],
 ['r5 duplicate-slot guard',r5.includes('This slot is already added.')],
 ['r5 draft-overlap guard',r5.includes('This slot overlaps another slot in the draft.')&&r5.includes('function overlaps(')],
 ['r5 external-conflict hard guard',r5.includes('overlaps existing committed/provisional occupancy and cannot be added.')&&r5.includes('function externalConflicts(')],
 ['r5 no arbitrary five-block ceiling',!r5.includes('PLANNING_TOO_MANY_BLOCKS')],
 ['r5 aggregate planned-hours guard',r5.includes("draftBlocks.reduce((n,b)=>n+blockHours(b),0)")],
 ['r5 embedded regex escapes preserved',r5.includes("match(/^(\\\\d{2}):(\\\\d{2})$/)")],
 ['r5 embedded warning newlines escaped',r5.includes("warnings.join('\\\\n')+'\\\\n\\\\nThese are soft warnings. Continue?'")],
 ['r4 required-hours projection',r4.includes("requiredHours:Number(String(g(['Total audit time in hours'")],
 ['r4 no five-candidate truncation',!r4.includes('.slice(0,5);')],
 ['r4 qualification remains scope-based',r4.includes('required.every(sc=>')],
 ['r4 focused read bounded batch',r4.includes("sheetsBatchGet(['Audit planning!A1:AX768','Auditors!A1:AZ256','Auditor Availability!A:P','Concept Reservations!A1:P256','Config_Scopes!A1:Z128','Companies!A1:AZ768'])")],
 ['r4 availability read not row-truncated',r4.includes("'Auditor Availability!A:P'")&&!r4.includes("'Auditor Availability!A1:P768'")],
 ['r4 canonical availability identity aliases',r4.includes('function availabilityProjection(values,candidates')&&r4.includes("ci=col(h,['Auditor_Email','Auditor Email','Email','E-mail','Auditor_Name','Auditor Name','Auditor'])")&&r4.includes('const rawIdentity=ci>=0?val(row,ci)')],
 ['r4 company planning context',r4.includes('function companyPlanningContext(')&&r4.includes('audit.preferredAuditMonths=companyCtx.preferredAuditMonths')&&r4.includes('audit.locations=companyCtx.locations')],
 ['r5 canonical locations UI',r5.includes('for(const x of a.locations||[])')&&r5.includes('id="location"')],
 ['r5 preferred months UI',r5.includes("a.preferredAuditMonths?'Preferred: '")],
 ['r5 required-hours drives default end',r5.includes("Math.round(Number(a.requiredHours)*60)")&&r5.includes("q('#start').addEventListener('change'")],
 ['r4 soft marker classified separately from audit occupancy',r4.includes("kind:auditRef?'audit':soft?'soft':'hard'")&&r4.includes("visualState=hasAudit?'OCCUPIED'")]
,
 ['r5 quarter-hour time navigation',r5.includes('step="900" list="quarterHours"')&&r5.includes('function snapQuarter(v)')],
 ['r56 implicit availability is green',r5.includes("state:'YES',available:'YES'")&&r5.includes("(hasOccupancy||softDay||hasProvisional)?'partial':'yes'")],
 ['r56 1.0 full-day criterion',r5.includes("blockedOp>=8*60||blockedBar>=8*60")&&r5.includes("auditFullDay")&&r5.includes("'FULLY OCCUPIED'")],
 ['r57 canonical availability visual states',r4.includes("visualState=hasAudit?'OCCUPIED':state==='NO'?(hasSoft?'SOFT_UNAVAILABLE':'HARD_BLOCKED'):'AVAILABLE'")],
 ['r57 soft warning not audit occupancy',r5.includes("auditSlots=slotsArr.filter(s=>s.kind==='audit'||s.auditRef)")&&r5.includes("softDay?'SOFT WARNING':'YES'")],
 ['r57 auditor default blocked weekday is soft',r5.includes("blockedDays.includes(wd)")&&r5.includes("defaultSoft")],
 ['r58 company context parity',r4.includes("contactName:''")&&r4.includes("preferredTimeWindow:''")&&r4.includes('audit.companyContext=companyCtx')&&r5.includes('id="companyContext"')],
 ['r58 effective planning window starts no earlier than today',r5.includes('effectiveFrom=a.planningWindowFrom&&a.planningWindowFrom>today?a.planningWindowFrom:today')&&r5.includes("txt('#window',[effectiveFrom,a.planningWindowTo]")],
 ['r58 inactive locations excluded',r4.includes("o.active===false||String(o.active).toLowerCase()==='false'")],
 ['r59 company blocked weekday remains soft',r5.includes("companyContext?.blockedWeekdays")&&r5.includes("blockedDays.includes(wd)||companyBlocked.includes(wd)")],
 ['r59 required planned remaining parity',r5.includes('id="hoursSummary"')&&r5.includes("'Required '+required.toFixed(2)+' h · Planned '")],
 ['r66 rolling calendar window',r5.includes('CALENDAR_WINDOW_DAYS=70')&&r5.includes('CALENDAR_SHIFT_DAYS=28')&&r5.includes('id="prevWindow"')&&r5.includes('id="nextWindow"')&&r5.includes('id="todayWindow"')],
 ['r66 rolling calendar bounded by effective planning window',r5.includes("allowedFrom=a.planningWindowFrom&&a.planningWindowFrom>today?a.planningWindowFrom:today")&&r5.includes("to0=addDaysIso(from,CALENDAR_WINDOW_DAYS-1)")],
 ['r61 company preferred-time remains soft warning',r5.includes('function companyTimeWindow()')&&r5.includes('outside company preferred time window')],
 ['r62 slot edit parity',r5.includes('data-edit="1"')&&r5.includes("q('#date').value=b.date")&&r5.includes("q('#location').value=b.execLoc||'HQ'")],
 ['r63 soft availability is advisory in conflict guard',r5.includes("!s.start||!s.end||s.kind==='soft'")],
 ['r63 warnings use soft availability semantics',r5.includes("day.visualState==='SOFT_UNAVAILABLE'")&&!r5.includes("day&&day.state==='NO'")],
 ['r64 provisional reservations visible',r5.includes('provisionalByDate')&&r5.includes('PROVISIONAL · ')],
 ['r64 Manager provisional overlap is soft warning',r5.includes('function provisionalConflicts(b)')&&r5.includes('Manager soft reserve')],
 ['r64 provisional context enriched canonically',r4.includes("company:clean(canonical.company)")&&r4.includes("scopes:Array.isArray(canonical.scopes)?canonical.scopes:[]")],
 ['r81 canonical rotation endpoint direct read',r5.includes('/api/v1/planning/rotation')&&r5.includes('canonicalRotationRead')&&r5.includes('/api/v1/planning/rotation-direct')],
 ['r65 selected auditor only rotation hydration',r5.includes('async function loadRotation()')&&r5.includes("/api/v1/planning/rotation?auditId=")&&r5.includes("auditorEmail='+encodeURIComponent(email)")],
 ['r66 company context is collapsible',r5.includes('id="companyContextCard"')&&r5.includes('<summary>Company details</summary>')],
 ['r66 no month-paging remnants',!r5.includes('calendarMonth')&&!r5.includes('prevMonth')&&!r5.includes('nextMonth')&&!r5.includes('monthLabel')],
 ['r66 rolling window crosses month boundaries',r5.includes('CALENDAR_WINDOW_DAYS=70')&&r5.includes("let iso=from;while(iso<=to")],
 ['r67 audit id safe script serialization',r5.includes("JSON.stringify(clean(auditId)).replace(/</g")&&r5.includes("replace(/\\u2028/g")],
 ['r68 generated client newline remains escaped',r5.includes("ctxLines.join('\\\\n')")&&!r5.includes("ctxLines.join('\\n')")],
 ['r69 rolling navigation has no redundant month dropdown',!r5.includes('preferredJump')&&!r5.includes('monthMap={Jan')&&r5.includes('id="prevWindow"')&&r5.includes('id="nextWindow"')],
 ['r69 window label is secondary context',r5.includes('id="windowLabel" class="muted"')],
 ['r70 rotation detail is per required scope',r5.includes('rotationByScope||{}')&&r5.includes("limit reached':m.nearLimit?' near limit")],
 ['r78 qualification fails closed while rotation remains advisory',r5.includes("if(c.hardBlockQualification||c.ineligible)return setStatus")&&r5.includes('hardQualified=!(candidate.hardBlockQualification||candidate.ineligible)')&&!r5.includes('candidate.ineligible||candidate.rotationCheckFailed')],
 ['r74 selected calendar day class follows date input and direct DOM state',r5.includes("q('#date').value===iso?' selected':''")&&r5.includes("box.querySelectorAll('.day.selected')")&&r5.includes("d.classList.add('selected')")],
 ['r74 selected calendar day has explicit overriding colour',r5.includes('.day.selected,.day.yes.selected,.day.partial.selected,.day.no.selected{background:#bfdbfe!important;border:3px solid #1d4ed8!important')],
 ['r74 manual date change synchronizes calendar selection',r5.includes("q('#date').addEventListener('change',function(){renderAvailability();validate()})")],
 ['r75 DEV sessions persist for 30-day test cycles',r4.includes('SESSION_TTL_SECONDS=30*24*60*60')&&r5.includes('SESSION_TTL_SECONDS=30*24*60*60')],
 ['r39 scope aliases compare canonical keys',r4.includes("const canonical=key(s.displayName||s.scopeCode||s.slotKey)")&&r4.includes("aliases.set(key(k),canonical)")&&r4.includes("const headerCanon=aliases.get(key(h[i]))||key(h[i])")],
 ['r79 rotation read failure is visible soft advisory with RCA detail',r5.includes("candidate.rotationState='CHECK_FAILED'")&&r5.includes("candidate.rotationWarning='Rotation check temporarily unavailable: '+detail")&&r5.includes("Rotation check temporarily unavailable · '+detail")&&!r5.includes('candidate.ineligible||candidate.rotationCheckFailed')],
 ['r80 rotation cache preserves canonical owner and deduplicates inflight reads',r5.includes('ROTATION_CACHE_TTL_MS=5*60*1000')&&r5.includes('rotationReadCache=new Map(),rotationReadInflight=new Map()')&&r5.includes('canonicalRotationReadUncached(identity,auditId,auditorEmail)')&&r5.includes("__rotationCache:'HIT'")&&r5.includes("__rotationCache:'MISS'")],
 ['r81 direct rotation endpoint is wired through Cloud Run',r4.includes("/api/v1/planning/rotation-direct")&&r4.includes('directRotationRead(auditId,auditorEmail)')&&r4.includes("__rotationReadOwner:'CLOUD_RUN_DIRECT_SHEETS'")&&r5.includes("/api/v1/planning/rotation-direct")],
 ['r81 direct rotation preserves canonical alias normalization and selected-scope dedupe',r4.includes("function rotationLooseKey(v){return key(v).replace(/\\s+/g,'')")&&r4.includes("required=[...new Set(scopesForAudit")],
 ['r81 direct rotation preserves canonical company UID to name fallback',r4.includes("if(uid){if(ru!==uid&&key(rn)!==key(company))continue}else if(key(rn)!==key(company))continue")],
 ['r81 direct rotation preserves canonical auditor identity fields',r4.includes("targetAud=audMap.byEmail.get(target)")&&r4.includes("name:targetAud.name||target,email:targetAud.email||target")],
 ['r81 rotation diagnostics identify direct read owner',r5.includes("readOwner:x.__rotationReadOwner")&&r5.includes("readServerMs:x.__serverMs")&&!r5.includes("gasServerMs:x.__serverMs")],
 ['r82 rotation warning UI does not expose internal state token',!r5.includes("out.push('Rotation: '+c.rotationState)")&&r5.includes("if(c.rotationWarning)out.push(c.rotationWarning)")],
 ['planning save exposes end-to-end latency diagnostics',r5.includes("[SAVE_PERF]")&&r5.includes("savePerf")&&r5.includes("transportTiming:x.transportTiming")&&r5.includes("debugTiming:x.debugTiming")&&r5.includes("saveRouteTiming:x.__saveRouteTiming")&&r5.includes("detail:x.detail")],
 ['DEV planning save remains open for acceptance diagnostics',r5.includes("q('#save').textContent='Saved'")&&!r5.includes("setTimeout(()=>{location.href='/'},700)")],
 ['manager portal presents canonical Approved as Pending acceptance',manager.includes('function displayStatus')&&manager.includes('s==="approved"?"Pending acceptance"')&&manager.includes('displayStatus(r.status)')],
 ['r77 save bridge exposes timing without changing canonical writer',r5.includes('const bridgeStarted=Date.now()')&&r5.includes('transportTiming={gasBridgeMs:bridgeMs,gasReportedMs:Number(out.totalMs||0)||null}')&&r5.includes("writeUrl.searchParams.set('action','externalplanningworkspace')")],
 ['save hot path does not reset fresh request execution cache',!backend.includes('try { AS_resetExecCache_(); } catch(_e) {}')],
 ['external commit response is compact and timed',handoff.includes('notificationQueued:!!')&&handoff.includes('bridgeMs:bridgeMs')&&handoff.includes('totalMs:Number(saved.totalMs || bridgeMs)')],
 ['planning commit failures remain JSON across GAS bridge',entry.includes("verified.mode === 'commit' || verified.mode === 'rotation'")&&entry.includes("ContentService.createTextOutput(JSON.stringify({success:false,error:'PLANNING_WORKSPACE_'")&&handoff.includes("error:'CANONICAL_PLANNING_SAVE_THROW'")],
 ['legacy GAS rotation bridge contract remains available',handoff.includes('ExternalPlanningWorkspaceHandoff_payload_')&&handoff.includes("mode === 'commit'")&&handoff.includes("mode === 'rotation' ? 'rotation' : 'open'")],
];
const failed=checks.filter(([,ok])=>!ok);
for(const [name,ok] of checks) console.log((ok?'PASS ':'FAIL ')+name);
if(failed.length){console.error('Contract failures: '+failed.map(([n])=>n).join(', '));process.exit(1);}
console.log('Focused Planning 2.0 contract GREEN: '+checks.length+'/'+checks.length);
