import http from 'node:http';
import {URL} from 'node:url';

const PUBLIC_PORT=Number(process.env.PORT||8080);
const INNER_PORT=PUBLIC_PORT+1;
const SID=process.env.DEV_SSOT_SPREADSHEET_ID||'';
const BUILD='2026-10-01_AMS_FORMAL_VS_SCHEDULED_HOURS_R1';

process.env.PORT=String(INNER_PORT);
await import('./server-r9.js');
process.env.PORT=String(PUBLIC_PORT);

function clean(v){return String(v==null?'':v).trim();}
function key(v){return clean(v).toLowerCase().replace(/\s+/g,'_');}
function col(h,names){const m={};(h||[]).forEach((v,i)=>{const k=key(v);if(k&&m[k]===undefined)m[k]=i;});for(const n of names){const k=key(n);if(m[k]!==undefined)return m[k];}return-1;}
function val(r,i){return i>=0?clean((r||[])[i]):'';}
function a1col(n){let s='';for(let x=n;x>0;x=Math.floor((x-1)/26))s=String.fromCharCode(65+((x-1)%26))+s;return s;}
function parseJson(raw){try{return typeof raw==='string'?JSON.parse(raw):raw}catch{return null}}
function blockHours(blocks){let total=0,seen=false;for(const b of Array.isArray(blocks)?blocks:[]){const n=Number(b?.hours);if(Number.isFinite(n)){total+=n;seen=true;continue;}const s=clean(b?.start),e=clean(b?.end);if(/^\d{2}:\d{2}$/.test(s)&&/^\d{2}:\d{2}$/.test(e)){const [sh,sm]=s.split(':').map(Number),[eh,em]=e.split(':').map(Number),mins=(eh*60+em)-(sh*60+sm);if(mins>0){total+=mins/60;seen=true;}}}return seen?Math.round(total*100)/100:null;}
function scheduledHours(j){if(!j||typeof j!=='object')return null;const explicit=Number(j.scheduledHours);if(Number.isFinite(explicit))return explicit;const blocks=blockHours(j.blocks);if(blocks!=null)return blocks;const legacy=Number(j.totalPlannedHours);return Number.isFinite(legacy)?legacy:null;}
function formalHours(j,fallback){if(j&&typeof j==='object'){const explicit=Number(j.formalHours);if(Number.isFinite(explicit))return explicit;}const n=Number(fallback);return Number.isFinite(n)?n:null;}
async function readRaw(req,max=131072){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>max)throw new Error('REQUEST_TOO_LARGE');}return raw;}
function sendJson(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-ams-build':BUILD});res.end(JSON.stringify(body));}
async function accessToken(){const r=await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token',{headers:{'Metadata-Flavor':'Google'}});if(!r.ok)throw new Error('METADATA_TOKEN_'+r.status);const j=await r.json();if(!j.access_token)throw new Error('METADATA_TOKEN_MISSING');return j.access_token;}
async function auditPlanningRows(){if(!SID)throw new Error('DEV_SSOT_SPREADSHEET_ID_NOT_CONFIGURED');const token=await accessToken(),u=new URL('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(SID)+'/values/Audit%20planning!A1:AX483');u.searchParams.set('valueRenderOption','UNFORMATTED_VALUE');u.searchParams.set('dateTimeRenderOption','FORMATTED_STRING');const r=await fetch(u,{headers:{authorization:'Bearer '+token}}),j=await r.json();if(!r.ok)throw new Error('SHEETS_API_'+r.status+': '+JSON.stringify(j));return j.values||[];}
async function enrichManagerOpen(obj){const rows=obj?.rows;if(!Array.isArray(rows)||!rows.length)return obj;const values=await auditPlanningRows();if(values.length<2)return obj;const h=values[0],ci=col(h,['Audit ID','Audit_ID','AuditId','Audit Id']),cp=col(h,['Planning JSON','Planning_JSON']),byId=new Map();for(const row of values.slice(1)){const id=val(row,ci);if(id)byId.set(id,row);}let enriched=0;for(const r of rows){if(!r||r.statusKey==='PENDING_PLANNING')continue;const source=byId.get(clean(r.auditId));if(!source)continue;const j=parseJson(val(source,cp));if(!j)continue;const scheduled=scheduledHours(j),formal=formalHours(j,r.requiredHours);if(formal!=null){r.hoursPlanned=Math.round(formal*100)/100;r.plannedHours=r.hoursPlanned;}if(scheduled!=null)r.scheduledHours=Math.round(scheduled*100)/100;if(formal!=null&&scheduled!=null)r.hoursVariance=Math.round((scheduled-formal)*100)/100;enriched++;}obj.hoursSemantics={build:BUILD,enriched,formalField:'hoursPlanned',scheduledField:'scheduledHours'};return obj;}
async function normalizeCombinedProjection(auditId,formal,scheduled,planningJson){const values=await auditPlanningRows();if(values.length<2)throw new Error('AUDIT_PLANNING_EMPTY');const h=values[0],ci=col(h,['Audit ID','Audit_ID','AuditId','Audit Id']),cp=col(h,['Planning JSON','Planning_JSON']);if(ci<0||cp<0)throw new Error('PLANNING_JSON_SCHEMA_MISSING');let rowNo=0;for(let i=1;i<values.length;i++)if(val(values[i],ci)===clean(auditId)){rowNo=i+1;break;}if(!rowNo)throw new Error('AUDIT_NOT_FOUND');const j=parseJson(planningJson)||{};j.scheduledHours=Math.round(Number(scheduled)*100)/100;j.formalHours=Math.round(Number(formal)*100)/100;j.totalPlannedHours=j.formalHours;const normalized=JSON.stringify(j),token=await accessToken(),range='Audit planning!'+a1col(cp+1)+rowNo,u='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(SID)+'/values/'+encodeURIComponent(range)+'?valueInputOption=USER_ENTERED',r=await fetch(u,{method:'PUT',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({values:[[normalized]]})}),out=await r.json();if(!r.ok)throw new Error('PLANNING_JSON_NORMALIZE_'+r.status+': '+JSON.stringify(out));return{success:true,auditId:clean(auditId),formalHours:j.formalHours,scheduledHours:j.scheduledHours,row:rowNo,planningJson:normalized};}
async function proxy(req,res,raw){const target='http://127.0.0.1:'+INNER_PORT+(req.url||'/'),headers={};for(const [k,v] of Object.entries(req.headers)){if(v!=null&&!['host','content-length','connection'].includes(k.toLowerCase()))headers[k]=v;}const init={method:req.method,headers,redirect:'manual'};if(req.method!=='GET'&&req.method!=='HEAD')init.body=raw||'';const r=await fetch(target,init),buf=Buffer.from(await r.arrayBuffer()),outHeaders={};r.headers.forEach((v,k)=>{if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))outHeaders[k]=v;});outHeaders['x-ams-build']=BUILD;let body=buf;const u=new URL(req.url||'/','http://localhost'),ct=clean(r.headers.get('content-type'));
  if(r.ok&&req.method==='GET'&&u.pathname==='/api/v1/manager/open'&&ct.includes('application/json')){let j;try{j=JSON.parse(buf.toString('utf8'));}catch{j=null;}if(j){j=await enrichManagerOpen(j);body=Buffer.from(JSON.stringify(j),'utf8');outHeaders['content-length']=String(body.length);}}
  if(r.ok&&req.method==='POST'&&u.pathname==='/api/v1/planning/commit-handoff'&&ct.includes('application/json')){let j;try{j=JSON.parse(buf.toString('utf8'));}catch{j=null;}const result=j?.result;if(j?.ok===true&&result?.success===true&&result?.combinedVisit===true){const formal=Number(result.formalHours),scheduled=Number(result.schedulingHours);if(Number.isFinite(formal)&&Number.isFinite(scheduled)){try{const fixed=await normalizeCombinedProjection(result.auditId,formal,scheduled,result.planningJson);result.planningJson=fixed.planningJson;j.formalSchedulingProjection=fixed;}catch(e){j.formalSchedulingProjection={success:false,error:clean(e?.message||e)};}body=Buffer.from(JSON.stringify(j),'utf8');outHeaders['content-length']=String(body.length);}}}
  res.writeHead(r.status,outHeaders);res.end(body);
}

http.createServer(async(req,res)=>{const u=new URL(req.url||'/','http://localhost');if(req.method==='GET'&&u.pathname==='/api/v1/build')return sendJson(res,200,{ok:true,build:BUILD,inner:'server-r9.js',hoursSemantics:{formalPlanned:'hoursPlanned',scheduledDuration:'scheduledHours'},ecasHoursSource:'Planning JSON totalPlannedHours=formalHours'});let raw='';try{if(req.method!=='GET'&&req.method!=='HEAD')raw=await readRaw(req);}catch(e){return sendJson(res,413,{ok:false,error:clean(e?.message||e),build:BUILD});}try{return await proxy(req,res,raw);}catch(e){return sendJson(res,502,{ok:false,error:'R10_PROXY_FAILED',detail:clean(e?.message||e),build:BUILD});}}).listen(PUBLIC_PORT,'0.0.0.0');
