import http from 'node:http';
import {URL} from 'node:url';
import {createHash} from 'node:crypto';
import {v211AuditorQualified,v211CompanyAuditorExclusions,v211MinimumIntervalConstraint} from './assignment-validation-v211.js';

const PUBLIC_PORT=Number(process.env.PORT||8080);
const INNER_PORT=PUBLIC_PORT+1;
const SID=process.env.DEV_SSOT_SPREADSHEET_ID||'';
const SESSION_COOKIE='ams_dev_session';
const BUILD='2026-10-04_AMS_COMBINED_VISIT_R3_V211_PARITY';

process.env.PORT=String(INNER_PORT);
await import('./server-r5.js');
process.env.PORT=String(PUBLIC_PORT);

function clean(v){return String(v==null?'':v).trim();}
function key(v){return clean(v).toLowerCase().replace(/\s+/g,'_');}
function col(h,names){const m={};(h||[]).forEach((v,i)=>{const k=key(v);if(k&&m[k]===undefined)m[k]=i;});for(const n of names){const k=key(n);if(m[k]!==undefined)return m[k];}return-1;}
function val(r,i){return i>=0?clean((r||[])[i]):'';}
function yes(v){const s=clean(v).toLowerCase();return s==='x'||s==='yes'||s==='true'||s==='1';}
function dateOnly(v){const s=clean(v),m=s.match(/^(\d{4}-\d{2}-\d{2})/);return m?m[1]:s.slice(0,10);}
function isoLocalStamp(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Amsterdam',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()).replace('T',' ');}
function a1col(n){let s='';for(let x=n;x>0;x=Math.floor((x-1)/26))s=String.fromCharCode(65+((x-1)%26))+s;return s;}
function overlaps(a,b){return clean(a.start)<clean(b.end)&&clean(b.start)<clean(a.end);}
function normalizeStatus(v){return clean(v).toUpperCase().replace(/[\s-]+/g,'_');}
function shaRevision(h,row){const g=n=>val(row,col(h,n));return createHash('sha256').update([g(['Audit ID','Audit_ID','AuditId','Audit Id']),g(['Status']),g(['Assigned to','Assigned auditor','Auditor']),g(['Planning JSON','Planning_JSON']),g(['Last decision timestamp']),g(['Status since'])].join('|')).digest('hex').slice(0,24);}

async function accessToken(){const r=await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token',{headers:{'Metadata-Flavor':'Google'}});if(!r.ok)throw new Error('METADATA_TOKEN_'+r.status);const j=await r.json();if(!j.access_token)throw new Error('METADATA_TOKEN_MISSING');return j.access_token;}
async function sheetsBatchGet(ranges){const token=await accessToken(),u=new URL('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(SID)+'/values:batchGet');for(const range of ranges)u.searchParams.append('ranges',range);u.searchParams.set('valueRenderOption','UNFORMATTED_VALUE');u.searchParams.set('dateTimeRenderOption','FORMATTED_STRING');const r=await fetch(u,{headers:{authorization:'Bearer '+token}}),body=await r.json();if(!r.ok)throw new Error('SHEETS_API_'+r.status+': '+JSON.stringify(body));return body.valueRanges||[];}
async function sheetsValuesBatchUpdate(data){const token=await accessToken(),u='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(SID)+'/values:batchUpdate';const r=await fetch(u,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({valueInputOption:'USER_ENTERED',data})}),body=await r.json();if(!r.ok)throw new Error('SHEETS_BATCH_UPDATE_'+r.status+': '+JSON.stringify(body));return body;}
async function sheetsValuesAppend(range,values){const token=await accessToken(),u='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(SID)+'/values/'+encodeURIComponent(range)+':append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS';const r=await fetch(u,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({values})}),body=await r.json();if(!r.ok)throw new Error('SHEETS_APPEND_'+r.status+': '+JSON.stringify(body));return body;}
async function sheetsEnsureRows(sheetTitle,requiredRows){const token=await accessToken(),metaUrl='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(SID)+'?fields=sheets.properties';const mr=await fetch(metaUrl,{headers:{authorization:'Bearer '+token}}),meta=await mr.json();if(!mr.ok)throw new Error('SHEETS_META_'+mr.status+': '+JSON.stringify(meta));const sh=(meta.sheets||[]).find(x=>x.properties?.title===sheetTitle);if(!sh)throw new Error('SHEET_NOT_FOUND_'+sheetTitle);const current=Number(sh.properties.gridProperties?.rowCount||0);if(requiredRows<=current)return;const u='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(SID)+':batchUpdate',body={requests:[{appendDimension:{sheetId:sh.properties.sheetId,dimension:'ROWS',length:Math.max(requiredRows-current,100)}}]};const r=await fetch(u,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)}),out=await r.json();if(!r.ok)throw new Error('SHEETS_GRID_EXPAND_'+r.status+': '+JSON.stringify(out));}

async function innerSession(req){const r=await fetch('http://127.0.0.1:'+INNER_PORT+'/api/v1/session',{headers:{cookie:clean(req.headers.cookie)},redirect:'manual'});let j={};try{j=await r.json();}catch{}return r.ok&&j?.ok===true?j.identity:null;}
async function innerRotationCheck(req,auditId,auditorEmail){const u='http://127.0.0.1:'+INNER_PORT+'/api/v1/planning/rotation?auditId='+encodeURIComponent(auditId)+'&auditorEmail='+encodeURIComponent(auditorEmail);const r=await fetch(u,{headers:{cookie:clean(req.headers.cookie)},redirect:'manual'});let j={};try{j=await r.json();}catch{}if(!r.ok||j?.success===false)throw new Error('PLANNING_ROTATION_CHECK_FAILED');return j;}
async function readRaw(req,max=131072){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>max)throw new Error('REQUEST_TOO_LARGE');}return raw;}
function sendJson(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(body));}

function scopeCatalog(values){if(!values.length)return[];const h=values[0],cs=col(h,['SlotKey','Slot key','Slot']),cc=col(h,['ScopeCode','Scope code','Code']),cn=col(h,['DisplayName','Display name','Name','ScopeName','Scope']),ca=col(h,['Active']),car=col(h,['Archived']),cr=col(h,['Recurring']),coc=col(h,['Obligation cycle','Obligation_cycle','Cycle']),ccb=col(h,['Complete by','Complete_by','Must be completed by']),cfh=col(h,['Formal_hours','Formal hours','Formal Hours','Default_hours','Default hours']),cmoh=col(h,['Max_Offsite_Hours','Max Offsite Hours','Max offsite hours','Maximum offsite hours']),cmi=col(h,['Min_Interval_Months','Min Interval Months','Minimum interval months']);return values.slice(1).map(r=>({slotKey:val(r,cs),scopeCode:val(r,cc),displayName:val(r,cn),active:ca<0||yes(r[ca]),archived:car>=0&&yes(r[car]),recurring:cr<0?null:yes(r[cr]),obligationCycle:val(r,coc).toUpperCase(),completeBy:val(r,ccb),formalHours:Number(String(val(r,cfh)||'').replace(',','.'))||0,maxOffsiteHours:Math.max(0,Number(String(val(r,cmoh)||'0').replace(',','.'))||0),minIntervalMonths:Math.max(0,Number(String(val(r,cmi)||'0').replace(',','.'))||0)})).filter(x=>x.scopeCode&&x.displayName&&x.active&&!x.archived);}
function directPlanNormBlocks(raw){const out=[];for(const x of Array.isArray(raw)?raw:[]){const date=dateOnly(x?.date),start=clean(x?.start),end=clean(x?.end),executionType=clean(x?.executionType||x?.workType||'ONSITE').toUpperCase()==='OFFSITE'?'OFFSITE':'ONSITE',execLoc=executionType==='OFFSITE'?'':(clean(x?.execLoc||x?.executionLocation||x?.location||'HQ')||'HQ'),slotComment=clean(x?.slotComment||x?.comment);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end))throw new Error('PLANNING_BLOCK_INVALID');const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);if(sh<0||sh>23||eh<0||eh>23||![0,15,30,45].includes(sm)||![0,15,30,45].includes(em))throw new Error('PLANNING_BLOCK_QUARTER_HOUR_REQUIRED');const startMin=sh*60+sm,endMin=eh*60+em,hours=(endMin-startMin)/60;if(!(hours>0))throw new Error('PLANNING_BLOCK_INVALID');out.push({date,start,end,hours,executionType,execLoc,slotComment});}out.sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)||a.end.localeCompare(b.end));return out;}
function findAudit(values,id){if(!values.length)return null;const h=values[0],ci=col(h,['Audit ID','Audit_ID','AuditId','Audit Id']);for(let i=1;i<values.length;i++)if(val(values[i],ci)===id)return{h,row:values[i],sourceRow:i+1};return null;}
function unionQualification(audValues,catalog,scopeCodes,auditorEmail){if(!audValues.length)return false;const h=audValues[0],e=col(h,['E-mail','Email','E-mail address','Mail']),a=col(h,['Active']),r=col(h,['Role','Function']),aliases=new Map();for(const s of catalog){const canonical=key(s.scopeCode);for(const x of [s.scopeCode,s.slotKey,s.displayName])if(x)aliases.set(key(x),canonical);}const target=audValues.slice(1).find(row=>val(row,e).toLowerCase()===auditorEmail&&yes(row[a])&&val(row,r).toLowerCase()==='auditor');if(!target)return false;return scopeCodes.every(sc=>{const canon=aliases.get(key(sc))||key(sc);for(let i=0;i<h.length;i++){const headerCanon=aliases.get(key(h[i]))||key(h[i]);if(headerCanon===canon)return yes(target[i]);}return false;});}
function addMonthsIso(iso,n){const m=clean(iso).match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return'';let t=Number(m[1])*12+Number(m[2])-1+Number(n||0),y=Math.floor(t/12),mo=t-y*12+1,d=Math.min(Number(m[3]),new Date(Date.UTC(y,mo,0)).getUTCDate());return String(y).padStart(4,'0')+'-'+String(mo).padStart(2,'0')+'-'+String(d).padStart(2,'0');}
function combinedMinPlanningDate(logValues,catalog,scopeCodes,companyUid,companyName){
  if(!logValues?.length)return'';const defs=(catalog||[]).filter(s=>Number(s.minIntervalMonths||0)>0&&(scopeCodes||[]).some(sc=>key(sc)===key(s.scopeCode)||key(sc)===key(s.displayName)||key(sc)===key(s.slotKey)));if(!defs.length)return'';
  const h=logValues[0],cu=col(h,['Company_UID','Company UID','CompanyUid']),cc=col(h,['Company']),cs=col(h,['Status']),cd=col(h,['Date completed','Completed date','Date planned','Date - Planned','Audit date','Execution date','Date']),csl=col(h,['Scopes list','Scopes','Scope']);let strict='';
  for(const def of defs){const aliases=new Set([def.scopeCode,def.displayName,def.slotKey].map(key).filter(Boolean));let latest='';for(const r of logValues.slice(1)){const st=val(r,cs).toUpperCase().replace(/[\s-]+/g,'_');if(st&&st!=='COMPLETED'&&st!=='REALIZED')continue;const uid=val(r,cu),name=key(val(r,cc));if(companyUid){if(uid!==companyUid&&name!==key(companyName))continue}else if(name!==key(companyName))continue;let match=false;for(let i=0;i<h.length&&!match;i++){if(aliases.has(key(h[i]))&&yes(r[i]))match=true}if(!match&&csl>=0)match=val(r,csl).split(/[,;|]/).some(x=>aliases.has(key(x)));if(!match)continue;const d=dateOnly(r[cd]);if(d&&(!latest||d>latest))latest=d}if(!latest)continue;const min=addMonthsIso(latest,Number(def.minIntervalMonths||0));if(min&&(!strict||min>strict))strict=min}return strict;
}
function executionDeadlineForObligation(ob,cfg){const cycle=clean(ob.cycleKey);if(!cfg||cfg.recurring!==false||clean(cfg.obligationCycle).toUpperCase()!=='ANNUAL'||!/^[0-9]{4}$/.test(cycle)||!/^([0-9]{2})-([0-9]{2})$/.test(clean(cfg.completeBy)))return'';return cycle+'-'+cfg.completeBy;}
function companyAuditorExcluded(values,companyUid,companyName,auditorEmail){
  if(!values.length)return false;const h=values[0],cu=col(h,['Company_UID','Company UID','UID']),cn=col(h,['Company']),cx=col(h,['Auditor_Exclusions','Auditor Exclusions','Auditor exclusions']);if(cx<0)return false;
  const uid=key(companyUid),name=key(companyName);let row=null;for(const r of values.slice(1)){if(uid&&cu>=0&&key(r[cu])===uid){row=r;break}if(!row&&name&&cn>=0&&key(r[cn])===name)row=r;}if(!row)return false;
  const target=clean(auditorEmail).toLowerCase(),raw=clean(row[cx]);if(!raw||!target)return false;const emails=new Set(),add=v=>{const s=clean(v).toLowerCase();if(s&&s.includes('@'))emails.add(s);};
  try{const j=JSON.parse(raw),arr=Array.isArray(j)?j:(Array.isArray(j?.exclusions)?j.exclusions:Array.isArray(j?.items)?j.items:[]);for(const x of arr){if(typeof x==='string'){add(x);continue}if(!x||typeof x!=='object'||x.active===false||String(x.active).toLowerCase()==='false')continue;add(x.auditorEmail||x.email||x.auditor||x.userEmail);}}catch{raw.split(/[;,|\n]/).forEach(add)}
  return emails.has(target);
}
function companyLocationCodes(values,companyUid,companyName){const out=new Set();if(!values.length)return out;const h=values[0],cu=col(h,['Company_UID','Company UID','UID']),cn=col(h,['Company']),cj=col(h,['Locations_JSON','Locations JSON','locations_json']),cl=col(h,['Location']);const uid=key(companyUid),name=key(companyName);let row=null;for(const r of values.slice(1)){if(uid&&cu>=0&&key(r[cu])===uid){row=r;break}if(!row&&name&&cn>=0&&key(r[cn])===name)row=r;}if(!row)return out;const raw=cj>=0?val(row,cj):'';const add=(o,i)=>{o=o||{};if(o.active===false||String(o.active).toLowerCase()==='false')return;const code=clean(o.code||o.Code||o.locationCode||o.location_code||o.type||o.Type||(i===0?'HQ':String(i+1)));const nm=clean(o.location||o.Location||o.name||o.Name||o.label||o.Label||o.address||o.Address||(cl>=0?val(row,cl):'')||code);if(code)out.add(code);if(!code&&nm)out.add(nm);};try{const j=JSON.parse(raw);const arr=Array.isArray(j)?j:(Array.isArray(j?.locations)?j.locations:Array.isArray(j?.Locations)?j.Locations:Array.isArray(j?.items)?j.items:Array.isArray(j?.sites)?j.sites:Array.isArray(j?.points)?j.points:(j&&typeof j==='object'?[j]:[]));arr.forEach(add);}catch{}if(!out.size)add({code:'HQ',name:cl>=0?val(row,cl):'HQ'},0);return out;}

const COMBINED_LOCKS=new Map();
async function withCombinedLock(fn){const k='__GLOBAL_COMBINED_VISIT__',prev=COMBINED_LOCKS.get(k)||Promise.resolve();let release;const gate=new Promise(r=>release=r),chain=prev.then(()=>gate);COMBINED_LOCKS.set(k,chain);await prev;try{return await fn();}finally{release();if(COMBINED_LOCKS.get(k)===chain)COMBINED_LOCKS.delete(k);}}

async function combinedCommit(identity,body,req){
  if(!SID)throw new Error('DEV_SSOT_SPREADSHEET_ID_NOT_CONFIGURED');
  const started=Date.now(),targetAuditId=clean(body?.auditId),auditorEmail=clean(body?.auditorEmail).toLowerCase(),auditorName=clean(body?.auditorName),requested=directPlanNormBlocks(body?.blocks);
  if(!targetAuditId||!auditorEmail||!requested.length)throw new Error('PLANNING_REQUIRED_FIELDS_MISSING');
  if(new Set(requested.map(b=>b.date)).size>5)throw new Error('PLANNING_MAX_5_DAYS');for(let i=0;i<requested.length;i++)for(let j=i+1;j<requested.length;j++)if(requested[i].date===requested[j].date&&overlaps(requested[i],requested[j]))throw new Error('PLANNING_BLOCKS_OVERLAP');
  const requestedMembers=Array.isArray(body?.visitMembers)?body.visitMembers:[],memberIds=[...new Set([targetAuditId,...(Array.isArray(body?.visitAuditIds)?body.visitAuditIds:[]),...requestedMembers.map(x=>x?.auditId)].map(clean).filter(Boolean))];
  if(memberIds.length<2)throw new Error('COMBINED_VISIT_REQUIRES_MULTIPLE_MEMBERS');
  return withCombinedLock(async()=>{
    const readStarted=Date.now(),vr=await sheetsBatchGet(['Audit planning!A1:AX483','Auditors!A1:Z256','Auditor Availability!A:P','Concept Reservations!A1:P256','Config_Scopes!A1:Z128','Audit_Obligations!A1:Z1000','Audit_Visit_Obligations!A1:H1000','Companies!A1:AJ686','Log realized audits!A1:AZ2048']),readMs=Date.now()-readStarted;
    const ap=vr[0]?.values||[],aud=vr[1]?.values||[],av=vr[2]?.values||[],cr=vr[3]?.values||[],scv=vr[4]?.values||[],obv=vr[5]?.values||[],links=vr[6]?.values||[],companies=vr[7]?.values||[],log=vr[8]?.values||[],catalog=scopeCatalog(scv),cfgByCode=new Map(catalog.map(x=>[x.scopeCode,x]));
    const memberById=new Map(requestedMembers.map(x=>[clean(x?.auditId),x]));
    const audits=new Map();let companyUid='',companyName='';
    for(const id of memberIds){const f=findAudit(ap,id);if(!f)throw new Error('VISIT_RELATED_AUDIT_NOT_FOUND');const status=normalizeStatus(val(f.row,col(f.h,['Status'])));if(status!=='PENDING_PLANNING')throw new Error(id===targetAuditId?'STATUS_TRANSITION_BLOCKED':'VISIT_RELATED_AUDIT_NOT_PENDING_PLANNING');const uid=val(f.row,col(f.h,['Company_UID','Company UID','CompanyUid']));if(companyUid&&uid!==companyUid)throw new Error('VISIT_COMPOSITION_COMPANY_MISMATCH');companyUid=companyUid||uid;companyName=companyName||val(f.row,col(f.h,['Company']));const revision=shaRevision(f.h,f.row),supplied=id===targetAuditId?clean(body?.sourceRevision):clean(memberById.get(id)?.sourceRevision);if(!supplied)throw new Error(id===targetAuditId?'PLANNING_SOURCE_REVISION_REQUIRED':'VISIT_RELATED_SOURCE_REVISION_REQUIRED');if(supplied!==revision)throw new Error(id===targetAuditId?'PLANNING_SOURCE_REVISION_CONFLICT':'VISIT_RELATED_SOURCE_REVISION_CONFLICT');const from=dateOnly(val(f.row,col(f.h,['Planning window from','Plan van','Planning from']))),to=dateOnly(val(f.row,col(f.h,['Planning window to','Plan tot','Planning to'])));if(requested.some(b=>(from&&b.date<from)||(to&&b.date>to)))throw new Error(id===targetAuditId?'PLANNING_WINDOW_BLOCKED':'VISIT_RELATED_PLANNING_WINDOW_BLOCKED');const formalHours=Number(String(val(f.row,col(f.h,['Total audit time in hours','Total time in hours','Required hours','Total hours']))||'').replace(',','.'))||0;audits.set(id,{...f,company:val(f.row,col(f.h,['Company'])),companyUid:uid,from,to,formalHours});}
    const oh=obv[0]||[],oi=col(oh,['Obligation_ID','Obligation ID']),ou=col(oh,['Company_UID','Company UID']),oc=col(oh,['ScopeCode','Scope Code']),ock=col(oh,['Cycle_Key','Cycle Key']),os=col(oh,['Obligation_State','Obligation State']),of=col(oh,['Formal_Hours','Formal Hours']),obById=new Map();for(const r of obv.slice(1)){const id=val(r,oi);if(id)obById.set(id,r);}
    const lh=links[0]||[],la=col(lh,['Audit_ID','Audit ID']),lo=col(lh,['Obligation_ID','Obligation ID']),ls=col(lh,['Link_State','Link State']),lm=col(lh,['Migration_Batch_ID','Migration Batch ID']),ll=col(lh,['Linked_At','Linked At']),lu=col(lh,['Unlinked_At','Unlinked At']);if([la,lo,ls,ll,lu].some(x=>x<0))throw new Error('VISIT_LINK_SCHEMA_INVALID');
    const activeByOb=new Map(),activeByAudit=new Map();for(let i=1;i<links.length;i++){const r=links[i],obId=val(r,lo);if(val(r,ls).toUpperCase()!=='ACTIVE'||!obId)continue;if(activeByOb.has(obId))throw new Error('VISIT_OBLIGATION_MULTIPLE_ACTIVE_LINKS');const x={row:r.slice(),sheetRow:i+1,auditId:val(r,la),obligationId:obId};activeByOb.set(obId,x);(activeByAudit.get(x.auditId)||activeByAudit.set(x.auditId,[]).get(x.auditId)).push(x);}
    const selectedObligations=[];for(const id of memberIds){const rows=activeByAudit.get(id)||[];if(!rows.length)throw new Error('VISIT_COMPOSITION_NO_ACTIVE_OBLIGATIONS');for(const x of rows){const ob=obById.get(x.obligationId);if(!ob)throw new Error('VISIT_OBLIGATION_NOT_FOUND');const state=val(ob,os).toUpperCase();if(['COMPLETED','CANCELLED','REJECTED'].includes(state))continue;if(val(ob,ou)&&companyUid&&val(ob,ou)!==companyUid)throw new Error('VISIT_COMPOSITION_COMPANY_MISMATCH');selectedObligations.push({link:x,ob,obligationId:x.obligationId,scopeCode:val(ob,oc),cycleKey:val(ob,ock),formalHours:Number(String(val(ob,of)||cfgByCode.get(val(ob,oc))?.formalHours||'').replace(',','.'))||0});}}
    if(!selectedObligations.length)throw new Error('VISIT_COMPOSITION_NO_ACTIVE_OBLIGATIONS');
    const selectedSet=new Set(selectedObligations.map(x=>x.obligationId));for(const id of memberIds.filter(x=>x!==targetAuditId)){const remaining=(activeByAudit.get(id)||[]).filter(x=>!selectedSet.has(x.obligationId)&&!['COMPLETED','CANCELLED','REJECTED'].includes(val(obById.get(x.obligationId)||[],os).toUpperCase()));if(remaining.length)throw new Error('VISIT_COMPOSITION_SOURCE_VISIT_NOT_EMPTY');}
    const scopeCodes=[...new Set(selectedObligations.map(x=>x.scopeCode).filter(Boolean))],minInterval=v211MinimumIntervalConstraint({logValues:log,catalog,scopeCodes,companyUid,companyName}),minPlanningDate=minInterval.minPlanningDate;if(minPlanningDate&&requested.some(b=>b.date<minPlanningDate))throw new Error('MIN_INTERVAL_HARD_BLOCK_'+minPlanningDate);const allowedExecLocs=companyLocationCodes(companies,companyUid,companyName);if(requested.some(b=>b.executionType==='ONSITE'&&!allowedExecLocs.has(clean(b.execLoc))))throw new Error('PLANNING_EXECUTION_LOCATION_INVALID');if(v211CompanyAuditorExclusions(companies,companyUid,companyName).has(auditorEmail))throw new Error('AUDITOR_EXCLUDED_FOR_COMPANY');if(!v211AuditorQualified(aud,catalog,scopeCodes,auditorEmail))throw new Error('AUDITOR_NOT_HARD_QUALIFIED');for(const memberId of memberIds){const rc=await innerRotationCheck(req,memberId,auditorEmail);if(rc?.auditor?.hardBlockQualification||rc?.auditor?.ineligible)throw new Error('AUDITOR_NOT_HARD_QUALIFIED');if(rc?.auditor?.softBlockRotation)throw new Error('PLANNING_ROTATION_LIMIT_HARD_BLOCK');}
    let formalRequired=0;for(const id of memberIds){const a=audits.get(id);formalRequired+=Number(a?.formalHours||0);}for(const x of selectedObligations){const cfg=cfgByCode.get(x.scopeCode)||{},deadline=executionDeadlineForObligation({cycleKey:x.cycleKey},cfg);if(deadline&&requested.some(b=>b.date>deadline)&&body?.executionExceptionApproved!==true)throw new Error(x.link.auditId===targetAuditId?'EXECUTION_DEADLINE_APPROVAL_REQUIRED':'VISIT_RELATED_EXECUTION_DEADLINE_APPROVAL_REQUIRED');}
    const total=requested.reduce((s,b)=>s+b.hours,0),totalMinutes=requested.reduce((s,b)=>s+Math.round(Number(b.hours||0)*60),0),formalRequiredMinutes=Math.round(formalRequired*60),planningDeltaMinutes=totalMinutes-formalRequiredMinutes,offsiteHours=Math.round(requested.filter(b=>b.executionType==='OFFSITE').reduce((s,b)=>s+b.hours,0)*100)/100;if(Math.abs(planningDeltaMinutes)>15)throw new Error(planningDeltaMinutes<0?'PLANNED_HOURS_BELOW_REQUIRED':'PLANNED_HOURS_ABOVE_REQUIRED');if(offsiteHours>0)throw new Error('OFFSITE_MULTI_SCOPE_ALLOCATION_REQUIRED');
    const now=isoLocalStamp(),sourceAuditIds=memberIds.filter(x=>x!==targetAuditId),sourceSet=new Set(sourceAuditIds);
    const ah=av[0]||[],cd=col(ah,['Date']),ce=col(ah,['Auditor_Email','Auditor Email','Email','E-mail']),ca=col(ah,['Available']),s1=col(ah,['First_Audit_Start_Time']),e1=col(ah,['First_Audit_End_Time']),id1=col(ah,['Audit_ID_1']),s2=col(ah,['Second_Audit_Start_Time']),e2=col(ah,['Second_Audit_End_Time']),id2=col(ah,['Audit_ID_2']),st1=col(ah,['Status_1']),st2=col(ah,['Status_2']),alu=col(ah,['Last_Updated']);if([cd,ce,ca,s1,e1,id1,s2,e2,id2,st1,st2].some(x=>x<0))throw new Error('AVAILABILITY_SCHEMA_INVALID');
    const avRows=av.slice(1).map((row,i)=>({row:row.slice(),sheetRow:i+2,date:dateOnly(row[cd]),email:clean(row[ce]).toLowerCase()})),touchedAv=new Map();for(const x of avRows){let changed=false;for(const z of [{s:s1,e:e1,id:id1,st:st1},{s:s2,e:e2,id:id2,st:st2}]){const aid=clean(x.row[z.id]);if(aid===targetAuditId||sourceSet.has(aid)){x.row[z.s]='';x.row[z.e]='';x.row[z.id]='';x.row[z.st]='';changed=true;}}if(changed){const has1=clean(x.row[id1]),has2=clean(x.row[id2]),soft=/^(DEFAULT_|MANUAL_|SYSTEM_DEFAULT|USER_MANUAL|CALENDAR|CALENDER)/i.test(clean(x.row[st1]))||/^(DEFAULT_|MANUAL_|SYSTEM_DEFAULT|USER_MANUAL|CALENDAR|CALENDER)/i.test(clean(x.row[st2]));x.row[ca]=(has1||has2||soft)?'NO':'YES';if(alu>=0)x.row[alu]=now;touchedAv.set(x.sheetRow,x);}}
    for(const b of requested){let x=avRows.find(r=>r.email===auditorEmail&&r.date===b.date);if(!x){const row=new Array(ah.length).fill('');row[cd]=b.date;row[ce]=auditorEmail;row[ca]='YES';if(alu>=0)row[alu]=now;x={row,sheetRow:av.length+1,date:b.date,email:auditorEmail};avRows.push(x);av.push(row);}const slots=[{s:s1,e:e1,id:id1,st:st1},{s:s2,e:e2,id:id2,st:st2}];for(const z of slots){const other=clean(x.row[z.id]);if(other&&other!==targetAuditId&&overlaps(b,{start:clean(x.row[z.s]),end:clean(x.row[z.e])}))throw new Error('AVAILABILITY_COLLISION_'+b.date);}const hardSlots=slots.filter(z=>!clean(x.row[z.id])&&clean(x.row[z.st])&&!/^(DEFAULT_|MANUAL_|SYSTEM_DEFAULT|USER_MANUAL|CALENDAR|CALENDER)/i.test(clean(x.row[z.st]))),wholeDayHard=!yes(x.row[ca])&&hardSlots.some(z=>!clean(x.row[z.s])&&!clean(x.row[z.e])),timedHard=hardSlots.some(z=>clean(x.row[z.s])&&clean(x.row[z.e])&&overlaps(b,{start:clean(x.row[z.s]),end:clean(x.row[z.e])}));if(wholeDayHard||timedHard)throw new Error('AVAILABILITY_HARD_BLOCK_'+b.date);const z=slots.find(q=>!clean(x.row[q.id]));if(!z)throw new Error('AVAILABILITY_CAPACITY_'+b.date);x.row[z.s]=b.start;x.row[z.e]=b.end;x.row[z.id]=targetAuditId;x.row[z.st]='Manager Planned';x.row[ca]='NO';if(alu>=0)x.row[alu]=now;touchedAv.set(x.sheetRow,x);}
    const target=audits.get(targetAuditId),h=target.h,targetRow=target.row.slice(),setTarget=(names,value)=>{const i=col(h,names);if(i>=0)targetRow[i]=value;};for(const cfg of catalog){const should=scopeCodes.includes(cfg.scopeCode);for(const name of [cfg.slotKey,cfg.scopeCode,cfg.displayName]){const i=col(h,[name]);if(i>=0)targetRow[i]=should?'X':'';}}
    const planningJson=JSON.stringify({blocks:requested,formalHours:Math.round(formalRequired*100)/100,totalPlannedHours:Math.round(total*100)/100,offsiteHours:0,auditorEmail,auditorName,visitAuditId:targetAuditId,obligationIds:selectedObligations.map(x=>x.obligationId),scopeCodes});setTarget(['Assigned to'],auditorEmail);setTarget(['Date - Planned'],requested[0].date);setTarget(['Date - Approved'],now.slice(0,10));setTarget(['Status'],'Approved');setTarget(['Hours planned','Planned hours','Hours Planned'],Math.round(formalRequired*100)/100);setTarget(['Planning JSON'],planningJson);setTarget(['Total audit time in hours','Total time in hours','Required hours','Total hours'],Math.round(formalRequired*100)/100);setTarget(['Last manager decision'],'PLAN');setTarget(['Last decision timestamp'],now);setTarget(['Status since'],now);
    const writes=[{range:'Audit planning!A'+target.sourceRow+':'+a1col(h.length)+target.sourceRow,values:[targetRow]}];for(const id of sourceAuditIds){const src=audits.get(id);writes.push({range:'Audit planning!A'+src.sourceRow+':'+a1col(src.h.length)+src.sourceRow,values:[new Array(src.h.length).fill('')]});}
    for(const x of touchedAv.values())writes.push({range:'Auditor Availability!A'+x.sheetRow+':'+a1col(ah.length)+x.sheetRow,values:[x.row]});
    let nextLinkRow=links.length+1;for(const x of selectedObligations){if(x.link.auditId===targetAuditId)continue;const old=x.link.row.slice();old[ls]='INACTIVE';old[lu]=now;writes.push({range:'Audit_Visit_Obligations!A'+x.link.sheetRow+':'+a1col(lh.length)+x.link.sheetRow,values:[old]});const nr=new Array(lh.length).fill('');nr[la]=targetAuditId;nr[lo]=x.obligationId;nr[ls]='ACTIVE';if(lm>=0)nr[lm]='';nr[ll]=now;nr[lu]='';writes.push({range:'Audit_Visit_Obligations!A'+nextLinkRow+':'+a1col(lh.length)+nextLinkRow,values:[nr]});nextLinkRow++;}
    const ch=cr[0]||[],ci=col(ch,['Audit ID']),cs=col(ch,['State']),cu=col(ch,['Updated At']),cby=col(ch,['Released By']),cat=col(ch,['Released At']),creason=col(ch,['Release Reason']);for(let i=1;i<cr.length;i++){const rr=cr[i].slice(),rid=clean(rr[ci]);if(!memberIds.includes(rid)||clean(rr[cs]).toUpperCase()!=='ACTIVE')continue;rr[cs]='RELEASED';if(cu>=0)rr[cu]=now;if(cby>=0)rr[cby]=clean(identity?.email);if(cat>=0)rr[cat]=now;if(creason>=0)rr[creason]='CANONICAL_COMBINED_VISIT_COMMIT';writes.push({range:'Concept Reservations!A'+(i+1)+':'+a1col(ch.length)+(i+1),values:[rr]});}
    const maxAv=Math.max(0,...[...touchedAv.values()].map(x=>x.sheetRow));if(maxAv)await sheetsEnsureRows('Auditor Availability',maxAv);if(nextLinkRow>links.length+1)await sheetsEnsureRows('Audit_Visit_Obligations',nextLinkRow-1);
    const writeStarted=Date.now();await sheetsValuesBatchUpdate(writes);const writeMs=Date.now()-writeStarted;
    const actorEmail=clean(identity?.email).toLowerCase(),minuteStamp=now.slice(0,16),company=clean(target.company),scopeNames=scopeCodes.map(code=>cfgByCode.get(code)?.displayName||code),trailRows=[];const composePayload={type:'VISIT_COMPOSITION_CHANGED',auditId:targetAuditId,company,actorEmail,actorRole:'MANAGER',sourceAuditIds,obligationIds:selectedObligations.map(x=>x.obligationId),scopeCodes,source:'CLOUD_RUN_COMBINED_VISIT',timestamp:now,action:'COMBINE_VISIT'};trailRows.push([minuteStamp,'AUDIT_TRAIL','VISIT_COMPOSITION_CHANGED','',targetAuditId,company,'[TRAIL] VISIT_COMPOSITION_CHANGED :: '+targetAuditId,JSON.stringify(composePayload),0,'',createHash('md5').update('VISIT_COMPOSITION_CHANGED|'+targetAuditId+'|'+now).digest('hex'),'',JSON.stringify({payload:composePayload})]);for(const src of sourceAuditIds){const p={type:'VISIT_SOURCE_PROJECTION_RETIRED',auditId:src,targetAuditId,company,actorEmail,actorRole:'MANAGER',source:'CLOUD_RUN_COMBINED_VISIT',timestamp:now,action:'COMBINE_VISIT'};trailRows.push([minuteStamp,'AUDIT_TRAIL','VISIT_SOURCE_PROJECTION_RETIRED','',src,company,'[TRAIL] VISIT_SOURCE_PROJECTION_RETIRED :: '+src+' -> '+targetAuditId,JSON.stringify(p),0,'',createHash('md5').update('VISIT_SOURCE_PROJECTION_RETIRED|'+src+'|'+targetAuditId+'|'+now).digest('hex'),'',JSON.stringify({payload:p})]);}
    const plannedPayload={eventType:'AUDIT_PLANNED_BY_MANAGER',eventFamily:'RICH_OPERATIONAL',rendererProfile:'RICH_OPERATIONAL',deliveryProfile:'IMMEDIATE_RICH',company,companyUid,targetAuditId,auditId:targetAuditId,actor:actorEmail,actorRole:'MANAGER',recipientRole:'AUDITOR',recipientGroup:'AUDITOR',resultStatus:'Approved',displayStatus:'Pending acceptance',plannedDates:[...new Set(requested.map(x=>x.date))],plannedHours:Math.round(total*100)/100,formalHours:Math.round(formalRequired*100)/100,blocks:requested,scopes:scopeNames,scopeCodes,obligationIds:selectedObligations.map(x=>x.obligationId),sourceAuditIds,auditorEmail,auditorName,planningJson,config:{active:true,sendEmail:true,logOnly:false,consolidate:false,bufferMinutes:0,digestGroup:'AUDITOR_OPERATIONAL',templateFamily:'RICH_OPERATIONAL',templateKeyDefault:'AUDIT_PLANNED_BY_MANAGER',fromEmail:'planning@agriqa.es',fromName:'Agri Quality Assurance – Audit Planning',replyTo:'',includeComment:true,requireReason:false}};const subject='Audit planned by manager – '+company+' – '+targetAuditId,bodyText=['Audit planned by manager','Company: '+company,'Audit ID: '+targetAuditId,'Scopes: '+scopeNames.join(', '),'Auditor: '+auditorName+' <'+auditorEmail+'>','Planning: '+requested.map(x=>x.date+' '+x.start+'-'+x.end).join('; '),'Planned hours: '+plannedPayload.plannedHours].join('\n'),hash=createHash('md5').update(auditorEmail+'|AUDIT_PLANNED_BY_MANAGER|'+targetAuditId+'|'+planningJson).digest('hex'),plannedRow=[minuteStamp,'PENDING','AUDIT_PLANNED_BY_MANAGER',auditorEmail,targetAuditId,company,subject,bodyText,0,'',hash,'',JSON.stringify({payload:plannedPayload})];
    let sideEffectQueue={success:true};const sideStarted=Date.now();try{await sheetsValuesAppend('Notification Queue!A:M',[...trailRows,plannedRow]);}catch(e){sideEffectQueue={success:false,error:clean(e?.message||e)};}const sideEffectMs=Date.now()-sideStarted;
    return{success:true,auditId:targetAuditId,newStatus:'Approved',assignedTo:auditorEmail,planningJson,combinedVisit:true,sourceAuditIds,obligationIds:selectedObligations.map(x=>x.obligationId),scopeCodes,formalHours:Math.round(formalRequired*100)/100,totalMs:Date.now()-started,readMs,writeMs,writeCount:writes.length,sideEffectMs,sideEffectQueue,owner:'CLOUD_RUN_DIRECT_SHEETS_COMBINED_VISIT',build:BUILD};
  });
}

function patchPlanningHtml(html){
  let out=String(html||'');
  const plannedMarker="function plannedHours(){return draftBlocks.reduce((n,b)=>n+blockHours(b),0)}";
  const planningTargetMarker="function planningTarget(){const a=model?.data?.audit||{},n=Number(a.formalHours??a.requiredHours??0);return Number.isFinite(n)&&n>=0?n:0}";
  const helper="function requiredVisitHours(){const set=model?.data?.audit?.companyPlanningSet||[],chosen=set.filter(r=>visitAuditIds.has(r.auditId)),sum=chosen.reduce((n,r)=>n+Number(r.formalHours||r.requiredHours||0),0);const primary=Number(model?.data?.audit?.formalHours||model?.data?.audit?.requiredHours||0);return sum||primary}";
  if(!out.includes('function requiredVisitHours(){')){
    if(!out.includes(plannedMarker))throw new Error('PLANNING_HTML_PATCH_MARKER_MISSING');
    out=out.replace(plannedMarker,plannedMarker+helper);
  }
  if(out.includes(planningTargetMarker)){
    out=out.replace(planningTargetMarker,"function planningTarget(){return requiredVisitHours()}");
  }
  if(!out.includes("function planningTarget(){return requiredVisitHours()}"))throw new Error('PLANNING_COMBINED_TARGET_PATCH_NOT_APPLIED');
  if(out.includes("function renderVisitComposition(){const set=")){
    out=out.replace("function renderVisitComposition(){const set=","function renderVisitComposition(){txt('#requiredHours',requiredVisitHours().toFixed(2)+' h');const set=");
  }
  if(!out.includes("txt('#requiredHours',requiredVisitHours().toFixed(2)+' h')"))throw new Error('PLANNING_COMBINED_DISPLAY_PATCH_NOT_APPLIED');
  return out;
}

async function proxy(req,res,raw){
  const u='http://127.0.0.1:'+INNER_PORT+(req.url||'/'),headers={};for(const [k,v] of Object.entries(req.headers)){if(v!=null&&!['host','content-length','connection'].includes(k.toLowerCase()))headers[k]=v;}const init={method:req.method,headers,redirect:'manual'};if(req.method!=='GET'&&req.method!=='HEAD')init.body=raw||'';const r=await fetch(u,init),buf=Buffer.from(await r.arrayBuffer()),outHeaders={};r.headers.forEach((v,k)=>{if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))outHeaders[k]=v;});let body=buf;if(r.ok&&clean(r.headers.get('content-type')).includes('text/html')&&(req.url||'').startsWith('/planning')){body=Buffer.from(patchPlanningHtml(buf.toString('utf8')),'utf8');outHeaders['content-length']=String(body.length);}res.writeHead(r.status,outHeaders);res.end(body);
}

http.createServer(async(req,res)=>{
  let raw='';try{if(req.method!=='GET'&&req.method!=='HEAD')raw=await readRaw(req);}catch(e){return sendJson(res,413,{ok:false,error:clean(e?.message||e)});}
  const u=new URL(req.url||'/', 'http://localhost');
  if(req.method==='POST'&&u.pathname==='/api/v1/planning/direct-commit'){
    let body={};try{body=JSON.parse(raw||'{}');}catch{return sendJson(res,400,{success:false,error:'BAD_JSON'});}const ids=[...new Set([clean(body?.auditId),...(Array.isArray(body?.visitAuditIds)?body.visitAuditIds.map(clean):[]),...(Array.isArray(body?.visitMembers)?body.visitMembers.map(x=>clean(x?.auditId)):[])].filter(Boolean))];if(ids.length>1){const identity=await innerSession(req);if(!identity)return sendJson(res,401,{success:false,error:'SESSION_REQUIRED'});if(clean(identity.role).toLowerCase()!=='manager')return sendJson(res,403,{success:false,error:'ROLE_FORBIDDEN'});try{return sendJson(res,200,await combinedCommit(identity,body,req));}catch(e){return sendJson(res,409,{success:false,error:clean(e?.message||e),build:BUILD,owner:'CLOUD_RUN_DIRECT_SHEETS_COMBINED_VISIT'});}}
  }
  try{if(req.method==='POST'&&u.pathname==='/api/v1/planning/direct-commit')return await withCombinedLock(()=>proxy(req,res,raw));return await proxy(req,res,raw);}catch(e){return sendJson(res,502,{ok:false,error:'R6_PROXY_FAILED',detail:clean(e?.message||e),build:BUILD});}
}).listen(PUBLIC_PORT,'0.0.0.0');
