import http from 'node:http';
import {URL} from 'node:url';

const PUBLIC_PORT=Number(process.env.PORT||8080);
const INNER_PORT=PUBLIC_PORT+1;
const SID=process.env.DEV_SSOT_SPREADSHEET_ID||'';
const BUILD='2026-10-01_AMS_COMBINED_VISIT_HOURS_PROJECTION_R1';

process.env.PORT=String(INNER_PORT);
await import('./server-r8.js');
process.env.PORT=String(PUBLIC_PORT);

function clean(v){return String(v==null?'':v).trim();}
function key(v){return clean(v).toLowerCase().replace(/\s+/g,'_');}
function col(h,names){const m={};(h||[]).forEach((v,i)=>{const k=key(v);if(k&&m[k]===undefined)m[k]=i;});for(const n of names){const k=key(n);if(m[k]!==undefined)return m[k];}return-1;}
function val(r,i){return i>=0?clean((r||[])[i]):'';}
function a1col(n){let s='';for(let x=n;x>0;x=Math.floor((x-1)/26))s=String.fromCharCode(65+((x-1)%26))+s;return s;}
function plannedHoursFromJson(raw){try{const j=typeof raw==='string'?JSON.parse(raw):raw;if(!j||typeof j!=='object')return null;const direct=Number(j.totalPlannedHours);if(Number.isFinite(direct)&&direct>=0)return direct;let total=0,seen=false;for(const b of Array.isArray(j.blocks)?j.blocks:[]){const h=Number(b?.hours);if(Number.isFinite(h)){total+=h;seen=true;continue;}const s=clean(b?.start),e=clean(b?.end);if(/^\d{2}:\d{2}$/.test(s)&&/^\d{2}:\d{2}$/.test(e)){const [sh,sm]=s.split(':').map(Number),[eh,em]=e.split(':').map(Number),mins=(eh*60+em)-(sh*60+sm);if(mins>0){total+=mins/60;seen=true;}}}return seen?Math.round(total*100)/100:null;}catch{return null;}}
function plannedHoursFromBlocks(blocks){let total=0,seen=false;for(const b of Array.isArray(blocks)?blocks:[]){const s=clean(b?.start),e=clean(b?.end);if(!/^\d{2}:\d{2}$/.test(s)||!/^\d{2}:\d{2}$/.test(e))continue;const [sh,sm]=s.split(':').map(Number),[eh,em]=e.split(':').map(Number),mins=(eh*60+em)-(sh*60+sm);if(mins>0){total+=mins/60;seen=true;}}return seen?Math.round(total*100)/100:null;}
async function readRaw(req,max=131072){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>max)throw new Error('REQUEST_TOO_LARGE');}return raw;}
function sendJson(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-ams-build':BUILD});res.end(JSON.stringify(body));}
async function accessToken(){const r=await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token',{headers:{'Metadata-Flavor':'Google'}});if(!r.ok)throw new Error('METADATA_TOKEN_'+r.status);const j=await r.json();if(!j.access_token)throw new Error('METADATA_TOKEN_MISSING');return j.access_token;}
async function auditPlanningRows(){if(!SID)throw new Error('DEV_SSOT_SPREADSHEET_ID_NOT_CONFIGURED');const token=await accessToken(),u=new URL('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(SID)+'/values/Audit%20planning!A1:AX483');u.searchParams.set('valueRenderOption','UNFORMATTED_VALUE');u.searchParams.set('dateTimeRenderOption','FORMATTED_STRING');const r=await fetch(u,{headers:{authorization:'Bearer '+token}}),j=await r.json();if(!r.ok)throw new Error('SHEETS_API_'+r.status+': '+JSON.stringify(j));return j.values||[];}
async function writeHoursProjection(auditId,hours){const values=await auditPlanningRows();if(values.length<2)throw new Error('AUDIT_PLANNING_EMPTY');const h=values[0],ci=col(h,['Audit ID','Audit_ID','AuditId','Audit Id']),ch=col(h,['Hours planned','Planned hours','Planned Hours','Hours Planned']);if(ci<0||ch<0)throw new Error('HOURS_PLANNED_SCHEMA_MISSING');let rowNo=0;for(let i=1;i<values.length;i++)if(val(values[i],ci)===clean(auditId)){rowNo=i+1;break;}if(!rowNo)throw new Error('AUDIT_NOT_FOUND');const token=await accessToken(),range='Audit planning!'+a1col(ch+1)+rowNo,u='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(SID)+'/values/'+encodeURIComponent(range)+'?valueInputOption=USER_ENTERED',r=await fetch(u,{method:'PUT',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({values:[[hours]]})}),j=await r.json();if(!r.ok)throw new Error('HOURS_PROJECTION_WRITE_'+r.status+': '+JSON.stringify(j));return{success:true,auditId:clean(auditId),hours,row:rowNo};}
async function enrichManagerOpen(obj){const rows=obj?.rows;if(!Array.isArray(rows)||!rows.some(r=>r&&!clean(r.hoursPlanned)))return obj;const values=await auditPlanningRows();if(values.length<2)return obj;const h=values[0],ci=col(h,['Audit ID','Audit_ID','AuditId','Audit Id']),cp=col(h,['Planning JSON','Planning_JSON']),byId=new Map();for(const row of values.slice(1)){const id=val(row,ci);if(id)byId.set(id,row);}let enriched=0;for(const r of rows){if(!r||clean(r.hoursPlanned))continue;const source=byId.get(clean(r.auditId));if(!source)continue;const hours=plannedHoursFromJson(val(source,cp));if(hours==null)continue;r.hoursPlanned=hours;r.plannedHours=hours;enriched++;}obj.hoursProjectionEnrichment={build:BUILD,enriched};return obj;}
function combinedRequest(body){const ids=[...new Set([clean(body?.auditId),...(Array.isArray(body?.visitAuditIds)?body.visitAuditIds.map(clean):[]),...(Array.isArray(body?.visitMembers)?body.visitMembers.map(x=>clean(x?.auditId)):[])].filter(Boolean))];return ids.length>1;}
async function proxy(req,res,raw){const target='http://127.0.0.1:'+INNER_PORT+(req.url||'/'),headers={};for(const [k,v] of Object.entries(req.headers)){if(v!=null&&!['host','content-length','connection'].includes(k.toLowerCase()))headers[k]=v;}const init={method:req.method,headers,redirect:'manual'};if(req.method!=='GET'&&req.method!=='HEAD')init.body=raw||'';const r=await fetch(target,init),buf=Buffer.from(await r.arrayBuffer()),outHeaders={};r.headers.forEach((v,k)=>{if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))outHeaders[k]=v;});outHeaders['x-ams-build']=BUILD;let body=buf;const u=new URL(req.url||'/','http://localhost'),ct=clean(r.headers.get('content-type'));
  if(r.ok&&req.method==='GET'&&u.pathname==='/api/v1/manager/open'&&ct.includes('application/json')){let j;try{j=JSON.parse(buf.toString('utf8'));}catch{j=null;}if(j){j=await enrichManagerOpen(j);body=Buffer.from(JSON.stringify(j),'utf8');outHeaders['content-length']=String(body.length);}}
  if(r.ok&&req.method==='POST'&&u.pathname==='/api/v1/planning/commit-handoff'&&ct.includes('application/json')){let requestBody=null,responseBody=null;try{requestBody=JSON.parse(raw||'{}');responseBody=JSON.parse(buf.toString('utf8'));}catch{}if(requestBody&&responseBody&&combinedRequest(requestBody)&&responseBody?.ok===true&&responseBody?.result?.success===true){const hours=plannedHoursFromBlocks(requestBody.blocks);if(hours!=null){try{responseBody.hoursProjectionWrite=await writeHoursProjection(requestBody.auditId,hours);}catch(e){responseBody.hoursProjectionWrite={success:false,error:clean(e?.message||e)};}body=Buffer.from(JSON.stringify(responseBody),'utf8');outHeaders['content-length']=String(body.length);}}}
  res.writeHead(r.status,outHeaders);res.end(body);
}

http.createServer(async(req,res)=>{const u=new URL(req.url||'/','http://localhost');if(req.method==='GET'&&u.pathname==='/api/v1/build')return sendJson(res,200,{ok:true,build:BUILD,inner:'server-r8.js',hoursProjection:true,ecasHoursSource:'Planning JSON totalPlannedHours'});let raw='';try{if(req.method!=='GET'&&req.method!=='HEAD')raw=await readRaw(req);}catch(e){return sendJson(res,413,{ok:false,error:clean(e?.message||e),build:BUILD});}try{return await proxy(req,res,raw);}catch(e){return sendJson(res,502,{ok:false,error:'R9_PROXY_FAILED',detail:clean(e?.message||e),build:BUILD});}}).listen(PUBLIC_PORT,'0.0.0.0');
